// 이 파일은 자동 생성됩니다. 직접 고치지 말고 sprites.py 를 고친 뒤
//     python tools/gen_sprites_cs.py
// 를 실행하세요.
using System.Collections.Generic;

namespace PokemonTaskbar
{
    public class PokemonSprite
    {
        public string Key;
        public string NameKo;
        public double ScaleFactor;
        public bool FacesRight;   // 원본 그림이 오른쪽을 보고 있는지
        public Dictionary<char, string> Palette;
        public string[][] Frames;   // 걷기 프레임마다 도트 줄 묶음
    }

    public static class Sprites
    {
        public static readonly List<PokemonSprite> All = new List<PokemonSprite>
        {
            new PokemonSprite
            {
                Key = "pikachu",
                NameKo = "피카츄",
                ScaleFactor = 0.3333333333333333,
                FacesRight = false,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#feba11" },
                    { 'Y', "#feed43" },
                    { 'O', "#000000" },
                    { 'W', "#542100" },
                    { 'R', "#984300" },
                    { 'B', "#dd9800" },
                    { 'G', "#fefeaa" },
                    { 'T', "#101010" },
                    { 'D', "#444355" },
                    { 'E', "#fdee42" },
                    { 'C', "#cb2110" },
                    { 'S', "#ed5443" },
                    { 'L', "#552000" },
                    { 'M', "#fdfefd" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".....OO",
                        "....OTO",
                        "....TTO",
                        "...OTTO",
                        "...OTTO",
                        "...WKBW",
                        "...WKKW..............OOOOOO",
                        "..WBKKW..........WWOOTDDDTO",
                        "..WKKKW........WWKYBTTDTTO",
                        "..WKKRRRRRRWWWOKYYYYBTTTO",
                        "..WREGGGGYYKBYYYYYYYKBOO",
                        "..RYGGGGGGYYYYYYYYYKWO..........RRRR",
                        "..KEGGGGGYYYYYYYKWOO.........RRRKYYW",
                        ".RYYGGGYYYYYYYYYWO........RRRKYYYYYW",
                        ".ODKYYYYYKDOKYYYW......RRRKYYYYYYYEW",
                        "ROMRYYYYYRMORYYKW.....RRYYYYYYYYYYYKW",
                        "RODREYYYYRDORYYKKW....RBKKKKYYYYYYYYW",
                        "RDOEYYYYYKODKYYKKW....RKKKKKKKKKYYYYW",
                        "RCYYRKYYYYYYYSSKKW....RKKKKKKKKKKKKKW",
                        "WCYBBYYYBYYYSSSCKW....WKKKKKKKKBOOOOO",
                        "WCKBKRRBYYYYSSCCKWO...WBKKKBWWWO",
                        ".WRKKKKKKKKKKCCKKWO....LKBWW",
                        "..WRBBKKKKKKKKKKKKO....WBKO",
                        "...LKKKKKKKKKKKKKKO.....OKKWW",
                        "...RKKKKKKKKKKKKYYRO.....OKKW",
                        "..WKBKKKKKKBKKWEYEWO....LBKO",
                        "..OKRKKKKKKRKKOEYYWO...WBBBOO",
                        "..OYYRYYYERYYOYYYYKRO...OBBBO",
                        "..OKYYRYYRYYKWYYYYYWOOOORRWO",
                        "..WLYYWYYWEYWYYYYYYWOWLLWOO",
                        ".RKYWWYYYYWWYYYYYYKWROWOO",
                        ".RKKYYYYYYYYYYYKKKKRBOO",
                        ".WKKKKYYYYYYKKKKKKKKKO",
                        ".WBKKKKKKKKKKKKKKKKKKO",
                        "..WBKKKKKKKKKKKKKKKKBO",
                        "..ORBBRWWWWWBBKKKKKBO",
                        ".OKKBOO.....WWWWRBRL",
                        ".OOOOO.........OKRKBO",
                        "................OOOOO",
                    },
                    new string[]
                    {
                        ".....OO",
                        "....OTO",
                        "....TTO",
                        "...OTTO",
                        "...OTTO",
                        "...WKBW",
                        "...WKKW..............OOOOOO",
                        "..WBKKW..........WWOOTDDDTO",
                        "..WKKKW........WWKYBTTDTTO",
                        "..WKKRRRRRRWWWOKYYYYBTTTO",
                        "..WREGGGGYYKBYYYYYYYKBOO",
                        "..RYGGGGGGYYYYYYYYYKWO..........RRRR",
                        "..KEGGGGGYYYYYYYKWOO.........RRRKYYW",
                        ".RYYGGGYYYYYYYYYWO........RRRKYYYYYW",
                        ".ODKYYYYYKDOKYYYW......RRRKYYYYYYYEW",
                        "ROMRYYYYYRMORYYKW.....RRYYYYYYYYYYYKW",
                        "RODREYYYYRDORYYKKW....RBKKKKYYYYYYYYW",
                        "RDOEYYYYYKODKYYKKW....RKKKKKKKKKYYYYW",
                        "RCYYRKYYYYYYYSSKKW....RKKKKKKKKKKKKKW",
                        "WCYBBYYYBYYYSSSCKW....WKKKKKKKKBOOOOO",
                        "WCKBKRRBYYYYSSCCKWO...WBKKKBWWWO",
                        ".WRKKKKKKKKKKCCKKWO....LKBWW",
                        "..WRBBKKKKKKKKKKKKO....WBKO",
                        "...LKKKKKKKKKKKKKKO.....OKKWW",
                        "...RKKKKKKKKKKKKYYRO.....OKKW",
                        "..WKBKKKKKKBKKWEYEWO....LBKO",
                        "..OKRKKKKKKRKKOEYYWO...WBBBOO",
                        "..OYYRYYYERYYOYYYYKRO...OBBBO",
                        "..OKYYRYYRYYKWYYYYYWOOOORRWO",
                        "..WLYYWYYWEYWYYYYYYWOWLLWOO",
                        ".RKYWWYYYYWWYYYYYYKWROWOO",
                        ".RKKYYYYYYYYYYYKKKKRBOO",
                        ".WKKKKYYYYYYKKKKKKKKKO",
                        ".WBKORBBRKKKKKKKKKKKKO",
                        "..WOKKBOOKKKKKKKKKKKBO",
                        "...OOOOOWWWWBBKWWRBRL",
                        "............WW..OKRKBO",
                        ".................OOOOO",
                        ".",
                    },
                    new string[]
                    {
                        ".....OO",
                        "....OTO",
                        "....TTO",
                        "...OTTO",
                        "...OTTO",
                        "...WKBW",
                        "...WKKW..............OOOOOO",
                        "..WBKKW..........WWOOTDDDTO",
                        "..WKKKW........WWKYBTTDTTO",
                        "..WKKRRRRRRWWWOKYYYYBTTTO",
                        "..WREGGGGYYKBYYYYYYYKBOO",
                        "..RYGGGGGGYYYYYYYYYKWO..........RRRR",
                        "..KEGGGGGYYYYYYYKWOO.........RRRKYYW",
                        ".RYYGGGYYYYYYYYYWO........RRRKYYYYYW",
                        ".ODKYYYYYKDOKYYYW......RRRKYYYYYYYEW",
                        "ROMRYYYYYRMORYYKW.....RRYYYYYYYYYYYKW",
                        "RODREYYYYRDORYYKKW....RBKKKKYYYYYYYYW",
                        "RDOEYYYYYKODKYYKKW....RKKKKKKKKKYYYYW",
                        "RCYYRKYYYYYYYSSKKW....RKKKKKKKKKKKKKW",
                        "WCYBBYYYBYYYSSSCKW....WKKKKKKKKBOOOOO",
                        "WCKBKRRBYYYYSSCCKWO...WBKKKBWWWO",
                        ".WRKKKKKKKKKKCCKKWO....LKBWW",
                        "..WRBBKKKKKKKKKKKKO....WBKO",
                        "...LKKKKKKKKKKKKKKO.....OKKWW",
                        "...RKKKKKKKKKKKKYYRO.....OKKW",
                        "..WKBKKKKKKBKKWEYEWO....LBKO",
                        "..OKRKKKKKKRKKOEYYWO...WBBBOO",
                        "..OYYRYYYERYYOYYYYKRO...OBBBO",
                        "..OKYYRYYRYYKWYYYYYWOOOORRWO",
                        "..WLYYWYYWEYWYYYYYYWOWLLWOO",
                        ".RKYWWYYYYWWYYYYYYKWROWOO",
                        ".RKKYYYYYYYYYYYKKKKRBOO",
                        ".WKKKKYYYYYYKKKKKKKKKO",
                        ".WBKKKKKKKKKKKKKKKKKKO",
                        "..WBKKKKKKKKKKKKKKKKBO",
                        "..ORBBRWWWWWBBKKKKKBO",
                        ".OKKBOO.....WWWWRBRL",
                        ".OOOOO.........OKRKBO",
                        "................OOOOO",
                    },
                    new string[]
                    {
                        ".....OO",
                        "....OTO",
                        "....TTO",
                        "...OTTO",
                        "...OTTO",
                        "...WKBW",
                        "...WKKW..............OOOOOO",
                        "..WBKKW..........WWOOTDDDTO",
                        "..WKKKW........WWKYBTTDTTO",
                        "..WKKRRRRRRWWWOKYYYYBTTTO",
                        "..WREGGGGYYKBYYYYYYYKBOO",
                        "..RYGGGGGGYYYYYYYYYKWO..........RRRR",
                        "..KEGGGGGYYYYYYYKWOO.........RRRKYYW",
                        ".RYYGGGYYYYYYYYYWO........RRRKYYYYYW",
                        ".ODKYYYYYKDOKYYYW......RRRKYYYYYYYEW",
                        "ROMRYYYYYRMORYYKW.....RRYYYYYYYYYYYKW",
                        "RODREYYYYRDORYYKKW....RBKKKKYYYYYYYYW",
                        "RDOEYYYYYKODKYYKKW....RKKKKKKKKKYYYYW",
                        "RCYYRKYYYYYYYSSKKW....RKKKKKKKKKKKKKW",
                        "WCYBBYYYBYYYSSSCKW....WKKKKKKKKBOOOOO",
                        "WCKBKRRBYYYYSSCCKWO...WBKKKBWWWO",
                        ".WRKKKKKKKKKKCCKKWO....LKBWW",
                        "..WRBBKKKKKKKKKKKKO....WBKO",
                        "...LKKKKKKKKKKKKKKO.....OKKWW",
                        "...RKKKKKKKKKKKKYYRO.....OKKW",
                        "..WKBKKKKKKBKKWEYEWO....LBKO",
                        "..OKRKKKKKKRKKOEYYWO...WBBBOO",
                        "..OYYRYYYERYYOYYYYKRO...OBBBO",
                        "..OKYYRYYRYYKWYYYYYWOOOORRWO",
                        "..WLYYWYYWEYWYYYYYYWOWLLWOO",
                        ".RKYWWYYYYWWYYYYYYKWROWOO",
                        ".RKKYYYYYYYYYYYKKKKRBOO",
                        ".WKKKKYYYYYYKKKKKKKKKO",
                        ".WBKKKKKKKKKKKKKKKKKKO",
                        "..WORBBRKKKKKKKKWWRBRL",
                        "..OKKBOOWWWWBBKKKOKRKBO",
                        "..OOOOO.....WW....OOOOO",
                        ".",
                        ".",
                    },
                },
            },
            new PokemonSprite
            {
                Key = "charmander",
                NameKo = "파이리",
                ScaleFactor = 0.3333333333333333,
                FacesRight = false,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#fc9443" },
                    { 'Y', "#d95339" },
                    { 'O', "#170c0c" },
                    { 'W', "#862b09" },
                    { 'R', "#fdd47a" },
                    { 'B', "#e7aa5b" },
                    { 'G', "#db3f0b" },
                    { 'T', "#fccf10" },
                    { 'D', "#fbc364" },
                    { 'E', "#f4a10c" },
                    { 'C', "#11387f" },
                    { 'S', "#fafcfb" },
                    { 'L', "#2885a8" },
                    { 'M', "#36aae9" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".........YYWWW",
                        ".......YYKKKKKWW",
                        "......YDKKKKKKKKO",
                        ".....YDDDKKKKKKKO",
                        ".....YDDDKKKKKKKKO",
                        "....YKKDKKKKKYKKKO",
                        "....YKKKKKKKYKKKKYO",
                        "....CYKKKKKKYKCCYYO",
                        "....LYKKKKKKKCCCWYO",
                        ".....KKKKKKKKSOLWYO",
                        "....OKKKKKKKKSCMWYO.............Y",
                        "...WCKKKKKKKKWLMYYO.............YT",
                        "...WDDDKKKKKKKYYYYO.............YT",
                        "...WDDKKYKKKKYYWYYO............GET",
                        "....WKKKKKKKYWWYYO......WW.....GTTE",
                        "....OOKKKKWWOSYYYO..WWWWYO.....GETTG",
                        ".WW...OOOOGGWYYYYWWWKKKKYO.....GTGTE",
                        ".OYWWWOYYWWWYYOYYKKKKKKYYYO...GGGGTTG",
                        ".OYKKKYOOKKYOOYYYYKKYYYYOO....GGEGGTEG",
                        "OYYYKKYYYOOOYYYYYYYYYYYO......GTTGTTTG",
                        ".OOYYYYYYYYYYYYYYYYYYOO.......GETTTTTG",
                        "...OOYYYYWYBBBYYYYWWO.........GEEETTEG",
                        ".....OOYYWBBBBBYYKKO...........GEGEEGG",
                        ".......OWYRRRRRBKKKO............YGWGG",
                        "........WBRRRRRRKKKYO............WWG",
                        "........WRRRRRRRKKKKO............WDO",
                        "........WRRRRRRRKKKKKO...........WKO",
                        ".......WBRRRRRRRBKKKKO..........WKKO",
                        ".......WRRRRRRRRRKKKKO........WWKKYO",
                        "......WWRRRRRRRRRYKKKKO....WWWKKKYO",
                        ".....WKYBRRRRRRRBYKKKKYOWWWKKKKKYBO",
                        ".....WKKYBRRRRBBYKKKKKKOYYYYKKYBBO",
                        "....OKKKWBBBBBBBYKKKKKKYOYYYYYBBO",
                        "....OKKKKOBBBBBBYKKKKKYYOYYYBBBO",
                        "....OKKKKYOBBBBBWYKKKYYYOBBBBOO",
                        ".....OKKYYYOOBBBWYYYYYYYOBBWW",
                        "......OYYYYYYOOOOWYYYYYOWWW",
                        "......OYYYYOO.....WYYYYO",
                        ".....OYYYYYO......WKKKYO",
                        "....OSWSYYO.......WYKKKYO",
                        ".....OOOOO.........OSWSWSO",
                        "....................OOOOO",
                    },
                    new string[]
                    {
                        ".........YYWWW",
                        ".......YYKKKKKWW",
                        "......YDKKKKKKKKO",
                        ".....YDDDKKKKKKKO",
                        ".....YDDDKKKKKKKKO",
                        "....YKKDKKKKKYKKKO",
                        "....YKKKKKKKYKKKKYO",
                        "....CYKKKKKKYKCCYYO",
                        "....LYKKKKKKKCCCWYO",
                        ".....KKKKKKKKSOLWYO",
                        "....OKKKKKKKKSCMWYO.............Y",
                        "...WCKKKKKKKKWLMYYO.............YT",
                        "...WDDDKKKKKKKYYYYO.............YT",
                        "...WDDKKYKKKKYYWYYO............GET",
                        "....WKKKKKKKYWWYYO......WW.....GTTE",
                        "....OOKKKKWWOSYYYO..WWWWYO.....GETTG",
                        ".WW...OOOOGGWYYYYWWWKKKKYO.....GTGTE",
                        ".OYWWWOYYWWWYYOYYKKKKKKYYYO...GGGGTTG",
                        ".OYKKKYOOKKYOOYYYYKKYYYYOO....GGEGGTEG",
                        "OYYYKKYYYOOOYYYYYYYYYYYO......GTTGTTTG",
                        ".OOYYYYYYYYYYYYYYYYYYOO.......GETTTTTG",
                        "...OOYYYYWYBBBYYYYWWO.........GEEETTEG",
                        ".....OOYYWBBBBBYYKKO...........GEGEEGG",
                        ".......OWYRRRRRBKKKO............YGWGG",
                        "........WBRRRRRRKKKYO............WWG",
                        "........WRRRRRRRKKKKO............WDO",
                        "........WRRRRRRRKKKKKO...........WKO",
                        ".......WBRRRRRRRBKKKKO..........WKKO",
                        ".......WRRRRRRRRRKKKKO........WWKKYO",
                        "......WWRRRRRRRRRYKKKKO....WWWKKKYO",
                        ".....WKYBRRRRRRRBYKKKKYOWWWKKKKKYBO",
                        ".....WKKYBRRRRBBYKKKKKKOYYYYKKYBBO",
                        "....OKKKWBBBBBBBYKKKKKKYOYYYYYBBO",
                        "....OKKKKOBBBBBBYKKKKKYYOYYYBBBO",
                        "....OKKKKYOBBBBBWYKKKYYYOBBBBOO",
                        ".....OKKOYYYYOOBWYYYYYYYOBBWW",
                        "......OOYYYYYOOOOWYWYYYYOWW",
                        "......OSWSYYO......WKKKYO",
                        ".......OOOOO.......WYKKKYO",
                        "....................OSWSWSO",
                        ".....................OOOOO",
                        ".",
                    },
                    new string[]
                    {
                        ".........YYWWW",
                        ".......YYKKKKKWW",
                        "......YDKKKKKKKKO",
                        ".....YDDDKKKKKKKO",
                        ".....YDDDKKKKKKKKO",
                        "....YKKDKKKKKYKKKO",
                        "....YKKKKKKKYKKKKYO",
                        "....CYKKKKKKYKCCYYO",
                        "....LYKKKKKKKCCCWYO",
                        ".....KKKKKKKKSOLWYO",
                        "....OKKKKKKKKSCMWYO.............Y",
                        "...WCKKKKKKKKWLMYYO.............YT",
                        "...WDDDKKKKKKKYYYYO.............YT",
                        "...WDDKKYKKKKYYWYYO............GET",
                        "....WKKKKKKKYWWYYO......WW.....GTTE",
                        "....OOKKKKWWOSYYYO..WWWWYO.....GETTG",
                        ".WW...OOOOGGWYYYYWWWKKKKYO.....GTGTE",
                        ".OYWWWOYYWWWYYOYYKKKKKKYYYO...GGGGTTG",
                        ".OYKKKYOOKKYOOYYYYKKYYYYOO....GGEGGTEG",
                        "OYYYKKYYYOOOYYYYYYYYYYYO......GTTGTTTG",
                        ".OOYYYYYYYYYYYYYYYYYYOO.......GETTTTTG",
                        "...OOYYYYWYBBBYYYYWWO.........GEEETTEG",
                        ".....OOYYWBBBBBYYKKO...........GEGEEGG",
                        ".......OWYRRRRRBKKKO............YGWGG",
                        "........WBRRRRRRKKKYO............WWG",
                        "........WRRRRRRRKKKKO............WDO",
                        "........WRRRRRRRKKKKKO...........WKO",
                        ".......WBRRRRRRRBKKKKO..........WKKO",
                        ".......WRRRRRRRRRKKKKO........WWKKYO",
                        "......WWRRRRRRRRRYKKKKO....WWWKKKYO",
                        ".....WKYBRRRRRRRBYKKKKYOWWWKKKKKYBO",
                        ".....WKKYBRRRRBBYKKKKKKOYYYYKKYBBO",
                        "....OKKKWBBBBBBBYKKKKKKYOYYYYYBBO",
                        "....OKKKKOBBBBBBYKKKKKYYOYYYBBBO",
                        "....OKKKKYOBBBBBWYKKKYYYOBBBBOO",
                        ".....OKKYYYOOBBBWYYYYYYYOBBWW",
                        "......OYYYYYYOOOOWYYYYYOWWW",
                        "......OYYYYOO.....WYYYYO",
                        ".....OYYYYYO......WKKKYO",
                        "....OSWSYYO.......WYKKKYO",
                        ".....OOOOO.........OSWSWSO",
                        "....................OOOOO",
                    },
                    new string[]
                    {
                        ".........YYWWW",
                        ".......YYKKKKKWW",
                        "......YDKKKKKKKKO",
                        ".....YDDDKKKKKKKO",
                        ".....YDDDKKKKKKKKO",
                        "....YKKDKKKKKYKKKO",
                        "....YKKKKKKKYKKKKYO",
                        "....CYKKKKKKYKCCYYO",
                        "....LYKKKKKKKCCCWYO",
                        ".....KKKKKKKKSOLWYO",
                        "....OKKKKKKKKSCMWYO.............Y",
                        "...WCKKKKKKKKWLMYYO.............YT",
                        "...WDDDKKKKKKKYYYYO.............YT",
                        "...WDDKKYKKKKYYWYYO............GET",
                        "....WKKKKKKKYWWYYO......WW.....GTTE",
                        "....OOKKKKWWOSYYYO..WWWWYO.....GETTG",
                        ".WW...OOOOGGWYYYYWWWKKKKYO.....GTGTE",
                        ".OYWWWOYYWWWYYOYYKKKKKKYYYO...GGGGTTG",
                        ".OYKKKYOOKKYOOYYYYKKYYYYOO....GGEGGTEG",
                        "OYYYKKYYYOOOYYYYYYYYYYYO......GTTGTTTG",
                        ".OOYYYYYYYYYYYYYYYYYYOO.......GETTTTTG",
                        "...OOYYYYWYBBBYYYYWWO.........GEEETTEG",
                        ".....OOYYWBBBBBYYKKO...........GEGEEGG",
                        ".......OWYRRRRRBKKKO............YGWGG",
                        "........WBRRRRRRKKKYO............WWG",
                        "........WRRRRRRRKKKKO............WDO",
                        "........WRRRRRRRKKKKKO...........WKO",
                        ".......WBRRRRRRRBKKKKO..........WKKO",
                        ".......WRRRRRRRRRKKKKO........WWKKYO",
                        "......WWRRRRRRRRRYKKKKO....WWWKKKYO",
                        ".....WKYBRRRRRRRBYKKKKYOWWWKKKKKYBO",
                        ".....WKKYBRRRRBBYKKKKKKOYYYYKKYBBO",
                        "....OKKKWBBBBBBBYKKKKKKYOYYYYYBBO",
                        "....OKKKKOBBBBBBYKKKKKYYOYYYBBBO",
                        "....OKKKKYOBBBBBWYKKKYYYOBBBBOO",
                        ".....OKKYYYOOBBBWYYYWYYYYOBWW",
                        "......OOYYYYOOOOOWYYWKKKYOW",
                        "......OYYYYYO.......WYKKKYO",
                        ".....OSWSYYO.........OSWSWSO",
                        "......OOOOO...........OOOOO",
                        ".",
                        ".",
                    },
                },
            },
            new PokemonSprite
            {
                Key = "bulbasaur",
                NameKo = "이상해씨",
                ScaleFactor = 1.0,
                FacesRight = true,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#2b2b2b" },
                    { 'T', "#7ec8a4" },
                    { 'D', "#4e9e7c" },
                    { 'G', "#6dbe45" },
                    { 'E', "#4a9130" },
                    { 'W', "#ffffff" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".......KKGGGGKK",
                        "......KGGEGGEGGK",
                        ".....KGGGGEGGGGGK",
                        ".....KGGEGGGGEGGK",
                        "....KKKGGGGGGGKKK",
                        "...KTTTKKKKKKKTTTK",
                        "..KTTDTTTTTTTTTDTTK",
                        "..KTTTTTTTTTTTTTTTK",
                        "..KTKWKTTTTTTKWKTTK",
                        "..KTKKKTTTTTTKKKTTK",
                        "..KTTTTTTKKTTTTTTTK",
                        "..KTTDTTTTTTTTTDTTK",
                        "...KTTTTTTTTTTTTTK",
                        "...KTTTTTTTTTTTTTK",
                        "...KKTTKKKKKKTTKK",
                        "....KKKK....KKKK",
                    },
                    new string[]
                    {
                        ".......KKGGGGKK",
                        "......KGGEGGEGGK",
                        ".....KGGGGEGGGGGK",
                        ".....KGGEGGGGEGGK",
                        "....KKKGGGGGGGKKK",
                        "...KTTTKKKKKKKTTTK",
                        "..KTTDTTTTTTTTTDTTK",
                        "..KTTTTTTTTTTTTTTTK",
                        "..KTKWKTTTTTTKWKTTK",
                        "..KTKKKTTTTTTKKKTTK",
                        "..KTTTTTTKKTTTTTTTK",
                        "..KTTDTTTTTTTTTDTTK",
                        "...KTTTTTTTTTTTTTK",
                        "...KTTTTTTTTTTTTTK",
                        "..KKTTKKKKKKTTKK",
                        "..KKKK......KKKK",
                    },
                },
            },
            new PokemonSprite
            {
                Key = "squirtle",
                NameKo = "꼬부기",
                ScaleFactor = 1.0,
                FacesRight = true,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#2b2b2b" },
                    { 'B', "#78c8f0" },
                    { 'D', "#3878a8" },
                    { 'S', "#c87838" },
                    { 'L', "#f0c078" },
                    { 'C', "#f8e8c0" },
                    { 'W', "#ffffff" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        "......KKKKKK",
                        ".....KBBBBBBK",
                        "....KBBBBBBBBK",
                        "....KBKWKBBKWKBK",
                        "....KBKKKBBKKKBK",
                        "....KBBBBBBBBBBK",
                        ".....KBBDDDDBBK",
                        "....KKKKKKKKKKKK",
                        "...KSSLLSSSSLLSSK",
                        "..KSLLSSSSSSSSLLSK",
                        "..KSSSSCCCCCCSSSSK",
                        "..KSLLSCCCCCCSLLSK",
                        "..KSSSSCCCCCCSSSSK",
                        "...KSSSSSSSSSSSSK",
                        "....KKBBKKKKBBKK",
                        ".....KKKK..KKKK",
                    },
                    new string[]
                    {
                        "......KKKKKK",
                        ".....KBBBBBBK",
                        "....KBBBBBBBBK",
                        "....KBKWKBBKWKBK",
                        "....KBKKKBBKKKBK",
                        "....KBBBBBBBBBBK",
                        ".....KBBDDDDBBK",
                        "....KKKKKKKKKKKK",
                        "...KSSLLSSSSLLSSK",
                        "..KSLLSSSSSSSSLLSK",
                        "..KSSSSCCCCCCSSSSK",
                        "..KSLLSCCCCCCSLLSK",
                        "..KSSSSCCCCCCSSSSK",
                        "...KSSSSSSSSSSSSK",
                        "...KKBBKKKKBBKK",
                        "...KKKK....KKKK",
                    },
                },
            },
        };

        public static PokemonSprite Find(string key)
        {
            foreach (PokemonSprite sprite in All)
            {
                if (sprite.Key == key)
                {
                    return sprite;
                }
            }
            return null;
        }
    }
}
