// 이 파일은 자동 생성됩니다. 직접 고치지 말고 sprites.py 를 고친 뒤
//     python tools/gen_sprites_cs.py
// 를 실행하세요.
using System.Collections.Generic;

namespace PokemonTaskbar
{
    public class PokemonSprite
    {
        public string Key;
        public string NameKo;
        public double ScaleFactor;
        public bool FacesRight;   // 원본 그림이 오른쪽을 보고 있는지
        public bool Hops;         // 걷지 않고 폴짝 뛰어 다니는지
        public bool Bounce;       // 걸을 때 프로그램이 살짝 띄워 줄지
        public Dictionary<char, string> Palette;
        public string[][] Frames;   // 걷기 프레임마다 도트 줄 묶음
        public Dictionary<string, string[]> Poses;  // 상황별 자세 (squash/stretch/blink)
    }

    public static class Sprites
    {
        public static readonly List<PokemonSprite> All = new List<PokemonSprite>
        {
            new PokemonSprite
            {
                Key = "pikachu",
                NameKo = "피카츄",
                ScaleFactor = 0.3333333333333333,
                FacesRight = false,
                Hops = false,
                Bounce = true,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#fcb913" },
                    { 'Y', "#feed43" },
                    { 'O', "#552403" },
                    { 'W', "#020000" },
                    { 'R', "#964703" },
                    { 'B', "#fdec49" },
                    { 'G', "#da9705" },
                    { 'T', "#f2eeea" },
                    { 'D', "#fdeb45" },
                    { 'E', "#141210" },
                    { 'C', "#fefda7" },
                    { 'S', "#47444f" },
                    { 'L', "#c7250e" },
                    { 'M', "#eb563f" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".",
                        ".",
                        ".....TWW",
                        ".....WEW",
                        "....TEEW",
                        "....WEEW",
                        "....WEEW",
                        "....OKGO",
                        "...TOKKO..........TTTTWWWWWW",
                        "...OGKKO..........OOWWESSSEW",
                        "...OKKKOTTTTTTTTOOKDGEESEEE",
                        "...OKKRRRRRROOOWKYYYYGEEEW",
                        "...ORBCCCCBBKGBBYYYYYKGEE........TTTT",
                        "...RBCCCCCCYYYYYYYDBKOW..........RRRR",
                        "..TKDCCCCCBYYYYYYKOEE......TTTRRRKYBO",
                        "..RBBCCCBYYBBYYYBOW........RRRKYYYYBO",
                        ".TWSKBDDYYKSWKYYDO.....TRRRKDDYYYYYBOT",
                        ".RWTRBYYYYRTWRYYKO.....RRBYYYYYYYYYYKO",
                        ".RWSRBYYYYRSWRDYKKO....RGKKKKYYYYYYYBO",
                        ".RSWBBYYYYKWSKBDKKO....RKKKKKKKKKYYYBO",
                        ".RLBDRKYYDYBBDMMKKO....RKKKKKKKKKKKKKO",
                        ".OLDGGDDYGYYBMMMLKO....OKKKKKKKKGWWWWW",
                        ".OLKGKRRGYYYDMMLLKOW...OGKKKGOOOE",
                        "..ORKKKKKKKKKKLLKKOW....OKGOO",
                        "...ORGGKKKKKKKKKKKKW....OGKETT",
                        "....OKKKKKKKKKKKKKKW.....WKKOO",
                        "...TRKKKKKKKKKKKKYYRW....TEKKO",
                        "...OKGKKKKKKGKKOBYYOW....OGKW",
                        "...WKRKKKKKKRKKWBYDOW...OGGGWW",
                        "...WBDRDYYDRBDWBYYYKRW...WGGGW",
                        "...WKYBRBYRDYKODYYYBOWWWWRROW",
                        "...OOBBOBDOBBOBYYYYDOWOOOOWW",
                        "..RKBOOBYYBOOBYYYYYKORWOWW",
                        "..RKKDYYYYYBDYYYKKKKRGWW",
                        "..OKKKKYYYYYYKKKKKKKKKW",
                        "..OGKKKKKKKKKKKKKKKKKKW",
                        "...OGKKKKKKKKKKKKKKKKGW",
                        "...WRGGROOOOOGGKKKKKGW",
                        "..WKKGWW.....OOOORGRO",
                        "..WWWWW.........WKRKGW",
                        ".................WWWWW",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        ".....TWW",
                        ".....WEW",
                        "....TEEW",
                        "....WEEW",
                        "....WEEW",
                        "....OKGO",
                        "...TOKKO..........TTTTWWWWWW",
                        "...OGKKO..........OOWWESSSEW",
                        "...OKKKOTTTTTTTTOOKDGEESEEE",
                        "...OKKRRRRRROOOWKYYYYGEEEW",
                        "...ORBCCCCBBKGBBYYYYYKGEE........TTTT",
                        "...RBCCCCCCYYYYYYYDBKOW..........RRRR",
                        "..TKDCCCCCBYYYYYYKOEE......TTTRRRKYBO",
                        "..RBBCCCBYYBBYYYBOW........RRRKYYYYBO",
                        ".TWSKBDDYYKSWKYYDO.....TRRRKDDYYYYYBOT",
                        ".RWTRBYYYYRTWRYYKO.....RRBYYYYYYYYYYKO",
                        ".RWSRBYYYYRSWRDYKKO....RGKKKKYYYYYYYBO",
                        ".RSWBBYYYYKWSKBDKKO....RKKKKKKKKKYYYBO",
                        ".RLBDRKYYDYBBDMMKKO....RKKKKKKKKKKKKKO",
                        ".OLDGGDDYGYYBMMMLKO....OKKKKKKKKGWWWWW",
                        ".OLKGKRRGYYYDMMLLKOW...OGKKKGOOOE",
                        "..ORKKKKKKKKKKLLKKOW....OKGOO",
                        "...ORGGKKKKKKKKKKKKW....OGKETT",
                        "....OKKKKKKKKKKKKKKW.....WKKOO",
                        "...TRKKKKKKKKKKKKYYRW....TEKKO",
                        "...OKGKKKKKKGKKOBYYOW....OGKW",
                        "...WKRKKKKKKRKKWBYDOW...OGGGWW",
                        "...WBDRDYYDRBDWBYYYKRW...WGGGW",
                        "...WKYBRBYRDYKODYYYBOWWWWRROW",
                        "...OOBBOBDOBBOBYYYYDOWOOOOWW",
                        "..RKBOOBYYBOOBYYYYYKORWOWW",
                        "..RKKDYYYYYBDYYYKKKKRGWW",
                        "..OKKKKYYYYYYKKKKKKKKKW",
                        "..OGKWRGGRKKKKKKKKKKKKW",
                        "...OWKKGWWKKKKKKKKKKKGW",
                        "....WWWWWOOOOGGKOORGRO",
                        ".............OO..WKRKGW",
                        "..................WWWWW",
                        ".",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        ".....TWW",
                        ".....WEW",
                        "....TEEW",
                        "....WEEW",
                        "....WEEW",
                        "....OKGO",
                        "...TOKKO..........TTTTWWWWWW",
                        "...OGKKO..........OOWWESSSEW",
                        "...OKKKOTTTTTTTTOOKDGEESEEE",
                        "...OKKRRRRRROOOWKYYYYGEEEW",
                        "...ORBCCCCBBKGBBYYYYYKGEE........TTTT",
                        "...RBCCCCCCYYYYYYYDBKOW..........RRRR",
                        "..TKDCCCCCBYYYYYYKOEE......TTTRRRKYBO",
                        "..RBBCCCBYYBBYYYBOW........RRRKYYYYBO",
                        ".TWSKBDDYYKSWKYYDO.....TRRRKDDYYYYYBOT",
                        ".RWTRBYYYYRTWRYYKO.....RRBYYYYYYYYYYKO",
                        ".RWSRBYYYYRSWRDYKKO....RGKKKKYYYYYYYBO",
                        ".RSWBBYYYYKWSKBDKKO....RKKKKKKKKKYYYBO",
                        ".RLBDRKYYDYBBDMMKKO....RKKKKKKKKKKKKKO",
                        ".OLDGGDDYGYYBMMMLKO....OKKKKKKKKGWWWWW",
                        ".OLKGKRRGYYYDMMLLKOW...OGKKKGOOOE",
                        "..ORKKKKKKKKKKLLKKOW....OKGOO",
                        "...ORGGKKKKKKKKKKKKW....OGKETT",
                        "....OKKKKKKKKKKKKKKW.....WKKOO",
                        "...TRKKKKKKKKKKKKYYRW....TEKKO",
                        "...OKGKKKKKKGKKOBYYOW....OGKW",
                        "...WKRKKKKKKRKKWBYDOW...OGGGWW",
                        "...WBDRDYYDRBDWBYYYKRW...WGGGW",
                        "...WKYBRBYRDYKODYYYBOWWWWRROW",
                        "...OOBBOBDOBBOBYYYYDOWOOOOWW",
                        "..RKBOOBYYBOOBYYYYYKORWOWW",
                        "..RKKDYYYYYBDYYYKKKKRGWW",
                        "..OKKKKYYYYYYKKKKKKKKKW",
                        "..OGKKKKKKKKKKKKKKKKKKW",
                        "...OGKKKKKKKKKKKKKKKKGW",
                        "...WRGGROOOOOGGKKKKKGW",
                        "..WKKGWW.....OOOORGRO",
                        "..WWWWW.........WKRKGW",
                        ".................WWWWW",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        ".....TWW",
                        ".....WEW",
                        "....TEEW",
                        "....WEEW",
                        "....WEEW",
                        "....OKGO",
                        "...TOKKO..........TTTTWWWWWW",
                        "...OGKKO..........OOWWESSSEW",
                        "...OKKKOTTTTTTTTOOKDGEESEEE",
                        "...OKKRRRRRROOOWKYYYYGEEEW",
                        "...ORBCCCCBBKGBBYYYYYKGEE........TTTT",
                        "...RBCCCCCCYYYYYYYDBKOW..........RRRR",
                        "..TKDCCCCCBYYYYYYKOEE......TTTRRRKYBO",
                        "..RBBCCCBYYBBYYYBOW........RRRKYYYYBO",
                        ".TWSKBDDYYKSWKYYDO.....TRRRKDDYYYYYBOT",
                        ".RWTRBYYYYRTWRYYKO.....RRBYYYYYYYYYYKO",
                        ".RWSRBYYYYRSWRDYKKO....RGKKKKYYYYYYYBO",
                        ".RSWBBYYYYKWSKBDKKO....RKKKKKKKKKYYYBO",
                        ".RLBDRKYYDYBBDMMKKO....RKKKKKKKKKKKKKO",
                        ".OLDGGDDYGYYBMMMLKO....OKKKKKKKKGWWWWW",
                        ".OLKGKRRGYYYDMMLLKOW...OGKKKGOOOE",
                        "..ORKKKKKKKKKKLLKKOW....OKGOO",
                        "...ORGGKKKKKKKKKKKKW....OGKETT",
                        "....OKKKKKKKKKKKKKKW.....WKKOO",
                        "...TRKKKKKKKKKKKKYYRW....TEKKO",
                        "...OKGKKKKKKGKKOBYYOW....OGKW",
                        "...WKRKKKKKKRKKWBYDOW...OGGGWW",
                        "...WBDRDYYDRBDWBYYYKRW...WGGGW",
                        "...WKYBRBYRDYKODYYYBOWWWWRROW",
                        "...OOBBOBDOBBOBYYYYDOWOOOOWW",
                        "..RKBOOBYYBOOBYYYYYKORWOWW",
                        "..RKKDYYYYYBDYYYKKKKRGWW",
                        "..OKKKKYYYYYYKKKKKKKKKW",
                        "..OGKKKKKKKKKKKKKKKKKKW",
                        "...OWRGGRKKKKKKKKOORGRO",
                        "...WKKGWWOOOOGGKKKWKRKGW",
                        "...WWWWW.....OO....WWWWW",
                        ".",
                        ".",
                    },
                },
                Poses = new Dictionary<string, string[]>
                {
                    { "blink", new string[]
                        {
                            ".",
                            ".",
                            ".....TWW",
                            ".....WEW",
                            "....TEEW",
                            "....WEEW",
                            "....WEEW",
                            "....OKGO",
                            "...TOKKO..........TTTTWWWWWW",
                            "...OGKKO..........OOWWESSSEW",
                            "...OKKKOTTTTTTTTOOKDGEESEEE",
                            "...OKKRRRRRROOOWKYYYYGEEEW",
                            "...ORBCCCCBBKGBBYYYYYKGEE........TTTT",
                            "...RBCCCCCCYYYYYYYDBKOW..........RRRR",
                            "..TKDCCCCCBYYYYYYKOEE......TTTRRRKYBO",
                            "..RBBCCCBYYBBYYYBOW........RRRKYYYYBO",
                            ".BBBBBDDYYYYYYYYDO.....TRRRKDDYYYYYBOT",
                            ".WWWWBYYYYWWWWYYKO.....RRBYYYYYYYYYYKO",
                            ".BBBBBYYYYYYYYDYKKO....RGKKKKYYYYYYYBO",
                            ".BBBBBYYYYYYYYBDKKO....RKKKKKKKKKYYYBO",
                            ".RLBDRKYYDYBBDMMKKO....RKKKKKKKKKKKKKO",
                            ".OLDGGDDYGYYBMMMLKO....OKKKKKKKKGWWWWW",
                            ".OLKGKRRGYYYDMMLLKOW...OGKKKGOOOE",
                            "..ORKKKKKKKKKKLLKKOW....OKGOO",
                            "...ORGGKKKKKKKKKKKKW....OGKETT",
                            "....OKKKKKKKKKKKKKKW.....WKKOO",
                            "...TRKKKKKKKKKKKKYYRW....TEKKO",
                            "...OKGKKKKKKGKKOBYYOW....OGKW",
                            "...WKRKKKKKKRKKWBYDOW...OGGGWW",
                            "...WBDRDYYDRBDWBYYYKRW...WGGGW",
                            "...WKYBRBYRDYKODYYYBOWWWWRROW",
                            "...OOBBOBDOBBOBYYYYDOWOOOOWW",
                            "..RKBOOBYYBOOBYYYYYKORWOWW",
                            "..RKKDYYYYYBDYYYKKKKRGWW",
                            "..OKKKKYYYYYYKKKKKKKKKW",
                            "..OGKKKKKKKKKKKKKKKKKKW",
                            "...OGKKKKKKKKKKKKKKKKGW",
                            "...WRGGROOOOOGGKKKKKGW",
                            "..WKKGWW.....OOOORGRO",
                            "..WWWWW.........WKRKGW",
                            ".................WWWWW",
                        }
                    },
                    { "squash", new string[]
                        {
                            ".",
                            ".",
                            ".",
                            ".",
                            ".....TWW",
                            ".....WEW",
                            "....TEEW",
                            "....WEEW",
                            "....WEEW",
                            "....OKGO",
                            "...TOKKO..........TTTTTWWWWWW",
                            "...OGKKO..........OOOWWESSSEW",
                            "...OKKKOTTTTTTTTOOKDDGEESEEE",
                            "...OKKRRRRRROOOWKYYYYYGEEEW",
                            "...ORBCCCCBBKGBBYYYYYYKGEE........TTTT",
                            "...RBCCCCCCYYYYYYYDBBKOW..........RRRR",
                            "..TKDCCCCCBYYYYYYKOEEE......TTTRRRKYBO",
                            "..RBBCCCBYYBBYYYBOW.........RRRKYYYYBO",
                            "TTWSKBDDYYKSWKYYDO......TRRRKDDYYYYYBOT",
                            "RRWTRBYYYYRTWRYYKO......RRBYYYYYYYYYYKO",
                            "RRWSRBYYYYRSWRDYKKO.....RGKKKKYYYYYYYBO",
                            "RRSWBBYYYYKWSKBDKKO.....RKKKKKKKKKYYYBO",
                            "RRLBDRKYYDYBBDMMKKO.....RKKKKKKKKKKKKKO",
                            "OOLKGKRRGYYYDMMLLKOWW...OGKKKGOOOE",
                            "..ORKKKKKKKKKKLLKKOWW....OKGOO",
                            "...ORGGKKKKKKKKKKKKWW....OGKETT",
                            "....OKKKKKKKKKKKKKKWW.....WKKOO",
                            "...TRKKKKKKKKKKKKYYRRW....TEKKO",
                            "...OKGKKKKKKGKKOBYYOOW....OGKW",
                            "...WKRKKKKKKRKKWBYDOOW...OGGGWW",
                            "...WBDRDYYDRBDWBYYYKKRW...WGGGW",
                            "...WKYBRBYRDYKODYYYBBOWWWWRROW",
                            "...OOBBOBDOBBOBYYYYDDOWOOOOWW",
                            "..RKBOOBYYBOOBYYYYYKKORWOWW",
                            "..RKKDYYYYYBDYYYKKKKKRGWW",
                            "..OKKKKYYYYYYKKKKKKKKKKW",
                            "..OGKKKKKKKKKKKKKKKKKKKW",
                            "...OGKKKKKKKKKKKKKKKKKGW",
                            "...WRGGROOOOOGGKKKKKKGW",
                            "..WKKGWW.....OOOORGRRO",
                            "..WWWWW.........WKRKKGW",
                        }
                    },
                    { "stretch", new string[]
                        {
                            "......TWW",
                            "......TWW",
                            "......WEW",
                            ".....TEEW",
                            ".....WEEW",
                            ".....WEEW",
                            ".....OKGO",
                            "....TOKKO..........TTTWWWWWW",
                            "....OGKKO..........OWWESSSEW",
                            "....OKKKOTTTTTTTTOOKGEESEEE",
                            "....OKKRRRRRROOOWKYYYGEEEW",
                            "....ORBCCCCBBKGBBYYYYKGEE........TTTT",
                            "....RBCCCCCCYYYYYYYDKOW..........RRRR",
                            "...TKDCCCCCBYYYYYYKOE......TTTRRRKYBO",
                            "...RBBCCCBYYBBYYYBOW.......RRRKYYYYBO",
                            "..TWSKBDDYYKSWKYYDO....TRRRKDDYYYYYBO",
                            "..RWTRBYYYYRTWRYYKO....RRBYYYYYYYYYYK",
                            "..RWSRBYYYYRSWRDYKKO...RGKKKKYYYYYYYB",
                            "..RSWBBYYYYKWSKBDKKO...RKKKKKKKKKYYYB",
                            "..RLBDRKYYDYBBDMMKKO...RKKKKKKKKKKKKK",
                            "..OLDGGDDYGYYBMMMLKO...OKKKKKKKKGWWWW",
                            "..OLDGGDDYGYYBMMMLKO...OKKKKKKKKGWWWW",
                            "..OLKGKRRGYYYDMMLLKO...OGKKKGOOOE",
                            "...ORKKKKKKKKKKLLKKO....OKGOO",
                            "....ORGGKKKKKKKKKKKK....OGKETT",
                            ".....OKKKKKKKKKKKKKK.....WKKOO",
                            "....TRKKKKKKKKKKKKYYW....TEKKO",
                            "....OKGKKKKKKGKKOBYYW....OGKW",
                            "....WKRKKKKKKRKKWBYDW...OGGGWW",
                            "....WBDRDYYDRBDWBYYYRW...WGGGW",
                            "....WKYBRBYRDYKODYYYOWWWWRROW",
                            "....OOBBOBDOBBOBYYYYOWOOOOWW",
                            "...RKBOOBYYBOOBYYYYYORWOWW",
                            "...RKKDYYYYYBDYYYKKKRGWW",
                            "...OKKKKYYYYYYKKKKKKKKW",
                            "...OGKKKKKKKKKKKKKKKKKW",
                            "....OGKKKKKKKKKKKKKKKGW",
                            "....WRGGROOOOOGGKKKKGW",
                            "...WKKGWW.....OOOORGO",
                            "...WWWWW.........WKRGW",
                            "..................WWWW",
                        }
                    },
                },
            },
            new PokemonSprite
            {
                Key = "charmander",
                NameKo = "파이리",
                ScaleFactor = 0.3333333333333333,
                FacesRight = false,
                Hops = false,
                Bounce = true,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#fa983c" },
                    { 'Y', "#d9502d" },
                    { 'O', "#cc5840" },
                    { 'W', "#e5a35b" },
                    { 'R', "#fdd37a" },
                    { 'B', "#2a1615" },
                    { 'G', "#8b2f0e" },
                    { 'T', "#3b302f" },
                    { 'D', "#924628" },
                    { 'E', "#4d4544" },
                    { 'C', "#f9c158" },
                    { 'S', "#f0ece9" },
                    { 'L', "#22417d" },
                    { 'M', "#4895bd" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".",
                        ".",
                        ".........SOODDD",
                        "........OOKKKKKGG",
                        ".......OCKKKKKKKKT",
                        "......OCCCKKKKKKKT",
                        "......OCCCKKKKKKKWT",
                        ".....OKKCKKKKKYKKKB",
                        ".....OKKKKKKKYKKWKOT",
                        ".....LOKKKKKKOWLLOOB",
                        ".....MOKKKKKKWLLLGOB",
                        "......KKKKKKKWSBMGOB",
                        ".....TKKKKKKKWSLMGOB.............O",
                        "....GEKKKKKKKKGMMOOB.............YC",
                        "....GCCCKKKKKKKOOYOB............SYC",
                        "....DCCKKYKKKKYYGYOT............YKC",
                        ".....DWKKKKKKODGYOB......GD.....YKKK",
                        ".....TBWKKKGGTSOYOB..DGGGOT.....YKKKY",
                        "..DD...BBBBYYGOOYYGDDKKKKOT.....YKYKK",
                        "..BOGGGBOOGGGOOBOYKKKKKKYOOT...YYYYKKO",
                        "..BOKKKOBBWWOBBOYYYKKYYYOBT....YYKYYKKO",
                        ".TOOYKKYOOBBBOOYYYYYYYOOB......YKKYKKKY",
                        "..EEOOYYYYOOOOOYYYYYYOEE.......YKKKKKKY",
                        "....TTOOYYGOWWWOYYYGGE.........YKKKKKKY",
                        "......TTOYGWWWWWOYKKB...........OKYKKYO",
                        "........TGORRRRRWKKKB............YYGYO",
                        ".........DWRRRRRRKKKOE...........SGGY",
                        ".........DRRRRRRRKKKKE............GCB",
                        ".........DRRRRRRRKKKKWT..........SGWB",
                        "........GWRRRRRRRWKKKKT..........DKKB",
                        "........GRRRRRRRRRKKKKT.......SDDKKOE",
                        ".......DGRRRRRRRRRYKKKWT....GGGKKKOB",
                        "......GKYWRRRRRRRWYKKKKOBGGGKKKKKOWT",
                        "......GKKOWRRRRWWOKKKKKKBOYYYKKYWWB",
                        ".....TKKKDWWWWWWWYKKKKKKOBYYYYOWWE",
                        ".....TKKKWBWWWWWWOKKKKKYOBOYYWWWB",
                        ".....TWKKKOBWWWWWGYKKKYYOBWWWWBT",
                        "......BWKYYOBBWWWGYYYYYYOBWWDD",
                        ".......BOYYYOOEEEEDYYYYOBDDO",
                        ".......BOYYOBE.....GYYYOB",
                        "......TOOYYOT......GKKKOB",
                        ".....ESDSOOT.......DOWKWOE",
                        "......ETTTE.........TSDSGSE",
                        ".....................TBBBE",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        ".........SOODDD",
                        "........OOKKKKKGG",
                        ".......OCKKKKKKKKT",
                        "......OCCCKKKKKKKT",
                        "......OCCCKKKKKKKWT",
                        ".....OKKCKKKKKYKKKB",
                        ".....OKKKKKKKYKKWKOT",
                        ".....LOKKKKKKOWLLOOB",
                        ".....MOKKKKKKWLLLGOB",
                        "......KKKKKKKWSBMGOB",
                        ".....TKKKKKKKWSLMGOB.............O",
                        "....GEKKKKKKKKGMMOOB.............YC",
                        "....GCCCKKKKKKKOOYOB............SYC",
                        "....DCCKKYKKKKYYGYOT............YKC",
                        ".....DWKKKKKKODGYOB......GD.....YKKK",
                        ".....TBWKKKGGTSOYOB..DGGGOT.....YKKKY",
                        "..DD...BBBBYYGOOYYGDDKKKKOT.....YKYKK",
                        "..BOGGGBOOGGGOOBOYKKKKKKYOOT...YYYYKKO",
                        "..BOKKKOBBWWOBBOYYYKKYYYOBT....YYKYYKKO",
                        ".TOOYKKYOOBBBOOYYYYYYYOOB......YKKYKKKY",
                        "..EEOOYYYYOOOOOYYYYYYOEE.......YKKKKKKY",
                        "....TTOOYYGOWWWOYYYGGE.........YKKKKKKY",
                        "......TTOYGWWWWWOYKKB...........OKYKKYO",
                        "........TGORRRRRWKKKB............YYGYO",
                        ".........DWRRRRRRKKKOE...........SGGY",
                        ".........DRRRRRRRKKKKE............GCB",
                        ".........DRRRRRRRKKKKWT..........SGWB",
                        "........GWRRRRRRRWKKKKT..........DKKB",
                        "........GRRRRRRRRRKKKKT.......SDDKKOE",
                        ".......DGRRRRRRRRRYKKKWT....GGGKKKOB",
                        "......GKYWRRRRRRRWYKKKKOBGGGKKKKKOWT",
                        "......GKKOWRRRRWWOKKKKKKBOYYYKKYWWB",
                        ".....TKKKDWWWWWWWYKKKKKKOBYYYYOWWE",
                        ".....TKKKWBWWWWWWOKKKKKYOBOYYWWWB",
                        ".....TWKKKOBWWWWWGYKKKYYOBWWWWBT",
                        "......BWKBOYYOBEWGYYYYYYOBWWDD",
                        ".......BTOOYYOTEEEDYGYYYOBDO",
                        ".......ESDSOOT......GKKKOB",
                        "........ETTTE.......DOWKWOE",
                        ".....................TSDSGSE",
                        "......................TBBBE",
                        ".",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        ".........SOODDD",
                        "........OOKKKKKGG",
                        ".......OCKKKKKKKKT",
                        "......OCCCKKKKKKKT",
                        "......OCCCKKKKKKKWT",
                        ".....OKKCKKKKKYKKKB",
                        ".....OKKKKKKKYKKWKOT",
                        ".....LOKKKKKKOWLLOOB",
                        ".....MOKKKKKKWLLLGOB",
                        "......KKKKKKKWSBMGOB",
                        ".....TKKKKKKKWSLMGOB.............O",
                        "....GEKKKKKKKKGMMOOB.............YC",
                        "....GCCCKKKKKKKOOYOB............SYC",
                        "....DCCKKYKKKKYYGYOT............YKC",
                        ".....DWKKKKKKODGYOB......GD.....YKKK",
                        ".....TBWKKKGGTSOYOB..DGGGOT.....YKKKY",
                        "..DD...BBBBYYGOOYYGDDKKKKOT.....YKYKK",
                        "..BOGGGBOOGGGOOBOYKKKKKKYOOT...YYYYKKO",
                        "..BOKKKOBBWWOBBOYYYKKYYYOBT....YYKYYKKO",
                        ".TOOYKKYOOBBBOOYYYYYYYOOB......YKKYKKKY",
                        "..EEOOYYYYOOOOOYYYYYYOEE.......YKKKKKKY",
                        "....TTOOYYGOWWWOYYYGGE.........YKKKKKKY",
                        "......TTOYGWWWWWOYKKB...........OKYKKYO",
                        "........TGORRRRRWKKKB............YYGYO",
                        ".........DWRRRRRRKKKOE...........SGGY",
                        ".........DRRRRRRRKKKKE............GCB",
                        ".........DRRRRRRRKKKKWT..........SGWB",
                        "........GWRRRRRRRWKKKKT..........DKKB",
                        "........GRRRRRRRRRKKKKT.......SDDKKOE",
                        ".......DGRRRRRRRRRYKKKWT....GGGKKKOB",
                        "......GKYWRRRRRRRWYKKKKOBGGGKKKKKOWT",
                        "......GKKOWRRRRWWOKKKKKKBOYYYKKYWWB",
                        ".....TKKKDWWWWWWWYKKKKKKOBYYYYOWWE",
                        ".....TKKKWBWWWWWWOKKKKKYOBOYYWWWB",
                        ".....TWKKKOBWWWWWGYKKKYYOBWWWWBT",
                        "......BWKYYOBBWWWGYYYYYYOBWWDD",
                        ".......BOYYYOOEEEEDYYYYOBDDO",
                        ".......BOYYOBE.....GYYYOB",
                        "......TOOYYOT......GKKKOB",
                        ".....ESDSOOT.......DOWKWOE",
                        "......ETTTE.........TSDSGSE",
                        ".....................TBBBE",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        ".........SOODDD",
                        "........OOKKKKKGG",
                        ".......OCKKKKKKKKT",
                        "......OCCCKKKKKKKT",
                        "......OCCCKKKKKKKWT",
                        ".....OKKCKKKKKYKKKB",
                        ".....OKKKKKKKYKKWKOT",
                        ".....LOKKKKKKOWLLOOB",
                        ".....MOKKKKKKWLLLGOB",
                        "......KKKKKKKWSBMGOB",
                        ".....TKKKKKKKWSLMGOB.............O",
                        "....GEKKKKKKKKGMMOOB.............YC",
                        "....GCCCKKKKKKKOOYOB............SYC",
                        "....DCCKKYKKKKYYGYOT............YKC",
                        ".....DWKKKKKKODGYOB......GD.....YKKK",
                        ".....TBWKKKGGTSOYOB..DGGGOT.....YKKKY",
                        "..DD...BBBBYYGOOYYGDDKKKKOT.....YKYKK",
                        "..BOGGGBOOGGGOOBOYKKKKKKYOOT...YYYYKKO",
                        "..BOKKKOBBWWOBBOYYYKKYYYOBT....YYKYYKKO",
                        ".TOOYKKYOOBBBOOYYYYYYYOOB......YKKYKKKY",
                        "..EEOOYYYYOOOOOYYYYYYOEE.......YKKKKKKY",
                        "....TTOOYYGOWWWOYYYGGE.........YKKKKKKY",
                        "......TTOYGWWWWWOYKKB...........OKYKKYO",
                        "........TGORRRRRWKKKB............YYGYO",
                        ".........DWRRRRRRKKKOE...........SGGY",
                        ".........DRRRRRRRKKKKE............GCB",
                        ".........DRRRRRRRKKKKWT..........SGWB",
                        "........GWRRRRRRRWKKKKT..........DKKB",
                        "........GRRRRRRRRRKKKKT.......SDDKKOE",
                        ".......DGRRRRRRRRRYKKKWT....GGGKKKOB",
                        "......GKYWRRRRRRRWYKKKKOBGGGKKKKKOWT",
                        "......GKKOWRRRRWWOKKKKKKBOYYYKKYWWB",
                        ".....TKKKDWWWWWWWYKKKKKKOBYYYYOWWE",
                        ".....TKKKWBWWWWWWOKKKKKYOBOYYWWWB",
                        ".....TWKKKOBWWWWWGYKKKYYOBWWWWBT",
                        "......BWKYYOBBWWWGYYYGYYYOBWDD",
                        ".......BBOYYOBEEEEDYYGKKKOBO",
                        ".......TOOYYOT.......DOWKWOE",
                        "......ESDSOOT.........TSDSGSE",
                        ".......ETTTE...........TBBBE",
                        ".",
                        ".",
                    },
                },
                Poses = new Dictionary<string, string[]>
                {
                    { "blink", new string[]
                        {
                            ".",
                            ".",
                            ".........SOODDD",
                            "........OOKKKKKGG",
                            ".......OCKKKKKKKKT",
                            "......OCCCKKKKKKKT",
                            "......OCCCKKKKKKKWT",
                            ".....OKKCKKKKKYKKKB",
                            ".....OKKKKKKKYKKWKOT",
                            ".....LOKKKKKKKKKKKKB",
                            ".....MOKKKKKKKKKKKKB",
                            "......KKKKKKKBBBBBBB",
                            ".....TKKKKKKKKKKKKKB.............O",
                            "....GEKKKKKKKKKKKKKB.............YC",
                            "....GCCCKKKKKKKOOYOB............SYC",
                            "....DCCKKYKKKKYYGYOT............YKC",
                            ".....DWKKKKKKODGYOB......GD.....YKKK",
                            ".....TBWKKKGGTSOYOB..DGGGOT.....YKKKY",
                            "..DD...BBBBYYGOOYYGDDKKKKOT.....YKYKK",
                            "..BOGGGBOOGGGOOBOYKKKKKKYOOT...YYYYKKO",
                            "..BOKKKOBBWWOBBOYYYKKYYYOBT....YYKYYKKO",
                            ".TOOYKKYOOBBBOOYYYYYYYOOB......YKKYKKKY",
                            "..EEOOYYYYOOOOOYYYYYYOEE.......YKKKKKKY",
                            "....TTOOYYGOWWWOYYYGGE.........YKKKKKKY",
                            "......TTOYGWWWWWOYKKB...........OKYKKYO",
                            "........TGORRRRRWKKKB............YYGYO",
                            ".........DWRRRRRRKKKOE...........SGGY",
                            ".........DRRRRRRRKKKKE............GCB",
                            ".........DRRRRRRRKKKKWT..........SGWB",
                            "........GWRRRRRRRWKKKKT..........DKKB",
                            "........GRRRRRRRRRKKKKT.......SDDKKOE",
                            ".......DGRRRRRRRRRYKKKWT....GGGKKKOB",
                            "......GKYWRRRRRRRWYKKKKOBGGGKKKKKOWT",
                            "......GKKOWRRRRWWOKKKKKKBOYYYKKYWWB",
                            ".....TKKKDWWWWWWWYKKKKKKOBYYYYOWWE",
                            ".....TKKKWBWWWWWWOKKKKKYOBOYYWWWB",
                            ".....TWKKKOBWWWWWGYKKKYYOBWWWWBT",
                            "......BWKYYOBBWWWGYYYYYYOBWWDD",
                            ".......BOYYYOOEEEEDYYYYOBDDO",
                            ".......BOYYOBE.....GYYYOB",
                            "......TOOYYOT......GKKKOB",
                            ".....ESDSOOT.......DOWKWOE",
                            "......ETTTE.........TSDSGSE",
                            ".....................TBBBE",
                        }
                    },
                    { "squash", new string[]
                        {
                            ".",
                            ".",
                            ".",
                            ".",
                            ".........SOODDD",
                            "........OOKKKKKGG",
                            ".......OCKKKKKKKKT",
                            "......OCCCKKKKKKKT",
                            "......OCCCKKKKKKKWT",
                            ".....OKKCKKKKKYKKKB",
                            ".....OKKKKKKKYKKWKOT",
                            ".....LOKKKKKKOWLLOOB",
                            ".....MOKKKKKKWLLLGOB",
                            "......KKKKKKKWSBMGOB",
                            ".....TKKKKKKKWSLMGOB..............O",
                            "....GEKKKKKKKKGMMOOB..............YC",
                            "....GCCCKKKKKKKOOYOB.............SYC",
                            "....DCCKKYKKKKYYGYOT.............YKC",
                            ".....DWKKKKKKODGYOB.......GD.....YKKK",
                            ".....TBWKKKGGTSOYOB...DGGGOT.....YKKKY",
                            "..DD...BBBBYYGOOYYGDDDKKKKOT.....YKYKK",
                            "..BOGGGBOOGGGOOBOYKKKKKKKYOOT...YYYYKKO",
                            "..BOKKKOBBWWOBBOYYYKKKYYYOBT....YYKYYKKO",
                            "TTOOYKKYOOBBBOOYYYYYYYYOOB......YKKYKKKY",
                            "....TTOOYYGOWWWOYYYGGGE.........YKKKKKKY",
                            "......TTOYGWWWWWOYKKBB...........OKYKKYO",
                            "........TGORRRRRWKKKBB............YYGYO",
                            ".........DWRRRRRRKKKOOE...........SGGY",
                            ".........DRRRRRRRKKKKKE............GCB",
                            ".........DRRRRRRRKKKKKWT..........SGWB",
                            "........GWRRRRRRRWKKKKKT..........DKKB",
                            "........GRRRRRRRRRKKKKKT.......SDDKKOE",
                            ".......DGRRRRRRRRRYKKKKWT....GGGKKKOB",
                            "......GKYWRRRRRRRWYKKKKKOBGGGKKKKKOWT",
                            "......GKKOWRRRRWWOKKKKKKKBOYYYKKYWWB",
                            ".....TKKKDWWWWWWWYKKKKKKKOBYYYYOWWE",
                            ".....TKKKWBWWWWWWOKKKKKKYOBOYYWWWB",
                            ".....TWKKKOBWWWWWGYKKKKYYOBWWWWBT",
                            "......BWKYYOBBWWWGYYYYYYYOBWWDD",
                            ".......BOYYYOOEEEEDYYYYYOBDDO",
                            ".......BOYYOBE.....GYYYYOB",
                            "......TOOYYOT......GKKKKOB",
                            ".....ESDSOOT.......DOOWKWOE",
                            "......ETTTE.........TTSDSGSE",
                        }
                    },
                    { "stretch", new string[]
                        {
                            "..........SOODDD",
                            "..........SOODDD",
                            ".........OOKKKKKGG",
                            "........OCKKKKKKKKT",
                            ".......OCCCKKKKKKKT",
                            ".......OCCCKKKKKKKWT",
                            "......OKKCKKKKKYKKKB",
                            "......OKKKKKKKYKKWKO",
                            "......LOKKKKKKOWLLOO",
                            "......MOKKKKKKWLLLGO",
                            ".......KKKKKKKWSBMGO",
                            "......TKKKKKKKWSLMGO.............O",
                            ".....GEKKKKKKKKGMMOO.............YC",
                            ".....GCCCKKKKKKKOOYO............SYC",
                            ".....DCCKKYKKKKYYGYO............YKC",
                            "......DWKKKKKKODGYOB.....GD.....YKKK",
                            "......TBWKKKGGTSOYOB.DGGGOT.....YKKKY",
                            "...DD...BBBBYYGOOYYGDKKKKOT.....YKYKK",
                            "...BOGGGBOOGGGOOBOYKKKKKYOOT...YYYYKKO",
                            "...BOKKKOBBWWOBBOYYYKYYYOBT....YYKYYKK",
                            "..TOOYKKYOOBBBOOYYYYYYOOB......YKKYKKK",
                            "...EEOOYYYYOOOOOYYYYYOEE.......YKKKKKK",
                            ".....TTOOYYGOWWWOYYYGE.........YKKKKKK",
                            ".....TTOOYYGOWWWOYYYGE.........YKKKKKK",
                            ".......TTOYGWWWWWOYKB...........OKYKKY",
                            ".........TGORRRRRWKKB............YYGYO",
                            "..........DWRRRRRRKKOE...........SGGY",
                            "..........DRRRRRRRKKKE............GCB",
                            "..........DRRRRRRRKKKWT..........SGWB",
                            ".........GWRRRRRRRWKKKT..........DKKB",
                            ".........GRRRRRRRRRKKKT.......SDDKKOE",
                            "........DGRRRRRRRRRYKKWT....GGGKKKOB",
                            ".......GKYWRRRRRRRWYKKKOBGGGKKKKKOWT",
                            ".......GKKOWRRRRWWOKKKKKBOYYYKKYWWB",
                            "......TKKKDWWWWWWWYKKKKKOBYYYYOWWE",
                            "......TKKKWBWWWWWWOKKKKYOBOYYWWWB",
                            "......TWKKKOBWWWWWGYKKYYOBWWWWBT",
                            ".......BWKYYOBBWWWGYYYYYOBWWDD",
                            "........BOYYYOOEEEEDYYYOBDDO",
                            "........BOYYOBE.....YYYOB",
                            ".......TOOYYOT......KKKOB",
                            "......ESDSOOT.......OWKWOE",
                            ".......ETTTE........TSDSGSE",
                            ".....................TBBBE",
                        }
                    },
                },
            },
            new PokemonSprite
            {
                Key = "bulbasaur",
                NameKo = "이상해씨",
                ScaleFactor = 0.3333333333333333,
                FacesRight = false,
                Hops = false,
                Bounce = true,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#599cb4" },
                    { 'Y', "#c8ecea" },
                    { 'O', "#a3d7df" },
                    { 'W', "#849b48" },
                    { 'R', "#2f606b" },
                    { 'B', "#457e90" },
                    { 'G', "#050707" },
                    { 'T', "#eaf9a8" },
                    { 'D', "#161819" },
                    { 'E', "#c3d476" },
                    { 'C', "#a33029" },
                    { 'S', "#57623b" },
                    { 'L', "#29525a" },
                    { 'M', "#da8785" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".",
                        ".",
                        "............................S",
                        "..........................SSEGG",
                        "..................WWWWSSSSEWWSWG",
                        "................WWTTTTTTEEEWESWG",
                        "...............WTTTTTTTTTWWEEWSG",
                        "....RLY.......WTTTTTLGWWWTEEEWSG",
                        "...KYYRLYBRRRRRRRLLLYOGTTTTEEESWGY",
                        "...KYYYRROYYYYOOOLYYYOGTTTTEEESWWG",
                        "...KOKYYYYYBBBYOOYYYOODTTTTEEEWSWG",
                        "...KBYYYYYBBBBYYOOOOOOKGTTTEEEWSWWG",
                        "...BYYYYYBBBBYYYOOOOOOKGTTEEEEWWSWG",
                        "...BYYYYYBBBYYYYOKKOOOKDTEEEEWWWSWWG",
                        "..BROOYYYYYYYYOYBYYROKKKGEEEWWWWSWWG",
                        "..RCKYOYYYBBYOYBCCYYRKKKGLEWWWWWSWWG",
                        "..RCKYOYYBBBYOYBMCYYRKKKGRWWWWWSWWWG",
                        ".BYMYKYYYBBYYYKCYCCYYKKKRKRWWWWSWWWD",
                        ".BYCYKOYYYYYYOKCYMMYYKKKBKKRWWSWWWG",
                        ".BOCCKOOOOOOOOKCCMMYKKKKKKKKRRWWWWD",
                        ".RGOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
                        ".BBDROOBOBOOOOOOOBRGGKKBKKKRRKKRG",
                        "..RBYCCOOOOOBLGGGYBKKKKRKKKRRRKKR",
                        "...BBBBCCCCCCCCCCBKKKKRKKKKKRRKKKR",
                        "....DDBBBCCMMMMBKKKKDGKKKKKBKKKKKRY",
                        "......DGBKKKKKKKKDGGKKKBKKLKKKRKKKG",
                        "......RKDDGGGGGGGKKKKKKRKKDKKRRRKKG",
                        "......KOOOKRKKKKKKROOKKKRGKKKRRRKKG",
                        ".......BKOOKRDBKKRKKOOKKRGKKKRRRKKD",
                        ".......BKOOKKKGDDRKKKOKKRDKKKKRKKG",
                        ".......KOOOOKKG..KOKKOKKR.DBKBKBKD",
                        ".......YBOKOKKD..KOOOOKG..BYLYLYB",
                        ".......RYRYRYD...BOKOKKD...DDDDD",
                        "........DDDDD...RYRYRKD",
                        ".................DDDDD",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        "............................S",
                        "..........................SSEGG",
                        "..................WWWWSSSSEWWSWG",
                        "................WWTTTTTTEEEWESWG",
                        "...............WTTTTTTTTTWWEEWSG",
                        "....RLY.......WTTTTTLGWWWTEEEWSG",
                        "...KYYRLYBRRRRRRRLLLYOGTTTTEEESWGY",
                        "...KYYYRROYYYYOOOLYYYOGTTTTEEESWWG",
                        "...KOKYYYYYBBBYOOYYYOODTTTTEEEWSWG",
                        "...KBYYYYYBBBBYYOOOOOOKGTTTEEEWSWWG",
                        "...BYYYYYBBBBYYYOOOOOOKGTTEEEEWWSWG",
                        "...BYYYYYBBBYYYYOKKOOOKDTEEEEWWWSWWG",
                        "..BROOYYYYYYYYOYBYYROKKKGEEEWWWWSWWG",
                        "..RCKYOYYYBBYOYBCCYYRKKKGLEWWWWWSWWG",
                        "..RCKYOYYBBBYOYBMCYYRKKKGRWWWWWSWWWG",
                        ".BYMYKYYYBBYYYKCYCCYYKKKRKRWWWWSWWWD",
                        ".BYCYKOYYYYYYOKCYMMYYKKKBKKRWWSWWWG",
                        ".BOCCKOOOOOOOOKCCMMYKKKKKKKKRRWWWWD",
                        ".RGOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
                        ".BBDROOBOBOOOOOOOBRGGKKBKKKRRKKRG",
                        "..RBYCCOOOOOBLGGGYBKKKKRKKKRRRKKR",
                        "...BBBBCCCCCCCCCCBKKKKRKKKKKRRKKKR",
                        "....DDBBBCCMMMMBKKKKDGKKKKKBKKKKKRY",
                        "......DGBKKKKKKKKDGGKKKBKKLKKKRKKKG",
                        "......RKDDGGGGGGGKKKKKKRKKDKKRRRKKG",
                        "......KOOOKRKKKKKKROOKKKRGKKKRRRKKG",
                        ".......BKOOOOKKGKRKKOOKKRGKKKRRRKKD",
                        ".......BYBOKOKKDDRKOKKOKKRDBKBKBKD",
                        "........RYRYRYD...KOOOOKG.BYLYLYB",
                        ".........DDDDD....BOKOKKD..DDDDD",
                        ".................RYRYRKD",
                        "..................DDDDD",
                        ".",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        "............................S",
                        "..........................SSEGG",
                        "..................WWWWSSSSEWWSWG",
                        "................WWTTTTTTEEEWESWG",
                        "...............WTTTTTTTTTWWEEWSG",
                        "....RLY.......WTTTTTLGWWWTEEEWSG",
                        "...KYYRLYBRRRRRRRLLLYOGTTTTEEESWGY",
                        "...KYYYRROYYYYOOOLYYYOGTTTTEEESWWG",
                        "...KOKYYYYYBBBYOOYYYOODTTTTEEEWSWG",
                        "...KBYYYYYBBBBYYOOOOOOKGTTTEEEWSWWG",
                        "...BYYYYYBBBBYYYOOOOOOKGTTEEEEWWSWG",
                        "...BYYYYYBBBYYYYOKKOOOKDTEEEEWWWSWWG",
                        "..BROOYYYYYYYYOYBYYROKKKGEEEWWWWSWWG",
                        "..RCKYOYYYBBYOYBCCYYRKKKGLEWWWWWSWWG",
                        "..RCKYOYYBBBYOYBMCYYRKKKGRWWWWWSWWWG",
                        ".BYMYKYYYBBYYYKCYCCYYKKKRKRWWWWSWWWD",
                        ".BYCYKOYYYYYYOKCYMMYYKKKBKKRWWSWWWG",
                        ".BOCCKOOOOOOOOKCCMMYKKKKKKKKRRWWWWD",
                        ".RGOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
                        ".BBDROOBOBOOOOOOOBRGGKKBKKKRRKKRG",
                        "..RBYCCOOOOOBLGGGYBKKKKRKKKRRRKKR",
                        "...BBBBCCCCCCCCCCBKKKKRKKKKKRRKKKR",
                        "....DDBBBCCMMMMBKKKKDGKKKKKBKKKKKRY",
                        "......DGBKKKKKKKKDGGKKKBKKLKKKRKKKG",
                        "......RKDDGGGGGGGKKKKKKRKKDKKRRRKKG",
                        "......KOOOKRKKKKKKROOKKKRGKKKRRRKKG",
                        ".......BKOOKRDBKKRKKOOKKRGKKKRRRKKD",
                        ".......BKOOKKKGDDRKKKOKKRDKKKKRKKG",
                        ".......KOOOOKKG..KOKKOKKR.DBKBKBKD",
                        ".......YBOKOKKD..KOOOOKG..BYLYLYB",
                        ".......RYRYRYD...BOKOKKD...DDDDD",
                        "........DDDDD...RYRYRKD",
                        ".................DDDDD",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        "............................S",
                        "..........................SSEGG",
                        "..................WWWWSSSSEWWSWG",
                        "................WWTTTTTTEEEWESWG",
                        "...............WTTTTTTTTTWWEEWSG",
                        "....RLY.......WTTTTTLGWWWTEEEWSG",
                        "...KYYRLYBRRRRRRRLLLYOGTTTTEEESWGY",
                        "...KYYYRROYYYYOOOLYYYOGTTTTEEESWWG",
                        "...KOKYYYYYBBBYOOYYYOODTTTTEEEWSWG",
                        "...KBYYYYYBBBBYYOOOOOOKGTTTEEEWSWWG",
                        "...BYYYYYBBBBYYYOOOOOOKGTTEEEEWWSWG",
                        "...BYYYYYBBBYYYYOKKOOOKDTEEEEWWWSWWG",
                        "..BROOYYYYYYYYOYBYYROKKKGEEEWWWWSWWG",
                        "..RCKYOYYYBBYOYBCCYYRKKKGLEWWWWWSWWG",
                        "..RCKYOYYBBBYOYBMCYYRKKKGRWWWWWSWWWG",
                        ".BYMYKYYYBBYYYKCYCCYYKKKRKRWWWWSWWWD",
                        ".BYCYKOYYYYYYOKCYMMYYKKKBKKRWWSWWWG",
                        ".BOCCKOOOOOOOOKCCMMYKKKKKKKKRRWWWWD",
                        ".RGOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
                        ".BBDROOBOBOOOOOOOBRGGKKBKKKRRKKRG",
                        "..RBYCCOOOOOBLGGGYBKKKKRKKKRRRKKR",
                        "...BBBBCCCCCCCCCCBKKKKRKKKKKRRKKKR",
                        "....DDBBBCCMMMMBKKKKDGKKKKKBKKKKKRY",
                        "......DGBKKKKKKKKDGGKKKBKKLKKKRKKKG",
                        "......RKDDGGGGGGGKKKKKKRKKDKKRRRKKG",
                        "......KOOOKRKKKKKKROOKKKRGKKKRRRKKG",
                        ".......BKOOKRDBKKRKOKKOKKRKDBKBKBKD",
                        ".......BKOOOOKKGDRKOOOOKGDKBYLYLYB",
                        "........YBOKOKKD..BOKOKKD...DDDDD",
                        "........RYRYRYD..RYRYRKD",
                        ".........DDDDD....DDDDD",
                        ".",
                        ".",
                    },
                },
                Poses = new Dictionary<string, string[]>
                {
                    { "blink", new string[]
                        {
                            ".",
                            ".",
                            "............................S",
                            "..........................SSEGG",
                            "..................WWWWSSSSEWWSWG",
                            "................WWTTTTTTEEEWESWG",
                            "...............WTTTTTTTTTWWEEWSG",
                            "....RLY.......WTTTTTLGWWWTEEEWSG",
                            "...KYYRLYBRRRRRRRLLLYOGTTTTEEESWGY",
                            "...KYYYRROYYYYOOOLYYYOGTTTTEEESWWG",
                            "...KOKYYYYYBBBYOOYYYOODTTTTEEEWSWG",
                            "...KBYYYYYBBBBYYOOOOOOKGTTTEEEWSWWG",
                            "...BYYYYYBBBBYYYOOOOOOKGTTEEEEWWSWG",
                            "...BYYYYYBBBYYYYOKKOOOKDTEEEEWWWSWWG",
                            "..BROOYYYYYYYYOYBYYROKKKGEEEWWWWSWWG",
                            "..RCOOOOOYBBYYYYYYYYRKKKGLEWWWWWSWWG",
                            "..RCOOOOOBBBYYYYYYYYRKKKGRWWWWWSWWWG",
                            ".BYMCCCCCBBYYCCCCCCYYKKKRKRWWWWSWWWD",
                            ".BYCOOOOOYYYYYYYYYYYYKKKBKKRWWSWWWG",
                            ".BOCOOOOOOOOOYYYYYYYKKKKKKKKRRWWWWD",
                            ".RGOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
                            ".BBDROOBOBOOOOOOOBRGGKKBKKKRRKKRG",
                            "..RBYCCOOOOOBLGGGYBKKKKRKKKRRRKKR",
                            "...BBBBCCCCCCCCCCBKKKKRKKKKKRRKKKR",
                            "....DDBBBCCMMMMBKKKKDGKKKKKBKKKKKRY",
                            "......DGBKKKKKKKKDGGKKKBKKLKKKRKKKG",
                            "......RKDDGGGGGGGKKKKKKRKKDKKRRRKKG",
                            "......KOOOKRKKKKKKROOKKKRGKKKRRRKKG",
                            ".......BKOOKRDBKKRKKOOKKRGKKKRRRKKD",
                            ".......BKOOKKKGDDRKKKOKKRDKKKKRKKG",
                            ".......KOOOOKKG..KOKKOKKR.DBKBKBKD",
                            ".......YBOKOKKD..KOOOOKG..BYLYLYB",
                            ".......RYRYRYD...BOKOKKD...DDDDD",
                            "........DDDDD...RYRYRKD",
                            ".................DDDDD",
                        }
                    },
                    { "squash", new string[]
                        {
                            ".",
                            ".",
                            ".",
                            ".",
                            ".............................S",
                            "...........................SSEGG",
                            "..................WWWWWSSSSEWWSWG",
                            "................WWTTTTTTTEEEWESWG",
                            "...............WTTTTTTTTTTWWEEWSG",
                            "....RLY.......WTTTTTTLGWWWTEEEWSG",
                            "...KYYRLYBRRRRRRRLLLLYOGTTTTEEESWGY",
                            "...KYYYRROYYYYOOOLYYYYOGTTTTEEESWWG",
                            "...KOKYYYYYBBBYOOYYYYOODTTTTEEEWSWG",
                            "...KBYYYYYBBBBYYOOOOOOOKGTTTEEEWSWWG",
                            "...BYYYYYBBBBYYYOOOOOOOKGTTEEEEWWSWG",
                            "...BYYYYYBBBYYYYOKKKOOOKDTEEEEWWWSWWG",
                            "..BROOYYYYYYYYOYBYYYROKKKGEEEWWWWSWWG",
                            "..RCKYOYYYBBYOYBCCYYYRKKKGLEWWWWWSWWG",
                            "..RCKYOYYBBBYOYBMCYYYRKKKGRWWWWWSWWWG",
                            "BBYMYKYYYBBYYYKCYCCCYYKKKRKRWWWWSWWWD",
                            "BBOCCKOOOOOOOOKCCMMMYKKKKKKKKRRWWWWD",
                            "RRGOOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
                            "BBBDROOBOBOOOOOOOBRRGGKKBKKKRRKKRG",
                            "..RBYCCOOOOOBLGGGYBBKKKKRKKKRRRKKR",
                            "...BBBBCCCCCCCCCCBKKKKKRKKKKKRRKKKR",
                            "....DDBBBCCMMMMBKKKKKDGKKKKKBKKKKKRY",
                            "......DGBKKKKKKKKDGGGKKKBKKLKKKRKKKG",
                            "......RKDDGGGGGGGKKKKKKKRKKDKKRRRKKG",
                            "......KOOOKRKKKKKKRROOKKKRGKKKRRRKKG",
                            ".......BKOOKRDBKKRKKKOOKKRGKKKRRRKKD",
                            ".......BKOOKKKGDDRKKKKOKKRDKKKKRKKG",
                            ".......KOOOOKKG..KOOKKOKKR.DBKBKBKD",
                            ".......YBOKOKKD..KOOOOOKG..BYLYLYB",
                            ".......RYRYRYD...BOOKOKKD...DDDDD",
                            "........DDDDD...RYRRYRKD",
                        }
                    },
                    { "stretch", new string[]
                        {
                            "............................S",
                            "............................S",
                            "..........................SSEGG",
                            "...................WWWSSSSEWWSWG",
                            ".................WWTTTTTEEEWESWG",
                            "................WTTTTTTTTWWEEWSG",
                            ".....RLY.......WTTTTLGWWWTEEEWSG",
                            "....KYYRLYBRRRRRRRLLYOGTTTTEEESWGY",
                            "....KYYYRROYYYYOOOLYYOGTTTTEEESWWG",
                            "....KOKYYYYYBBBYOOYYOODTTTTEEEWSWG",
                            "....KBYYYYYBBBBYYOOOOOKGTTTEEEWSWWG",
                            "....BYYYYYBBBBYYYOOOOOKGTTEEEEWWSWG",
                            "....BYYYYYBBBYYYYOKOOOKDTEEEEWWWSWW",
                            "...BROOYYYYYYYYOYBYROKKKGEEEWWWWSWW",
                            "...RCKYOYYYBBYOYBCCYRKKKGLEWWWWWSWW",
                            "...RCKYOYYBBBYOYBMCYRKKKGRWWWWWSWWW",
                            "..BYMYKYYYBBYYYKCYCYYKKKRKRWWWWSWWW",
                            "..BYCYKOYYYYYYOKCYMYYKKKBKKRWWSWWWG",
                            "..BYCYKOYYYYYYOKCYMYYKKKBKKRWWSWWWG",
                            "..BOCCKOOOOOOOOKCCMYKKKKKKKKRRWWWWD",
                            "..RGOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
                            "..BBDROOBOBOOOOOOOBGGKKBKKKRRKKRG",
                            "...RBYCCOOOOOBLGGGYKKKKRKKKRRRKKR",
                            "....BBBBCCCCCCCCCCBKKKRKKKKKRRKKKR",
                            ".....DDBBBCCMMMMBKKKDGKKKKKBKKKKKRY",
                            ".......DGBKKKKKKKKDGKKKBKKLKKKRKKKG",
                            ".......RKDDGGGGGGGKKKKKRKKDKKRRRKKG",
                            ".......KOOOKRKKKKKKOOKKKRGKKKRRRKKG",
                            "........BKOOKRDBKKRKOOKKRGKKKRRRKKD",
                            "........BKOOKKKGDDRKKOKKRDKKKKRKKG",
                            "........KOOOOKKG..KKKOKKR.DBKBKBKD",
                            "........YBOKOKKD..KOOOKG..BYLYLYB",
                            "........RYRYRYD...BKOKKD...DDDDD",
                            ".........DDDDD...RYYRKD",
                            "..................DDDD",
                        }
                    },
                },
            },
            new PokemonSprite
            {
                Key = "squirtle",
                NameKo = "꼬부기",
                ScaleFactor = 0.3333333333333333,
                FacesRight = false,
                Hops = false,
                Bounce = true,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#93d3ca" },
                    { 'Y', "#60aa9b" },
                    { 'O', "#141c19" },
                    { 'W', "#d8d6d4" },
                    { 'R', "#fcdc88" },
                    { 'B', "#457363" },
                    { 'G', "#c67f31" },
                    { 'T', "#e3ab5b" },
                    { 'D', "#e8efed" },
                    { 'E', "#589082" },
                    { 'C', "#682e0c" },
                    { 'S', "#b3f3eb" },
                    { 'L', "#b4690f" },
                    { 'M', "#813e18" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".",
                        ".",
                        "............YYYYBB",
                        ".........DYYSSSSKKBBD",
                        "........DYSSSSKKKKKKB",
                        ".......DESSSSKKKKKKKKBW",
                        "......DBKSSSKKKKKKKKKKB",
                        "......WBKKKKKKKYKKKKKKED",
                        "......BYKKKKKKYKYYYKKKYBD",
                        "......BMKKKKKKKEOKWYKYYOW",
                        "......EDYKKKKKKOOOWBYYYOW",
                        "......BCYKKKKKKOOCDBYYYOW",
                        "......BOKKKKKKKDOCDBYYYOW",
                        "....DBSSKKKKKKKCOCDYYYYOW",
                        "....WOSKYKYKKKKKKYYYYYYOW",
                        "......OBKKKKKKKKYYBYYYODDYBBB",
                        "..Y.Y.WOOKKYBBBBBCCYYYBDYKKYYOW",
                        "..BKYBOOEOOCGGGGCCYYYOEKKKBYO",
                        ".YKKKKYYOYYCCCCCYYYBOBKKKBBYO",
                        ".BKKKKKKKOBYYYYYYOOTWYKKKYYOW",
                        "..BYKKKKKYYBOOOOOTTTBKKKYYYOW",
                        "..DBYYYYYYGTTTTTGGGBYKKYYYO",
                        "....BBYYYGTGTGGTRRTBYYYYYOC.....EBBBD",
                        "....DDOOOGRTGTRRRRRGBYYYOLLMD.EEKKKYED",
                        "........GRRRTRRRRRRGTOOOWLLCWBYKKKKKYBD",
                        "........GRRRTRRRRRTTTTCWWLLCBYKKKKKKKBD",
                        "........GRRRTRRRRRGRTTCWWLLOEYYKKBBKKYOW",
                        "........GGRRGRRRRGTRTTLWWLCCEYYYEKKEKYOW",
                        "........GRTGGGTTGGRRRTGLWTLCEYYBYKKKYYOW",
                        "........GRRRGRRRTTGRRTGCWWGOEYYOEYYYYOW",
                        "......DYGRRRTRRRRRTGTYYBBWGOEYYOEYYYYOW",
                        "......YKKGRRTRRRRRTGYKKKYBWOEYYEOEYYOW",
                        "....DYKKKGGGGGTTTTTYKKKKKYBYYYYYYOOOW",
                        "....DYKKKKGTTTTGGGGBKKKKKYOYYYYOOOWW",
                        "....DBKKKKYMTTTTTGGBKKKKKYBOOOOWWW",
                        "....WOYKKYYEMMGGGGGOYKKKYYYOWWW",
                        ".....WOYYYYYEEMMOOOOBYYYYYYOW",
                        "......BYYYYYYOWWWWWWOYYYYYYOW",
                        "....DEKYEKYOOW......WOEYYYYEO",
                        ".....DOOWOOWW........OYYOKEOO",
                        "......WW.WW..........WOOWOOWW",
                        "......................WW.WW",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        "............YYYYBB",
                        ".........DYYSSSSKKBBD",
                        "........DYSSSSKKKKKKB",
                        ".......DESSSSKKKKKKKKBW",
                        "......DBKSSSKKKKKKKKKKB",
                        "......WBKKKKKKKYKKKKKKED",
                        "......BYKKKKKKYKYYYKKKYBD",
                        "......BMKKKKKKKEOKWYKYYOW",
                        "......EDYKKKKKKOOOWBYYYOW",
                        "......BCYKKKKKKOOCDBYYYOW",
                        "......BOKKKKKKKDOCDBYYYOW",
                        "....DBSSKKKKKKKCOCDYYYYOW",
                        "....WOSKYKYKKKKKKYYYYYYOW",
                        "......OBKKKKKKKKYYBYYYODDYBBB",
                        "..Y.Y.WOOKKYBBBBBCCYYYBDYKKYYOW",
                        "..BKYBOOEOOCGGGGCCYYYOEKKKBYO",
                        ".YKKKKYYOYYCCCCCYYYBOBKKKBBYO",
                        ".BKKKKKKKOBYYYYYYOOTWYKKKYYOW",
                        "..BYKKKKKYYBOOOOOTTTBKKKYYYOW",
                        "..DBYYYYYYGTTTTTGGGBYKKYYYO",
                        "....BBYYYGTGTGGTRRTBYYYYYOC.....EBBBD",
                        "....DDOOOGRTGTRRRRRGBYYYOLLMD.EEKKKYED",
                        "........GRRRTRRRRRRGTOOOWLLCWBYKKKKKYBD",
                        "........GRRRTRRRRRTTTTCWWLLCBYKKKKKKKBD",
                        "........GRRRTRRRRRGRTTCWWLLOEYYKKBBKKYOW",
                        "........GGRRGRRRRGTRTTLWWLCCEYYYEKKEKYOW",
                        "........GRTGGGTTGGRRRTGLWTLCEYYBYKKKYYOW",
                        "........GRRRGRRRTTGRRTGCWWGOEYYOEYYYYOW",
                        "......DYGRRRTRRRRRTGTYYBBWGOEYYOEYYYYOW",
                        "......YKKGRRTRRRRRTGYKKKYBWOEYYEOEYYOW",
                        "....DYKKKGGGGGTTTTTYKKKKKYBYYYYYYOOOW",
                        "....DYKKKKGTTTTGGGGBKKKKKYOYYYYOOOWW",
                        "....DBKWOYYYYYEETGGBKKKKKYBOOOOWWW",
                        "....WOYKBYYYYYYOGGGOYKKKYYYOWWW",
                        "......DEKYEKYOOWOOOOBOYYYYYYOW",
                        ".......DOOWOOWWWWWWW.WOEYYYYEO",
                        "......................OYYOKEOO",
                        "......................WOOWOOWW",
                        "......WW.WW",
                        "......................WW.WW",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        "............YYYYBB",
                        ".........DYYSSSSKKBBD",
                        "........DYSSSSKKKKKKB",
                        ".......DESSSSKKKKKKKKBW",
                        "......DBKSSSKKKKKKKKKKB",
                        "......WBKKKKKKKYKKKKKKED",
                        "......BYKKKKKKYKYYYKKKYBD",
                        "......BMKKKKKKKEOKWYKYYOW",
                        "......EDYKKKKKKOOOWBYYYOW",
                        "......BCYKKKKKKOOCDBYYYOW",
                        "......BOKKKKKKKDOCDBYYYOW",
                        "....DBSSKKKKKKKCOCDYYYYOW",
                        "....WOSKYKYKKKKKKYYYYYYOW",
                        "......OBKKKKKKKKYYBYYYODDYBBB",
                        "..Y.Y.WOOKKYBBBBBCCYYYBDYKKYYOW",
                        "..BKYBOOEOOCGGGGCCYYYOEKKKBYO",
                        ".YKKKKYYOYYCCCCCYYYBOBKKKBBYO",
                        ".BKKKKKKKOBYYYYYYOOTWYKKKYYOW",
                        "..BYKKKKKYYBOOOOOTTTBKKKYYYOW",
                        "..DBYYYYYYGTTTTTGGGBYKKYYYO",
                        "....BBYYYGTGTGGTRRTBYYYYYOC.....EBBBD",
                        "....DDOOOGRTGTRRRRRGBYYYOLLMD.EEKKKYED",
                        "........GRRRTRRRRRRGTOOOWLLCWBYKKKKKYBD",
                        "........GRRRTRRRRRTTTTCWWLLCBYKKKKKKKBD",
                        "........GRRRTRRRRRGRTTCWWLLOEYYKKBBKKYOW",
                        "........GGRRGRRRRGTRTTLWWLCCEYYYEKKEKYOW",
                        "........GRTGGGTTGGRRRTGLWTLCEYYBYKKKYYOW",
                        "........GRRRGRRRTTGRRTGCWWGOEYYOEYYYYOW",
                        "......DYGRRRTRRRRRTGTYYBBWGOEYYOEYYYYOW",
                        "......YKKGRRTRRRRRTGYKKKYBWOEYYEOEYYOW",
                        "....DYKKKGGGGGTTTTTYKKKKKYBYYYYYYOOOW",
                        "....DYKKKKGTTTTGGGGBKKKKKYOYYYYOOOWW",
                        "....DBKKKKYMTTTTTGGBKKKKKYBOOOOWWW",
                        "....WOYKKYYEMMGGGGGOYKKKYYYOWWW",
                        ".....WOYYYYYEEMMOOOOBYYYYYYOW",
                        "......BYYYYYYOWWWWWWOYYYYYYOW",
                        "....DEKYEKYOOW......WOEYYYYEO",
                        ".....DOOWOOWW........OYYOKEOO",
                        "......WW.WW..........WOOWOOWW",
                        "......................WW.WW",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        "............YYYYBB",
                        ".........DYYSSSSKKBBD",
                        "........DYSSSSKKKKKKB",
                        ".......DESSSSKKKKKKKKBW",
                        "......DBKSSSKKKKKKKKKKB",
                        "......WBKKKKKKKYKKKKKKED",
                        "......BYKKKKKKYKYYYKKKYBD",
                        "......BMKKKKKKKEOKWYKYYOW",
                        "......EDYKKKKKKOOOWBYYYOW",
                        "......BCYKKKKKKOOCDBYYYOW",
                        "......BOKKKKKKKDOCDBYYYOW",
                        "....DBSSKKKKKKKCOCDYYYYOW",
                        "....WOSKYKYKKKKKKYYYYYYOW",
                        "......OBKKKKKKKKYYBYYYODDYBBB",
                        "..Y.Y.WOOKKYBBBBBCCYYYBDYKKYYOW",
                        "..BKYBOOEOOCGGGGCCYYYOEKKKBYO",
                        ".YKKKKYYOYYCCCCCYYYBOBKKKBBYO",
                        ".BKKKKKKKOBYYYYYYOOTWYKKKYYOW",
                        "..BYKKKKKYYBOOOOOTTTBKKKYYYOW",
                        "..DBYYYYYYGTTTTTGGGBYKKYYYO",
                        "....BBYYYGTGTGGTRRTBYYYYYOC.....EBBBD",
                        "....DDOOOGRTGTRRRRRGBYYYOLLMD.EEKKKYED",
                        "........GRRRTRRRRRRGTOOOWLLCWBYKKKKKYBD",
                        "........GRRRTRRRRRTTTTCWWLLCBYKKKKKKKBD",
                        "........GRRRTRRRRRGRTTCWWLLOEYYKKBBKKYOW",
                        "........GGRRGRRRRGTRTTLWWLCCEYYYEKKEKYOW",
                        "........GRTGGGTTGGRRRTGLWTLCEYYBYKKKYYOW",
                        "........GRRRGRRRTTGRRTGCWWGOEYYOEYYYYOW",
                        "......DYGRRRTRRRRRTGTYYBBWGOEYYOEYYYYOW",
                        "......YKKGRRTRRRRRTGYKKKYBWOEYYEOEYYOW",
                        "....DYKKKGGGGGTTTTTYKKKKKYBYYYYYYOOOW",
                        "....DYKKKKGTTTTGGGGBKKKKKYOYYYYOOOWW",
                        "....DBKKKKYMTTTTTGGBKKKKKYBOOOOWWW",
                        "....WOWOYYYYYEEGGGGOYKOYYYYYYOW",
                        ".......BYYYYYYOMOOOOBYWOEYYYYEO",
                        ".....DEKYEKYOOWWWWWW...OYYOKEOO",
                        "......DOOWOOWW.........WOOWOOWW",
                        ".",
                        "......WW.WW",
                        "......................WW.WW",
                    },
                },
                Poses = new Dictionary<string, string[]>
                {
                    { "blink", new string[]
                        {
                            ".",
                            ".",
                            "............YYYYBB",
                            ".........DYYSSSSKKBBD",
                            "........DYSSSSKKKKKKB",
                            ".......DESSSSKKKKKKKKBW",
                            "......DBKSSSKKKKKKKKKKB",
                            "......WBKKKKKKKYKKKKKKED",
                            "......BYKKKKKKYKYYYKKKYBD",
                            "......KKKKKKKKKKKKKYKYYOW",
                            "......KKKKKKKKKKKKKBYYYOW",
                            "......OOOKKKKKOOOOOBYYYOW",
                            "......KKKKKKKKKKKKKBYYYOW",
                            "....DBKKKKKKKKKKKKKYYYYOW",
                            "....WOSKYKYKKKKKKYYYYYYOW",
                            "......OBKKKKKKKKYYBYYYODDYBBB",
                            "..Y.Y.WOOKKYBBBBBCCYYYBDYKKYYOW",
                            "..BKYBOOEOOCGGGGCCYYYOEKKKBYO",
                            ".YKKKKYYOYYCCCCCYYYBOBKKKBBYO",
                            ".BKKKKKKKOBYYYYYYOOTWYKKKYYOW",
                            "..BYKKKKKYYBOOOOOTTTBKKKYYYOW",
                            "..DBYYYYYYGTTTTTGGGBYKKYYYO",
                            "....BBYYYGTGTGGTRRTBYYYYYOC.....EBBBD",
                            "....DDOOOGRTGTRRRRRGBYYYOLLMD.EEKKKYED",
                            "........GRRRTRRRRRRGTOOOWLLCWBYKKKKKYBD",
                            "........GRRRTRRRRRTTTTCWWLLCBYKKKKKKKBD",
                            "........GRRRTRRRRRGRTTCWWLLOEYYKKBBKKYOW",
                            "........GGRRGRRRRGTRTTLWWLCCEYYYEKKEKYOW",
                            "........GRTGGGTTGGRRRTGLWTLCEYYBYKKKYYOW",
                            "........GRRRGRRRTTGRRTGCWWGOEYYOEYYYYOW",
                            "......DYGRRRTRRRRRTGTYYBBWGOEYYOEYYYYOW",
                            "......YKKGRRTRRRRRTGYKKKYBWOEYYEOEYYOW",
                            "....DYKKKGGGGGTTTTTYKKKKKYBYYYYYYOOOW",
                            "....DYKKKKGTTTTGGGGBKKKKKYOYYYYOOOWW",
                            "....DBKKKKYMTTTTTGGBKKKKKYBOOOOWWW",
                            "....WOYKKYYEMMGGGGGOYKKKYYYOWWW",
                            ".....WOYYYYYEEMMOOOOBYYYYYYOW",
                            "......BYYYYYYOWWWWWWOYYYYYYOW",
                            "....DEKYEKYOOW......WOEYYYYEO",
                            ".....DOOWOOWW........OYYOKEOO",
                            "......WW.WW..........WOOWOOWW",
                            "......................WW.WW",
                        }
                    },
                    { "squash", new string[]
                        {
                            ".",
                            ".",
                            ".",
                            ".",
                            "............YYYYBB",
                            ".........DYYSSSSKKBBDD",
                            "........DYSSSSKKKKKKBB",
                            ".......DESSSSKKKKKKKKKBW",
                            "......DBKSSSKKKKKKKKKKKB",
                            "......WBKKKKKKKYKKKKKKKED",
                            "......BYKKKKKKYKYYYKKKKYBD",
                            "......BMKKKKKKKEOKWYKKYYOW",
                            "......EDYKKKKKKOOOWBYYYYOW",
                            "......BCYKKKKKKOOCDBYYYYOW",
                            "......BOKKKKKKKDOCDBYYYYOW",
                            "....DBSSKKKKKKKCOCDYYYYYOW",
                            "....WOSKYKYKKKKKKYYYYYYYOW",
                            "......OBKKKKKKKKYYBYYYYODDYBBB",
                            "..Y.Y.WOOKKYBBBBBCCYYYYBDYKKYYOW",
                            "..BKYBOOEOOCGGGGCCYYYYOEKKKBYO",
                            "YYKKKKYYOYYCCCCCYYYBOOBKKKBBYO",
                            "BBKKKKKKKOBYYYYYYOOTWWYKKKYYOW",
                            "..BYKKKKKYYBOOOOOTTTBBKKKYYYOW",
                            "....BBYYYGTGTGGTRRTBYYYYYYOC.....EBBBD",
                            "....DDOOOGRTGTRRRRRGBBYYYOLLMD.EEKKKYED",
                            "........GRRRTRRRRRRGTTOOOWLLCWBYKKKKKYBD",
                            "........GRRRTRRRRRTTTTTCWWLLCBYKKKKKKKBD",
                            "........GRRRTRRRRRGRTTTCWWLLOEYYKKBBKKYOW",
                            "........GGRRGRRRRGTRTTTLWWLCCEYYYEKKEKYOW",
                            "........GRTGGGTTGGRRRRTGLWTLCEYYBYKKKYYOW",
                            "........GRRRGRRRTTGRRRTGCWWGOEYYOEYYYYOW",
                            "......DYGRRRTRRRRRTGTTYYBBWGOEYYOEYYYYOW",
                            "......YKKGRRTRRRRRTGYYKKKYBWOEYYEOEYYOW",
                            "....DYKKKGGGGGTTTTTYKKKKKKYBYYYYYYOOOW",
                            "....DYKKKKGTTTTGGGGBKKKKKKYOYYYYOOOWW",
                            "....DBKKKKYMTTTTTGGBKKKKKKYBOOOOWWW",
                            "....WOYKKYYEMMGGGGGOYYKKKYYYOWWW",
                            ".....WOYYYYYEEMMOOOOBBYYYYYYOW",
                            "......BYYYYYYOWWWWWWOOYYYYYYOW",
                            "....DEKYEKYOOW......WWOEYYYYEO",
                            ".....DOOWOOWW.........OYYOKEOO",
                            "......WW.WW...........WOOWOOWW",
                        }
                    },
                    { "stretch", new string[]
                        {
                            ".............YYYYBB",
                            ".............YYYYBB",
                            "..........DYYSSSSKKBB",
                            ".........DYSSSSKKKKKK",
                            "........DESSSSKKKKKKKBW",
                            ".......DBKSSSKKKKKKKKKB",
                            ".......WBKKKKKKKYKKKKKED",
                            ".......BYKKKKKKYKYYYKKYBD",
                            ".......BMKKKKKKKEOKWYYYOW",
                            ".......EDYKKKKKKOOOWBYYOW",
                            ".......BCYKKKKKKOOCDBYYOW",
                            ".......BOKKKKKKKDOCDBYYOW",
                            ".....DBSSKKKKKKKCOCDYYYOW",
                            ".....WOSKYKYKKKKKKYYYYYOW",
                            ".......OBKKKKKKKKYYBYYODDYBBB",
                            "...Y.Y.WOOKKYBBBBBCCYYBDYKKYYOW",
                            "...BKYBOOEOOCGGGGCCYYOEKKKBYO",
                            "..YKKKKYYOYYCCCCCYYYBBKKKBBYO",
                            "..BKKKKKKKOBYYYYYYOOTYKKKYYOW",
                            "...BYKKKKKYYBOOOOOTTTKKKYYYOW",
                            "...DBYYYYYYGTTTTTGGGBKKYYYO",
                            ".....BBYYYGTGTGGTRRTBYYYYOC.....EBBBD",
                            ".....BBYYYGTGTGGTRRTBYYYYOC.....EBBBD",
                            ".....DDOOOGRTGTRRRRRGYYYOLLMD.EEKKKYED",
                            ".........GRRRTRRRRRRGOOOWLLCWBYKKKKKYBD",
                            ".........GRRRTRRRRRTTTCWWLLCBYKKKKKKKBD",
                            ".........GRRRTRRRRRGRTCWWLLOEYYKKBBKKYO",
                            ".........GGRRGRRRRGTRTLWWLCCEYYYEKKEKYO",
                            ".........GRTGGGTTGGRRTGLWTLCEYYBYKKKYYO",
                            ".........GRRRGRRRTTGRTGCWWGOEYYOEYYYYOW",
                            ".......DYGRRRTRRRRRTGYYBBWGOEYYOEYYYYOW",
                            ".......YKKGRRTRRRRRTGKKKYBWOEYYEOEYYOW",
                            ".....DYKKKGGGGGTTTTTYKKKKYBYYYYYYOOOW",
                            ".....DYKKKKGTTTTGGGGBKKKKYOYYYYOOOWW",
                            ".....DBKKKKYMTTTTTGGBKKKKYBOOOOWWW",
                            ".....WOYKKYYEMMGGGGGOKKKYYYOWWW",
                            "......WOYYYYYEEMMOOOOYYYYYYOW",
                            ".......BYYYYYYOWWWWWWYYYYYYOW",
                            ".....DEKYEKYOOW......OEYYYYEO",
                            "......DOOWOOWW.......OYYOKEOO",
                            ".......WW.WW.........WOOWOOWW",
                            "......................WW.WW",
                        }
                    },
                },
            },
            new PokemonSprite
            {
                Key = "ditto",
                NameKo = "메타몽",
                ScaleFactor = 0.3333333333333333,
                FacesRight = false,
                Hops = true,
                Bounce = false,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#c37ae4" },
                    { 'Y', "#9a58b3" },
                    { 'O', "#834f9b" },
                    { 'W', "#241f27" },
                    { 'R', "#ac68ca" },
                    { 'B', "#6c3a8f" },
                    { 'G', "#423c45" },
                    { 'T', "#e6adf0" },
                    { 'D', "#f2d2f3" },
                    { 'E', "#ab7eba" },
                    { 'C', "#5e218f" },
                    { 'S', "#cd8fe2" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".",
                        ".",
                        ".",
                        "..............EBWW",
                        ".............ETTRYW..BWWW",
                        "...........OBSDTKYOBBTTSYG",
                        "......EEOBBCRKSKKYYRSDDTKOW",
                        ".....ETTSKKKKKKKRRKKKTTKKYW",
                        "....ESDDTKKKKKKKKKKKKKKKKYOO",
                        "....BRTTKKKKKKKKKKKKKKKKKYYYC",
                        "....WYKKKKKKKGKKKKKKKKKKKKRKKBB",
                        ".....GRKKKKKKKKKKKKKWKKKKKKKKKKB",
                        ".....GRKKKKKRKKKKKKKRKKKKKKKKKKRG",
                        "......WYKKKKKCWOKKKKKKKKKKKKKKKRW",
                        "......WYKKKKKKRYCWWWCYKKKKKKKKKRW",
                        "......WYKKKKKKKKKKKKKKKKKKKKKKKYB",
                        "......BRKKKKKKKKKKKKKKKKKKKKKKKW",
                        ".....ORKKKKKKKKKKKKKKKKKKKKKKRYYB",
                        ".....ORKKKKKKKKKKKKKKKKKKKKKKYYYB",
                        "....WYKKKKKKKKKKKKKKKKKKKKKKKRYYOW",
                        "...GEKKKKKKKKKKKKKKKKKKKKKKKKKYYYB",
                        "..BOKKKKKKKKKKKKKKKKKKKKKKKKKRYYYYB",
                        ".DBYYRKKKKKKKKKKKKKKKKKKKKKKKYYYYYOGD",
                        ".OYYYYRKKKKKKKKKKKKKKKKKKKKKYYYYYYYOW",
                        ".GOYYYYYYYYYRKKKKKKKKKKYKRKYYYYYYYYOW",
                        ".GOYYYYYYYYYYKKKKKKKRKYKYKYYYYYYYYYOW",
                        "..WBYYYYYYYYYYRKKKKRYYKYKYYYYYYYYYYOG",
                        "..GBOYYYOOYYYYYYYYYYYYYYYYYOOYYYYOOO",
                        "...GWBOOGWBCYYYYYYYYYYYYYYBWWCOOOWG",
                        ".....GWWD..OYOYYYYYYYYYOOO...BWWO",
                        "............OGOOOOOOOOOWW",
                        "..............WWWWWWWWW",
                    },
                    new string[]
                    {
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        ".",
                        "...............EBWW",
                        ".............EETTRYW..BWWW",
                        "...........OBSSDTKYOBBTTSYGG",
                        "......EEOBBCRKKSKKYYRSDDTKOOW",
                        ".....ETTSKKKKKKKKRRKKKTTKKYYW",
                        "....ESDDTKKKKKKKKKKKKKKKKKYYOO",
                        "....BRTTKKKKKKKKKKKKKKKKKKYYYYC",
                        "....WYKKKKKKKGGKKKKKKKKKKKKKRKKBB",
                        ".....GRKKKKKKKKKKKKKKWKKKKKKKKKKKB",
                        "......WYKKKKKCCWOKKKKKKKKKKKKKKKKRW",
                        "......WYKKKKKKKRYCWWWCYKKKKKKKKKKRW",
                        "......WYKKKKKKKKKKKKKKKKKKKKKKKKKYB",
                        "......BRKKKKKKKKKKKKKKKKKKKKKKKKKW",
                        ".....ORKKKKKKKKKKKKKKKKKKKKKKKKRYYB",
                        ".....ORKKKKKKKKKKKKKKKKKKKKKKKKYYYB",
                        "....WYKKKKKKKKKKKKKKKKKKKKKKKKKRYYOW",
                        "...GEKKKKKKKKKKKKKKKKKKKKKKKKKKKYYYB",
                        "..BOKKKKKKKKKKKKKKKKKKKKKKKKKKKRYYYYB",
                        "OOYYYYRKKKKKKKKKKKKKKKKKKKKKKKYYYYYYYOW",
                        "GGOYYYYYYYYYRKKKKKKKKKKKYKRRKYYYYYYYYOW",
                        "GGOYYYYYYYYYYKKKKKKKKRKYKYKKYYYYYYYYYOW",
                        "..WBYYYYYYYYYYYRKKKKRYYKYKYYYYYYYYYYYOG",
                        "..GBOYYYOOYYYYYYYYYYYYYYYYYYYOOYYYYOOO",
                        "...GWBOOGWBCYYYYYYYYYYYYYYYYBWWCOOOWG",
                        ".....GWWD..OYOOYYYYYYYYYOOOO...BWWO",
                        "............OGGOOOOOOOOOWW",
                    },
                    new string[]
                    {
                        "...............EBWW",
                        "...............EBWW",
                        "..............ETTRYW..BWW",
                        ".............OSDTKYOBBTTSG",
                        "........EEOBBCKSKKYYRSDDTOW",
                        ".......ETTSKKKKKKRRKKKTTKYW",
                        "......ESDDTKKKKKKKKKKKKKKYOO",
                        "......BRTTKKKKKKKKKKKKKKKYYYC",
                        "......WYKKKKKKGKKKKKKKKKKKRKKBB",
                        ".......GRKKKKKKKKKKKKWKKKKKKKKKB",
                        ".......GRKKKKKKKKKKKKRKKKKKKKKKRG",
                        ".......GRKKKKKKKKKKKKRKKKKKKKKKRG",
                        "........WYKKKKCWOKKKKKKKKKKKKKKRW",
                        "........WYKKKKKRYCWWWCYKKKKKKKKRW",
                        "........WYKKKKKKKKKKKKKKKKKKKKKYB",
                        "........BRKKKKKKKKKKKKKKKKKKKKKW",
                        ".......ORKKKKKKKKKKKKKKKKKKKKRYYB",
                        ".......ORKKKKKKKKKKKKKKKKKKKKYYYB",
                        "......WYKKKKKKKKKKKKKKKKKKKKKRYYOW",
                        ".....GEKKKKKKKKKKKKKKKKKKKKKKKYYYB",
                        "....BOKKKKKKKKKKKKKKKKKKKKKKKRYYYYB",
                        "...DBYYRKKKKKKKKKKKKKKKKKKKKKYYYYYOG",
                        "...DBYYRKKKKKKKKKKKKKKKKKKKKKYYYYYOG",
                        "...OYYYYRKKKKKKKKKKKKKKKKKKKYYYYYYYO",
                        "...GOYYYYYYYYYKKKKKKKKKKYRKYYYYYYYYO",
                        "...GOYYYYYYYYYKKKKKKKRKYKKYYYYYYYYYO",
                        "....WBYYYYYYYYYRKKKKRYYKYYYYYYYYYYYO",
                        "....GBOYYYOOYYYYYYYYYYYYYYYOOYYYYOOO",
                        ".....GWBOOGWBCYYYYYYYYYYYYBWWCOOOWG",
                        ".......GWWD..OOYYYYYYYYYOO...BWWO",
                        "..............GOOOOOOOOOW",
                        "...............WWWWWWWWW",
                    },
                },
                Poses = new Dictionary<string, string[]>
                {
                    { "blink", new string[]
                        {
                            ".",
                            ".",
                            ".",
                            "..............EBWW",
                            ".............ETTRYW..BWWW",
                            "...........OBSDTKYOBBTTSYG",
                            "......EEOBBCRKSKKYYRSDDTKOW",
                            ".....ETTSKKKKKKKRRKKKTTKKYW",
                            "....ESDDTKKKKKKKKKKKKKKKKYOO",
                            "....BRTTKKKKKKKKKKKKKKKKKYYYC",
                            "....WYKKKKKKKGKKKKKKKKKKKKRKKBB",
                            ".....GRKKKKKKKKKKKKKWKKKKKKKKKKB",
                            ".....GRKKKKKRKKKKKKKRKKKKKKKKKKRG",
                            "......WYKKKKKWWWKKKKKKKKKKKKKKKRW",
                            "......WYKKKKKKKKCWWWCCCKKKKKKKKRW",
                            "......WYKKKKKKKKKKKKKKKKKKKKKKKYB",
                            "......BRKKKKKKKKKKKKKKKKKKKKKKKW",
                            ".....ORKKKKKKKKKKKKKKKKKKKKKKRYYB",
                            ".....ORKKKKKKKKKKKKKKKKKKKKKKYYYB",
                            "....WYKKKKKKKKKKKKKKKKKKKKKKKRYYOW",
                            "...GEKKKKKKKKKKKKKKKKKKKKKKKKKYYYB",
                            "..BOKKKKKKKKKKKKKKKKKKKKKKKKKRYYYYB",
                            ".DBYYRKKKKKKKKKKKKKKKKKKKKKKKYYYYYOGD",
                            ".OYYYYRKKKKKKKKKKKKKKKKKKKKKYYYYYYYOW",
                            ".GOYYYYYYYYYRKKKKKKKKKKYKRKYYYYYYYYOW",
                            ".GOYYYYYYYYYYKKKKKKKRKYKYKYYYYYYYYYOW",
                            "..WBYYYYYYYYYYRKKKKRYYKYKYYYYYYYYYYOG",
                            "..GBOYYYOOYYYYYYYYYYYYYYYYYOOYYYYOOO",
                            "...GWBOOGWBCYYYYYYYYYYYYYYBWWCOOOWG",
                            ".....GWWD..OYOYYYYYYYYYOOO...BWWO",
                            "............OGOOOOOOOOOWW",
                            "..............WWWWWWWWW",
                        }
                    },
                },
            },
        };

        public static PokemonSprite Find(string key)
        {
            foreach (PokemonSprite sprite in All)
            {
                if (sprite.Key == key)
                {
                    return sprite;
                }
            }
            return null;
        }
    }
}
