// 이 파일은 자동 생성됩니다. 직접 고치지 말고 sprites.py 를 고친 뒤
//     python tools/gen_sprites_cs.py
// 를 실행하세요.
using System.Collections.Generic;

namespace PokemonTaskbar
{
    public class PokemonSprite
    {
        public string Key;
        public string NameKo;
        public double ScaleFactor;
        public Dictionary<char, string> Palette;
        public string[][] Frames;   // 걷기 프레임마다 도트 줄 묶음
    }

    public static class Sprites
    {
        public static readonly List<PokemonSprite> All = new List<PokemonSprite>
        {
            new PokemonSprite
            {
                Key = "pikachu",
                NameKo = "피카츄",
                ScaleFactor = 0.3333333333333333,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#f6e800" },
                    { 'Y', "#e7b700" },
                    { 'O', "#0f0f0f" },
                    { 'W', "#7d4c01" },
                    { 'R', "#be8501" },
                    { 'B', "#e7b602" },
                    { 'G', "#f7f777" },
                    { 'T', "#676767" },
                    { 'D', "#af0000" },
                    { 'E', "#0f0f11" },
                    { 'C', "#f5f877" },
                    { 'S', "#fdfefd" },
                    { 'L', "#dd0000" },
                    { 'M', "#f74747" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        "......O",
                        ".....OOO",
                        ".....OOO",
                        ".....OTOO",
                        "....OTTOO......................OOO",
                        "....OTTTOO..................OOOTTO",
                        "....OTTTBO................OOTTTTOO",
                        "....OTTKKO..............RYKTTTTOO",
                        ".....OKKKBO............RKKKTTTOOO",
                        ".....RKKKBO..........RBKKKKYTOOO",
                        ".....RKKKBO.........WKKKKKKKOOO",
                        "......BKYBORRBBBRRWWKKKKKKKBOO",
                        "......RYYRRCGGGGKKYKKKKKKYYO",
                        ".......WYGGGGGGGGKKKKKKYBOO..........RR",
                        "......BKKCGGGGGCGKKKKKYWE..........RBCKW",
                        ".....WKKKKGGGGGKBOOBKKYW..........RGKKKW",
                        ".....RBOOKKKKKKKESOEKKYYO........RCKKKYW",
                        "....RKESOKKKKKKKEOTEKKYYO......RYGKKYYYYW",
                        "....WKEOTKKKKKKKYOOYKKYYW.....RGCKYYYYYYW",
                        "...WBKROBKKWYKKKKKKKLLYYBO..YYKKKYYYYYYYW",
                        "...OMKKKKBKKKKKRKKKLLLDYBOWWKKYYYYYYYYYYW",
                        "...ELKKKKKRDDDDYKKKLLLDBWWCRWYYYYYYYYYYYW",
                        "..WSODKKKKKDDMMKKKKLLDDWGRKGCWYYYYYYYYYYO",
                        ".WCWWDKKKKKDMMDKKKKKDDBWKKKKRWYYYYYYYYWO",
                        "WCKKBWKKKKKKDDKKKKKKKYWKKKKKKOYYYYYYWE",
                        ".RKKYYWKKKKKKKKKKKKKKWKKKKYYOBYYYYWO",
                        ".WBYYYRRKKKKKKKKKKKKKKKKKYYBOYYYYW",
                        "..OYYYRKKKKKKKKKKKKKKKKKYYYOWYYYO",
                        "...OYYYKKKKKKKKKKKKKKKKYYYOSSWYYBO",
                        "....OWKKKKKKKKKKKKKKKKBYYYOSSSWYYBO",
                        ".....RKKKKKKKKKKKKKKKKYYRWSSWWYYYYBO",
                        "....WKKKKKKKKKKKKKKKKKYRYWOEKYYYYWO",
                        "....RKKKKKKKKKKKKKKKKKYYYWKYYYYWO",
                        "...WKKKKKKKKKKKKKKKKYYYYWBYYYOO",
                        "..WWWKKKKKKKKKKKKKKYYYYYOYYYO",
                        ".WCCRWKKKKKKKKKKKKKYYYYYOOBYBO",
                        ".RRKRKWKKKKKKKKKKKYYYYYYOSERRBO",
                        ".WYYYYRKKKKKKKKKYYYYYYYYOOWWWRYO",
                        "..RYYYYWYYKKKKYYYYYYYYYYWWWWOOE",
                        "...WYYYWYYYYYYYYYYYYYYYWWOOO",
                        "...EYYYOYYYYYYYYYYYYYYYOO",
                        "....WOOBYYYYYYYYYYYYYYBO",
                        ".......OOOOWYYYYYYYYYYO",
                        "............OOWYYYYYWO",
                        "..............OORROOO",
                        "..............WRRRRO",
                        "..............WRWRRO",
                        "..............WYRYO",
                        "...............OOO",
                    },
                    new string[]
                    {
                        "......O",
                        ".....OOO",
                        ".....OOO",
                        ".....OTOO",
                        "....OTTOO......................OOO",
                        "....OTTTOO..................OOOTTO",
                        "....OTTTBO................OOTTTTOO",
                        "....OTTKKO..............RYKTTTTOO",
                        ".....OKKKBO............RKKKTTTOOO",
                        ".....RKKKBO..........RBKKKKYTOOO",
                        ".....RKKKBO.........WKKKKKKKOOO",
                        "......BKYBORRBBBRRWWKKKKKKKBOO",
                        "......RYYRRCGGGGKKYKKKKKKYYO",
                        ".......WYGGGGGGGGKKKKKKYBOO..........RR",
                        "......BKKCGGGGGCGKKKKKYWE..........RBCKW",
                        ".....WKKKKGGGGGKBOOBKKYW..........RGKKKW",
                        ".....RBOOKKKKKKKESOEKKYYO........RCKKKYW",
                        "....RKESOKKKKKKKEOTEKKYYO......RYGKKYYYYW",
                        "......EOTKKKKKKKYOOYKKYYW.....RGCKYYYYYYW",
                        "....WKROBKKWYKKKKKKKLLYYBO..YYKKKYYYYYYYW",
                        "...WBKKKKBKKKKKRKKKLLLDYBOWWKKYYYYYYYYYYW",
                        "...OMKKKKKRDDDDYKKKLLLDBWWCRWYYYYYYYYYYYW",
                        "...ELKKKKKKDDMMKKKKLLDDWGRKGCWYYYYYYYYYYO",
                        "..WSODKKKKKDMMDKKKKKDDBWKKKKRWYYYYYYYYWO",
                        ".WCWWDKKKKKKDDKKKKKKKYWKKKKKKOYYYYYYWE",
                        "WCKKBWWKKKKKKKKKKKKKKWKKKKYYOBYYYYWO",
                        ".RKKYYRRKKKKKKKKKKKKKKKKKYYBOYYYYW",
                        ".WBYYYRKKKKKKKKKKKKKKKKKYYYOWYYYO",
                        "..OOYYYKKKKKKKKKKKKKKKKYYYOSSWYYBO",
                        "....OWKKKKKKKKKKKKKKKKBYYYOSSSWYYBO",
                        ".....WKKKKKKKKKKKKKKKKYYRWSSWWYYYYBO",
                        "....WWWKKKKKKKKKKKKKKKYRYWOEKYYYYWO",
                        "...WCCRWKKKKKKKKKKKKKKYYYWKYYYYWO",
                        "...RRKRKWKKKKKKKKKKKYYYYWBYYYOO",
                        "...WYYYYRKKKKKKKKKKYYYYYOYYYO",
                        "....RYYYYKKKKKKKKKKYYYYYOOBYBO",
                        ".....WYYYKKKKKKKKKYYYYYYOSERRBO",
                        ".....EYYYKKKKKKKYYYYYYYYOOWWWRYO",
                        "......WOOYKKKKYYYYYYYYYYWWWWOOE",
                        ".......WYYYYYYYYYYYYYYYWWOOO",
                        ".......OYYYYYYYYYYYYYYYOO",
                        ".......BYYYYYYYYYYYYYYYO",
                        ".......OOOOW.OOWYYYYYWO",
                        "...............OORROOO",
                        "...............WRRRRO",
                        "...............WRWRRO",
                        "...............WYRYO",
                        "................OOO",
                        ".",
                    },
                    new string[]
                    {
                        "......O",
                        ".....OOO",
                        ".....OOO",
                        ".....OTOO",
                        "....OTTOO......................OOO",
                        "....OTTTOO..................OOOTTO",
                        "....OTTTBO................OOTTTTOO",
                        "....OTTKKO..............RYKTTTTOO",
                        ".....OKKKBO............RKKKTTTOOO",
                        ".....RKKKBO..........RBKKKKYTOOO",
                        ".....RKKKBO.........WKKKKKKKOOO",
                        "......BKYBORRBBBRRWWKKKKKKKBOO",
                        "......RYYRRCGGGGKKYKKKKKKYYO",
                        ".......WYGGGGGGGGKKKKKKYBOO..........RR",
                        "......BKKCGGGGGCGKKKKKYWE..........RBCKW",
                        ".....WKKKKGGGGGKBOOBKKYW..........RGKKKW",
                        ".....RBOOKKKKKKKESOEKKYYO........RCKKKYW",
                        "....RKESOKKKKKKKEOTEKKYYO......RYGKKYYYYW",
                        "....WKEOTKKKKKKKYOOYKKYYW.....RGCKYYYYYYW",
                        "...WBKROBKKWYKKKKKKKLLYYBO..YYKKKYYYYYYYW",
                        "...OMKKKKBKKKKKRKKKLLLDYBOWWKKYYYYYYYYYYW",
                        "...ELKKKKKRDDDDYKKKLLLDBWWCRWYYYYYYYYYYYW",
                        "..WSODKKKKKDDMMKKKKLLDDWGRKGCWYYYYYYYYYYO",
                        ".WCWWDKKKKKDMMDKKKKKDDBWKKKKRWYYYYYYYYWO",
                        "WCKKBWKKKKKKDDKKKKKKKYWKKKKKKOYYYYYYWE",
                        ".RKKYYWKKKKKKKKKKKKKKWKKKKYYOBYYYYWO",
                        ".WBYYYRRKKKKKKKKKKKKKKKKKYYBOYYYYW",
                        "..OYYYRKKKKKKKKKKKKKKKKKYYYOWYYYO",
                        "...OYYYKKKKKKKKKKKKKKKKYYYOSSWYYBO",
                        "....OWKKKKKKKKKKKKKKKKBYYYOSSSWYYBO",
                        ".....RKKKKKKKKKKKKKKKKYYRWSSWWYYYYBO",
                        "....WKKKKKKKKKKKKKKKKKYRYWOEKYYYYWO",
                        "....RKKKKKKKKKKKKKKKKKYYYWKYYYYWO",
                        "...WKKKKKKKKKKKKKKKKYYYYWBYYYOO",
                        "..WWWKKKKKKKKKKKKKKYYYYYOYYYO",
                        ".WCCRWKKKKKKKKKKKKKYYYYYOOBYBO",
                        ".RRKRKWKKKKKKKKKKKYYYYYYOSERRBO",
                        ".WYYYYRKKKKKKKKKYYYYYYYYOOWWWRYO",
                        "..RYYYYWYYKKKKYYYYYYYYYYWWWWOOE",
                        "...WYYYWYYYYYYYYYYYYYYYWWOOO",
                        "...EYYYOYYYYYYYYYYYYYYYOO",
                        "....WOOBYYYYYYYYYYYYYYBO",
                        ".......OOOOWYYYYYYYYYYO",
                        "............OOWYYYYYWO",
                        "..............OORROOO",
                        "..............WRRRRO",
                        "..............WRWRRO",
                        "..............WYRYO",
                        "...............OOO",
                    },
                    new string[]
                    {
                        "......O",
                        ".....OOO",
                        ".....OOO",
                        ".....OTOO",
                        "....OTTOO......................OOO",
                        "....OTTTOO..................OOOTTO",
                        "....OTTTBO................OOTTTTOO",
                        "....OTTKKO..............RYKTTTTOO",
                        ".....OKKKBO............RKKKTTTOOO",
                        ".....RKKKBO..........RBKKKKYTOOO",
                        ".....RKKKBO.........WKKKKKKKOOO",
                        "......BKYBORRBBBRRWWKKKKKKKBOO",
                        "......RYYRRCGGGGKKYKKKKKKYYO",
                        ".......WYGGGGGGGGKKKKKKYBOO..........RR",
                        "......BKKCGGGGGCGKKKKKYWE..........RBCKW",
                        ".....WKKKKGGGGGKBOOBKKYW..........RGKKKW",
                        ".....RBOOKKKKKKKESOEKKYYO........RCKKKYW",
                        "....WKESOKKKKKKKEOTEKKYYO......RYGKKYYYYW",
                        "...WBKEOTKKKKKKKYOOYKKYYW.....RGCKYYYYYYW",
                        "...OMKROBKKWYKKKKKKKLLYYBO..YYKKKYYYYYYYW",
                        "...ELKKKKBKKKKKRKKKLLLDYBOWWKKYYYYYYYYYYW",
                        "..WSODKKKKRDDDDYKKKLLLDBWWCRWYYYYYYYYYYYW",
                        ".WCWWDKKKKKDDMMKKKKLLDDWGRKGCWYYYYYYYYYYO",
                        "WCKKBWKKKKKDMMDKKKKKDDBWKKKKRWYYYYYYYYWO",
                        ".RKKYYKKKKKKDDKKKKKKKYWKKKKKKOYYYYYYWE",
                        ".WBYYYWKKKKKKKKKKKKKKWKKKKYYOBYYYYWO",
                        "..OYYYRRKKKKKKKKKKKKKKKKKYYBOYYYYW",
                        "......RKKKKKKKKKKKKKKKKKYYYOWYYYO",
                        "...OYYYKKKKKKKKKKKKKKKKYYYOSSWYYBO",
                        "....OWKKKKKKKKKKKKKKKKBYYYOSSSWYYBO",
                        ".....RKKKKKKKKKKKKKKKKYYRWSSWWYYYYBO",
                        "....WKKKKKKKKKKKKKKKKKYRYWOEKYYYYWO",
                        "....WKKKKKKKKKKKKKKKKKYYYWKYYYYWO",
                        "...WWWKKKKKKKKKKKKKKYYYYWBYYYOO",
                        "..WCCRWKKKKKKKKKKKKYYYYYOYYYO",
                        "..RRKRKWKKKKKKKKKKKYYYYYOOBYBO",
                        "..WYYYYRKKKKKKKKKKYYYYYYOSERRBO",
                        "...RYYYYKKKKKKKKYYYYYYYYOOWWWRYO",
                        "....WYYYYYKKKKYYYYYYYYYYWWWWOOE",
                        "....EYYYYYYYYYYYYYYYYYYYWOOO",
                        ".....WOOYYYYYYOOWYYYYYWOO",
                        ".......BYYYYYYYYOORROOOO",
                        ".......OOOOW....WRRRROO",
                        "................WRWRRO",
                        "................WYRYO",
                        ".................OOO",
                        ".",
                        ".",
                        ".",
                    },
                },
            },
            new PokemonSprite
            {
                Key = "charmander",
                NameKo = "파이리",
                ScaleFactor = 1.0,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#2b2b2b" },
                    { 'O', "#f0803c" },
                    { 'S', "#c85a1e" },
                    { 'C', "#f8dcae" },
                    { 'W', "#ffffff" },
                    { 'R', "#e8482c" },
                    { 'Y', "#ffd24a" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".......KKKKKK",
                        "......KOOOOOOK",
                        ".....KOOOOOOOOK",
                        ".....KOKWKOOKWKOK",
                        ".....KOKKKOOKKKOK",
                        ".....KOOOOOOOOOOK...KRK",
                        "......KOOSSSSOOK..KRYRK",
                        "......KKOOOOOOKK..KRYYRK",
                        ".....KOOOOOOOOOOK.KRRYRK",
                        "....KOOCCCCCCCCOK..KRRK",
                        "....KOCCCCCCCCCOKKKSOK",
                        "....KOCCCCCCCCCOKKSOK",
                        "....KOCCCCCCCCCOK",
                        ".....KOCCCCCCCOK",
                        ".....KOOKKKKOOK",
                        "....KKKK..KKKK",
                    },
                    new string[]
                    {
                        ".......KKKKKK",
                        "......KOOOOOOK",
                        ".....KOOOOOOOOK",
                        ".....KOKWKOOKWKOK",
                        ".....KOKKKOOKKKOK",
                        ".....KOOOOOOOOOOK...KRK",
                        "......KOOSSSSOOK..KRYRK",
                        "......KKOOOOOOKK..KRYYRK",
                        ".....KOOOOOOOOOOK.KRRYRK",
                        "....KOOCCCCCCCCOK..KRRK",
                        "....KOCCCCCCCCCOKKKSOK",
                        "....KOCCCCCCCCCOKKSOK",
                        "....KOCCCCCCCCCOK",
                        ".....KOCCCCCCCOK",
                        "....KOOKKKKOOK",
                        "...KKKK....KKKK",
                    },
                },
            },
            new PokemonSprite
            {
                Key = "bulbasaur",
                NameKo = "이상해씨",
                ScaleFactor = 1.0,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#2b2b2b" },
                    { 'T', "#7ec8a4" },
                    { 'D', "#4e9e7c" },
                    { 'G', "#6dbe45" },
                    { 'E', "#4a9130" },
                    { 'W', "#ffffff" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        ".......KKGGGGKK",
                        "......KGGEGGEGGK",
                        ".....KGGGGEGGGGGK",
                        ".....KGGEGGGGEGGK",
                        "....KKKGGGGGGGKKK",
                        "...KTTTKKKKKKKTTTK",
                        "..KTTDTTTTTTTTTDTTK",
                        "..KTTTTTTTTTTTTTTTK",
                        "..KTKWKTTTTTTKWKTTK",
                        "..KTKKKTTTTTTKKKTTK",
                        "..KTTTTTTKKTTTTTTTK",
                        "..KTTDTTTTTTTTTDTTK",
                        "...KTTTTTTTTTTTTTK",
                        "...KTTTTTTTTTTTTTK",
                        "...KKTTKKKKKKTTKK",
                        "....KKKK....KKKK",
                    },
                    new string[]
                    {
                        ".......KKGGGGKK",
                        "......KGGEGGEGGK",
                        ".....KGGGGEGGGGGK",
                        ".....KGGEGGGGEGGK",
                        "....KKKGGGGGGGKKK",
                        "...KTTTKKKKKKKTTTK",
                        "..KTTDTTTTTTTTTDTTK",
                        "..KTTTTTTTTTTTTTTTK",
                        "..KTKWKTTTTTTKWKTTK",
                        "..KTKKKTTTTTTKKKTTK",
                        "..KTTTTTTKKTTTTTTTK",
                        "..KTTDTTTTTTTTTDTTK",
                        "...KTTTTTTTTTTTTTK",
                        "...KTTTTTTTTTTTTTK",
                        "..KKTTKKKKKKTTKK",
                        "..KKKK......KKKK",
                    },
                },
            },
            new PokemonSprite
            {
                Key = "squirtle",
                NameKo = "꼬부기",
                ScaleFactor = 1.0,
                Palette = new Dictionary<char, string>
                {
                    { 'K', "#2b2b2b" },
                    { 'B', "#78c8f0" },
                    { 'D', "#3878a8" },
                    { 'S', "#c87838" },
                    { 'L', "#f0c078" },
                    { 'C', "#f8e8c0" },
                    { 'W', "#ffffff" },
                },
                Frames = new string[][]
                {
                    new string[]
                    {
                        "......KKKKKK",
                        ".....KBBBBBBK",
                        "....KBBBBBBBBK",
                        "....KBKWKBBKWKBK",
                        "....KBKKKBBKKKBK",
                        "....KBBBBBBBBBBK",
                        ".....KBBDDDDBBK",
                        "....KKKKKKKKKKKK",
                        "...KSSLLSSSSLLSSK",
                        "..KSLLSSSSSSSSLLSK",
                        "..KSSSSCCCCCCSSSSK",
                        "..KSLLSCCCCCCSLLSK",
                        "..KSSSSCCCCCCSSSSK",
                        "...KSSSSSSSSSSSSK",
                        "....KKBBKKKKBBKK",
                        ".....KKKK..KKKK",
                    },
                    new string[]
                    {
                        "......KKKKKK",
                        ".....KBBBBBBK",
                        "....KBBBBBBBBK",
                        "....KBKWKBBKWKBK",
                        "....KBKKKBBKKKBK",
                        "....KBBBBBBBBBBK",
                        ".....KBBDDDDBBK",
                        "....KKKKKKKKKKKK",
                        "...KSSLLSSSSLLSSK",
                        "..KSLLSSSSSSSSLLSK",
                        "..KSSSSCCCCCCSSSSK",
                        "..KSLLSCCCCCCSLLSK",
                        "..KSSSSCCCCCCSSSSK",
                        "...KSSSSSSSSSSSSK",
                        "...KKBBKKKKBBKK",
                        "...KKKK....KKKK",
                    },
                },
            },
        };

        public static PokemonSprite Find(string key)
        {
            foreach (PokemonSprite sprite in All)
            {
                if (sprite.Key == key)
                {
                    return sprite;
                }
            }
            return null;
        }
    }
}
