# -*- coding: utf-8 -*-
"""도트(픽셀) 스프라이트 데이터.

외부 이미지 파일이나 네트워크 없이, 문자 그리드로 포켓몬 도트를 정의한다.
각 문자는 팔레트의 색(#RRGGBB)에 대응하고 '.' 은 투명 픽셀이다.

이 모듈은 tkinter에 의존하지 않으므로 GUI 없이도 검증/테스트가 가능하다.
"""

from __future__ import annotations


class Pokemon:
    """한 마리의 도트 그림과 걷기 애니메이션 정보.

    두 가지 방식으로 정의할 수 있다.

    * rows + step_rows : 손으로 그린 스프라이트. 기본 자세와, 두 번째 프레임에서
      바꿔 끼울 줄만 적는다.
    * frame_rows       : 프레임마다 전체 줄을 적는다. tools/import_sprite.py 가
      이미지에서 만들어 내는 형식이다.
    """

    def __init__(self, key, name_ko, palette, rows=None, step_rows=None,
                 frame_rows=None, scale_factor=1.0, bounce=True, facing="right",
                 move="walk", pose_rows=None):
        self.key = key
        self.name_ko = name_ko
        self.palette = palette
        # --scale 에 곱해질 배율. 도트가 촘촘한 그림일수록 작게 잡는다.
        self.scale_factor = scale_factor
        # 프로그램이 홀수 프레임마다 살짝 띄워 주는 흔들림을 쓸지 여부.
        # 프레임 안에 이미 몸통 움직임이 그려져 있으면 끈다.
        self.bounce = bounce
        # 원본 그림이 어느 쪽을 보고 있는지. 이동 방향과 다르면 좌우로 뒤집는다.
        if facing not in ("left", "right"):
            raise ValueError("%s: facing 은 'left' 또는 'right' 여야 합니다" % key)
        self.facing = facing
        # 걷기 프레임 말고 상황에 따라 쓰는 자세들.
        # 같은 도트를 눌러 놓거나 늘여서 만든 것이라 새 그림이 필요 없다.
        #   squash  눌린 자세 (착지 반동)
        #   stretch 늘어난 자세 (공중)
        #   blink   눈을 감은 자세
        self.pose_rows = {name: list(rows) for name, rows in (pose_rows or {}).items()}

        # 걸어 다닐지(walk), 폴짝 뛰어 다닐지(hop), 공중에 떠다닐지(float).
        # hop 은 프레임이 [평소, 웅크림, 늘어남] 순서라고 본다.
        # float 은 바닥을 딛지 않고, 프레임을 천천히 돌려 가며 떠 있는다.
        if move not in ("walk", "hop", "float"):
            raise ValueError(
                "%s: move 는 'walk', 'hop', 'float' 중 하나여야 합니다" % key
            )
        self.move = move

        if frame_rows:
            self.frame_rows = [list(frame) for frame in frame_rows]
            self.rows = self.frame_rows[0]
            self.step_rows = {}
        else:
            if not rows:
                raise ValueError("%s: rows 또는 frame_rows 가 필요합니다" % key)
            self.rows = list(rows)
            self.step_rows = step_rows or {}
            stepped = list(self.rows)
            for index, replacement in self.step_rows.items():
                stepped[index] = replacement
            self.frame_rows = [self.rows, stepped]

    # --- 그리드 만들기 -------------------------------------------------
    def width(self):
        blocks = list(self.frame_rows) + list(self.pose_rows.values())
        return max(len(row) for block in blocks for row in block)

    def _grid(self, rows, width):
        grid = []
        for row in rows:
            row = row.ljust(width, ".")
            grid.append([None if ch == "." else self.palette[ch] for ch in row])
        return grid

    def frames(self):
        """걷기 프레임(색상 그리드) 목록을 돌려준다."""
        width = self.width()
        return [self._grid(frame, width) for frame in self.frame_rows]

    def poses(self):
        """이름별 자세(색상 그리드). 없으면 빈 딕셔너리."""
        width = self.width()
        return {name: self._grid(rows, width) for name, rows in self.pose_rows.items()}

    # --- 검증 -----------------------------------------------------------
    def validate(self):
        heights = {len(frame) for frame in self.frame_rows}
        if len(heights) != 1:
            raise ValueError("%s: 프레임마다 줄 수가 다릅니다" % self.key)
        for name, rows in self.pose_rows.items():
            if len(rows) != len(self.frame_rows[0]):
                raise ValueError("%s: 자세 %s 의 줄 수가 프레임과 다릅니다" % (self.key, name))
        for number, frame in enumerate(list(self.frame_rows) + list(self.pose_rows.values())):
            for index, row in enumerate(frame):
                for ch in row:
                    if ch != "." and ch not in self.palette:
                        raise ValueError(
                            "%s: %d번 프레임 %d행에 팔레트에 없는 문자 %r 이 있습니다"
                            % (self.key, number, index, ch)
                        )
        if self.scale_factor <= 0:
            raise ValueError("%s: scale_factor 는 0보다 커야 합니다" % self.key)


# --- 자동 생성 시작: pikachu ---
PIKACHU = Pokemon(
    key="pikachu",
    name_ko="피카츄",
    scale_factor=1 / 3,
    facing="left",
    palette={
        "K": "#fcb913",
        "Y": "#feec43",
        "O": "#020000",
        "W": "#542302",
        "R": "#fdec48",
        "B": "#964703",
        "G": "#da9705",
        "T": "#13110f",
        "D": "#fefda7",
        "E": "#c7250e",
        "C": "#47434d",
        "S": "#eb563f",
        "L": "#413e4b",
        "M": "#ffffff",
    },
    frame_rows=[
        [
            ".",
            ".",
            "......OO",
            ".....OTO",
            ".....TTO",
            "....OTTO",
            "....OTTO",
            "....WKGW",
            "....WKKW..............OOOOOO",
            "...WGKKW..........WWOOTCCCTO",
            "...WKKKW........WWKYGTTLTTO",
            "...WKKBBBBBBWWWOKYYYYGTTTO",
            "...WBRDDDDRRKGRRYYYYYKGOO",
            "...BRDDDDDDYYYYYYYRRKWO..........BBBB",
            "...KRDDDDDRYYYYYYKWOO.........BBBKYRW",
            "..BRRDDDRYYRRYYYRWO........BBBKYYYYRW",
            "..OCKRRRYYKCOKYYYW......BBBKYRYYYYYRW",
            ".BOMBRYYYYBMOBYYKW.....BBRYYYYYYYYYYKW",
            ".BOLBRYYYYBLOBRYKKW....BGKKKKYYYYYYYRW",
            ".BCORRYYYYKOCKRRKKW....BKKKKKKKKKYYYRW",
            ".BERYBKYYYYRRRSSKKW....BKKKKKKKKKKKKKW",
            ".WEYGGYRYGYYRSSSEKW....WKKKKKKKKGOOOOO",
            ".WEKGKBBGYYYYSSEEKWO...WGKKKGWWWO",
            "..WBKKKKKKKKKKEEKKWO....WKGWW",
            "...WBGGKKKKKKKKKKKKO....WGKT",
            "....WKKKKKKKKKKKKKKO.....OKKWW",
            "....BKKKKKKKKKKKKYYBO.....TKKW",
            "...WKGKKKKKKGKKWRYYWO....WGKO",
            "...OKBKKKKKKBKKORYRWO...WGGGOO",
            "...ORRBRYYYBRRORYYYKBO...OGGGO",
            "...OKYRBRYBRYKWRYYYRWOOOOBBWO",
            "...WWRRWRRWRRWRYYYYRWOWWWWOO",
            "..BKRWWRYYRWWRYYYYYKWBOWOO",
            "..BKKYYYYYYRRYYYKKKKBGOO",
            "..WKKKKYYYYYYKKKKKKKKKO",
            "..WGKKKKKKKKKKKKKKKKKKO",
            "...WGKKKKKKKKKKKKKKKKGO",
            "...OBGGBWWWWWGGKKKKKGO",
            "..OKKGOO.....WWWWBGBW",
            "..OOOOO.........OKBKGO",
            ".................OOOOO",
        ],
        [
            ".",
            ".",
            "......OO",
            ".....OTO",
            ".....TTO",
            "....OTTO",
            "....OTTO",
            "....WKGW",
            "....WKKW..............OOOOOO",
            "...WGKKW..........WWOOTCCCTO",
            "...WKKKW........WWKYGTTLTTO",
            "...WKKBBBBBBWWWOKYYYYGTTTO",
            "...WBRDDDDRRKGRRYYYYYKGOO",
            "...BRDDDDDDYYYYYYYRRKWO..........BBBB",
            "...KRDDDDDRYYYYYYKWOO.........BBBKYRW",
            "..BRRDDDRYYRRYYYRWO........BBBKYYYYRW",
            "..OCKRRRYYKCOKYYYW......BBBKYRYYYYYRW",
            ".BOMBRYYYYBMOBYYKW.....BBRYYYYYYYYYYKW",
            ".BOLBRYYYYBLOBRYKKW....BGKKKKYYYYYYYRW",
            ".BCORRYYYYKOCKRRKKW....BKKKKKKKKKYYYRW",
            ".BERYBKYYYYRRRSSKKW....BKKKKKKKKKKKKKW",
            ".WEYGGYRYGYYRSSSEKW....WKKKKKKKKGOOOOO",
            ".WEKGKBBGYYYYSSEEKWO...WGKKKGWWWO",
            "..WBKKKKKKKKKKEEKKWO....WKGWW",
            "...WBGGKKKKKKKKKKKKO....WGKT",
            "....WKKKKKKKKKKKKKKO.....OKKWW",
            "....BKKKKKKKKKKKKYYBO.....TKKW",
            "...WKGKKKKKKGKKWRYYWO....WGKO",
            "...OKBKKKKKKBKKORYRWO...WGGGOO",
            "...ORRBRYYYBRRORYYYKBO...OGGGO",
            "...OKYRBRYBRYKWRYYYRWOOOOBBWO",
            "...WWRRWRRWRRWRYYYYRWOWWWWOO",
            "..BKRWWRYYRWWRYYYYYKWBOWOO",
            "..BKKYYYYYYRRYYYKKKKBGOO",
            "..WKKKKYYYYYYKKKKKKKKKO",
            "..WGKOBGGBKKKKKKKKKKKKO",
            "...WOKKGOOKKKKKKKKKKKGO",
            "....OOOOOWWWWGGKWWBGBW",
            ".............WW..OKBKGO",
            "..................OOOOO",
            ".",
        ],
        [
            ".",
            ".",
            "......OO",
            ".....OTO",
            ".....TTO",
            "....OTTO",
            "....OTTO",
            "....WKGW",
            "....WKKW..............OOOOOO",
            "...WGKKW..........WWOOTCCCTO",
            "...WKKKW........WWKYGTTLTTO",
            "...WKKBBBBBBWWWOKYYYYGTTTO",
            "...WBRDDDDRRKGRRYYYYYKGOO",
            "...BRDDDDDDYYYYYYYRRKWO..........BBBB",
            "...KRDDDDDRYYYYYYKWOO.........BBBKYRW",
            "..BRRDDDRYYRRYYYRWO........BBBKYYYYRW",
            "..OCKRRRYYKCOKYYYW......BBBKYRYYYYYRW",
            ".BOMBRYYYYBMOBYYKW.....BBRYYYYYYYYYYKW",
            ".BOLBRYYYYBLOBRYKKW....BGKKKKYYYYYYYRW",
            ".BCORRYYYYKOCKRRKKW....BKKKKKKKKKYYYRW",
            ".BERYBKYYYYRRRSSKKW....BKKKKKKKKKKKKKW",
            ".WEYGGYRYGYYRSSSEKW....WKKKKKKKKGOOOOO",
            ".WEKGKBBGYYYYSSEEKWO...WGKKKGWWWO",
            "..WBKKKKKKKKKKEEKKWO....WKGWW",
            "...WBGGKKKKKKKKKKKKO....WGKT",
            "....WKKKKKKKKKKKKKKO.....OKKWW",
            "....BKKKKKKKKKKKKYYBO.....TKKW",
            "...WKGKKKKKKGKKWRYYWO....WGKO",
            "...OKBKKKKKKBKKORYRWO...WGGGOO",
            "...ORRBRYYYBRRORYYYKBO...OGGGO",
            "...OKYRBRYBRYKWRYYYRWOOOOBBWO",
            "...WWRRWRRWRRWRYYYYRWOWWWWOO",
            "..BKRWWRYYRWWRYYYYYKWBOWOO",
            "..BKKYYYYYYRRYYYKKKKBGOO",
            "..WKKKKYYYYYYKKKKKKKKKO",
            "..WGKKKKKKKKKKKKKKKKKKO",
            "...WGKKKKKKKKKKKKKKKKGO",
            "...OBGGBWWWWWGGKKKKKGO",
            "..OKKGOO.....WWWWBGBW",
            "..OOOOO.........OKBKGO",
            ".................OOOOO",
        ],
        [
            ".",
            ".",
            "......OO",
            ".....OTO",
            ".....TTO",
            "....OTTO",
            "....OTTO",
            "....WKGW",
            "....WKKW..............OOOOOO",
            "...WGKKW..........WWOOTCCCTO",
            "...WKKKW........WWKYGTTLTTO",
            "...WKKBBBBBBWWWOKYYYYGTTTO",
            "...WBRDDDDRRKGRRYYYYYKGOO",
            "...BRDDDDDDYYYYYYYRRKWO..........BBBB",
            "...KRDDDDDRYYYYYYKWOO.........BBBKYRW",
            "..BRRDDDRYYRRYYYRWO........BBBKYYYYRW",
            "..OCKRRRYYKCOKYYYW......BBBKYRYYYYYRW",
            ".BOMBRYYYYBMOBYYKW.....BBRYYYYYYYYYYKW",
            ".BOLBRYYYYBLOBRYKKW....BGKKKKYYYYYYYRW",
            ".BCORRYYYYKOCKRRKKW....BKKKKKKKKKYYYRW",
            ".BERYBKYYYYRRRSSKKW....BKKKKKKKKKKKKKW",
            ".WEYGGYRYGYYRSSSEKW....WKKKKKKKKGOOOOO",
            ".WEKGKBBGYYYYSSEEKWO...WGKKKGWWWO",
            "..WBKKKKKKKKKKEEKKWO....WKGWW",
            "...WBGGKKKKKKKKKKKKO....WGKT",
            "....WKKKKKKKKKKKKKKO.....OKKWW",
            "....BKKKKKKKKKKKKYYBO.....TKKW",
            "...WKGKKKKKKGKKWRYYWO....WGKO",
            "...OKBKKKKKKBKKORYRWO...WGGGOO",
            "...ORRBRYYYBRRORYYYKBO...OGGGO",
            "...OKYRBRYBRYKWRYYYRWOOOOBBWO",
            "...WWRRWRRWRRWRYYYYRWOWWWWOO",
            "..BKRWWRYYRWWRYYYYYKWBOWOO",
            "..BKKYYYYYYRRYYYKKKKBGOO",
            "..WKKKKYYYYYYKKKKKKKKKO",
            "..WGKKKKKKKKKKKKKKKKKKO",
            "...WOBGGBKKKKKKKKWWBGBW",
            "...OKKGOOWWWWGGKKKOKBKGO",
            "...OOOOO.....WW....OOOOO",
            ".",
            ".",
        ],
    ],
    pose_rows={
        "blink": [
            ".",
            ".",
            "......OO",
            ".....OTO",
            ".....TTO",
            "....OTTO",
            "....OTTO",
            "....WKGW",
            "....WKKW..............OOOOOO",
            "...WGKKW..........WWOOTCCCTO",
            "...WKKKW........WWKYGTTLTTO",
            "...WKKBBBBBBWWWOKYYYYGTTTO",
            "...WBRDDDDRRKGRRYYYYYKGOO",
            "...BRDDDDDDYYYYYYYRRKWO..........BBBB",
            "...KRDDDDDRYYYYYYKWOO.........BBBKYRW",
            "..BRRDDDRYYRRYYYRWO........BBBKYYYYRW",
            "..RRRRRRYYYYYYYYYW......BBBKYRYYYYYRW",
            ".OOOORYYYYOOOOYYKW.....BBRYYYYYYYYYYKW",
            ".RRRRRYYYYYYYYRYKKW....BGKKKKYYYYYYYRW",
            ".RRRRRYYYYYYYYRRKKW....BKKKKKKKKKYYYRW",
            ".BERYBKYYYYRRRSSKKW....BKKKKKKKKKKKKKW",
            ".WEYGGYRYGYYRSSSEKW....WKKKKKKKKGOOOOO",
            ".WEKGKBBGYYYYSSEEKWO...WGKKKGWWWO",
            "..WBKKKKKKKKKKEEKKWO....WKGWW",
            "...WBGGKKKKKKKKKKKKO....WGKT",
            "....WKKKKKKKKKKKKKKO.....OKKWW",
            "....BKKKKKKKKKKKKYYBO.....TKKW",
            "...WKGKKKKKKGKKWRYYWO....WGKO",
            "...OKBKKKKKKBKKORYRWO...WGGGOO",
            "...ORRBRYYYBRRORYYYKBO...OGGGO",
            "...OKYRBRYBRYKWRYYYRWOOOOBBWO",
            "...WWRRWRRWRRWRYYYYRWOWWWWOO",
            "..BKRWWRYYRWWRYYYYYKWBOWOO",
            "..BKKYYYYYYRRYYYKKKKBGOO",
            "..WKKKKYYYYYYKKKKKKKKKO",
            "..WGKKKKKKKKKKKKKKKKKKO",
            "...WGKKKKKKKKKKKKKKKKGO",
            "...OBGGBWWWWWGGKKKKKGO",
            "..OKKGOO.....WWWWBGBW",
            "..OOOOO.........OKBKGO",
            ".................OOOOO",
        ],
        "squash": [
            ".",
            ".",
            ".",
            ".",
            "......OO",
            ".....OTO",
            ".....TTO",
            "....OTTO",
            "....OTTO",
            "....WKGW",
            "....WKKW...............OOOOOO",
            "...WGKKW..........WWWOOTCCCTO",
            "...WKKKW........WWKYYGTTLTTO",
            "...WKKBBBBBBWWWOKYYYYYGTTTO",
            "...WBRDDDDRRKGRRYYYYYYKGOO",
            "...BRDDDDDDYYYYYYYRRRKWO..........BBBB",
            "...KRDDDDDRYYYYYYKWOOO.........BBBKYRW",
            "..BRRDDDRYYRRYYYRWO.........BBBKYYYYRW",
            "..OCKRRRYYKCOKYYYW.......BBBKYRYYYYYRW",
            "BBOMBRYYYYBMOBYYKW......BBRYYYYYYYYYYKW",
            "BBOLBRYYYYBLOBRYKKW.....BGKKKKYYYYYYYRW",
            "BBCORRYYYYKOCKRRKKW.....BKKKKKKKKKYYYRW",
            "BBERYBKYYYYRRRSSKKW.....BKKKKKKKKKKKKKW",
            "WWEKGKBBGYYYYSSEEKWOO...WGKKKGWWWO",
            "..WBKKKKKKKKKKEEKKWOO....WKGWW",
            "...WBGGKKKKKKKKKKKKOO....WGKT",
            "....WKKKKKKKKKKKKKKOO.....OKKWW",
            "....BKKKKKKKKKKKKYYBBO.....TKKW",
            "...WKGKKKKKKGKKWRYYWWO....WGKO",
            "...OKBKKKKKKBKKORYRWWO...WGGGOO",
            "...ORRBRYYYBRRORYYYKKBO...OGGGO",
            "...OKYRBRYBRYKWRYYYRRWOOOOBBWO",
            "...WWRRWRRWRRWRYYYYRRWOWWWWOO",
            "..BKRWWRYYRWWRYYYYYKKWBOWOO",
            "..BKKYYYYYYRRYYYKKKKKBGOO",
            "..WKKKKYYYYYYKKKKKKKKKKO",
            "..WGKKKKKKKKKKKKKKKKKKKO",
            "...WGKKKKKKKKKKKKKKKKKGO",
            "...OBGGBWWWWWGGKKKKKKGO",
            "..OKKGOO.....WWWWBGBBW",
            "..OOOOO.........OKBKKGO",
        ],
        "stretch": [
            ".......OO",
            ".......OO",
            "......OTO",
            "......TTO",
            ".....OTTO",
            ".....OTTO",
            ".....WKGW",
            ".....WKKW.............OOOOOO",
            "....WGKKW..........WOOTCCCTO",
            "....WKKKW........WWKGTTLTTO",
            "....WKKBBBBBBWWWOKYYYGTTTO",
            "....WBRDDDDRRKGRRYYYYKGOO",
            "....BRDDDDDDYYYYYYYRKWO..........BBBB",
            "....KRDDDDDRYYYYYYKWO.........BBBKYRW",
            "...BRRDDDRYYRRYYYRWO.......BBBKYYYYRW",
            "...OCKRRRYYKCOKYYYW.....BBBKYRYYYYYRW",
            "..BOMBRYYYYBMOBYYKW....BBRYYYYYYYYYYK",
            "..BOLBRYYYYBLOBRYKKW...BGKKKKYYYYYYYR",
            "..BCORRYYYYKOCKRRKKW...BKKKKKKKKKYYYR",
            "..BERYBKYYYYRRRSSKKW...BKKKKKKKKKKKKK",
            "..WEYGGYRYGYYRSSSEKW...WKKKKKKKKGOOOO",
            "..WEYGGYRYGYYRSSSEKW...WKKKKKKKKGOOOO",
            "..WEKGKBBGYYYYSSEEKW...WGKKKGWWWO",
            "...WBKKKKKKKKKKEEKKW....WKGWW",
            "....WBGGKKKKKKKKKKKK....WGKT",
            ".....WKKKKKKKKKKKKKK.....OKKWW",
            ".....BKKKKKKKKKKKKYYO.....TKKW",
            "....WKGKKKKKKGKKWRYYO....WGKO",
            "....OKBKKKKKKBKKORYRO...WGGGOO",
            "....ORRBRYYYBRRORYYYBO...OGGGO",
            "....OKYRBRYBRYKWRYYYWOOOOBBWO",
            "....WWRRWRRWRRWRYYYYWOWWWWOO",
            "...BKRWWRYYRWWRYYYYYWBOWOO",
            "...BKKYYYYYYRRYYYKKKBGOO",
            "...WKKKKYYYYYYKKKKKKKKO",
            "...WGKKKKKKKKKKKKKKKKKO",
            "....WGKKKKKKKKKKKKKKKGO",
            "....OBGGBWWWWWGGKKKKGO",
            "...OKKGOO.....WWWWBGW",
            "...OOOOO.........OKBGO",
            "..................OOOO",
        ],
    },
)
# --- 자동 생성 끝: pikachu ---

# --- 자동 생성 시작: charmander ---
CHARMANDER = Pokemon(
    key="charmander",
    name_ko="파이리",
    scale_factor=1 / 3,
    facing="left",
    palette={
        "K": "#fa973c",
        "Y": "#d9502d",
        "O": "#cc573f",
        "W": "#e4a35b",
        "R": "#281615",
        "B": "#fdd37a",
        "G": "#372c2a",
        "T": "#8b2e0c",
        "D": "#8e4324",
        "E": "#f9c158",
        "C": "#ffffff",
        "S": "#1b3975",
        "L": "#4593bb",
        "M": "#364a7c",
    },
    frame_rows=[
        [
            ".",
            ".",
            "..........OODDD",
            "........OOKKKKKTT",
            ".......OEKKKKKKKKR",
            "......OEEEKKKKKKKR",
            "......OEEEKKKKKKKWG",
            ".....OKKEKKKKKYKKKR",
            ".....OKKKKKKKYKKWKOG",
            ".....MOKKKKKKOWSSOOR",
            ".....LOKKKKKKWMSSTOR",
            "......KKKKKKKWCRLTOR",
            ".....GKKKKKKKWCSLDOR.............O",
            "....DSKKKKKKKKTLLOOR.............YE",
            "....TEEEKKKKKKKOOYOR.............YE",
            "....DEEKKYKKKKYYTYOG............YKE",
            ".....DWKKKKKKODTYOR......TD.....YKKK",
            ".....GRWKKKTTRCOYOR..DTTTOG.....YKKKY",
            "..DD...RRRRYYTOOYYTDDKKKKOG.....YKYKK",
            "..ROTTTROOTTTOOROYKKKKKKYOOR...YYYYKKO",
            "..ROKKKORGWWORROYYYKKYYYORG....YYKYYKKO",
            ".GOOYKKYOORRROOYYYYYYYOOR......YKKYKKKY",
            "..GGOOYYYYOOOOOYYYYYYOGG.......YKKKKKKY",
            "....RROOYYTOWWWOYYYTTG.........YKKKKKKY",
            "......RROYTWWWWWOYKKR...........YKYKKYO",
            "........GTOBBBBBWKKKR............YYTYO",
            ".........DWBBBBBBKKKOG............TDY",
            ".........DBBBBBBBKKKKG............TER",
            ".........DBBBBBBBKKKKWR...........TWR",
            "........DWBBBBBBBWKKKKR..........DKKR",
            "........TBBBBBBBBBKKKKG........DDKKOG",
            ".......DTBBBBBBBBBYKKKWR....TTTKKKOR",
            "......TKYWBBBBBBBWYKKKKORTTTKKKKKOWG",
            "......TKKOWBBBBWWOKKKKKKROYYYKKYWWR",
            ".....GKKKDWWWWWWWYKKKKKKORYYYYOWWG",
            ".....GKKKKRWWWWWWOKKKKKYOROYYWWWR",
            ".....GWKKKORWWWWWTYKKKYYORWWWWRG",
            "......RWKYYORRWWWTYYYYYYOGWWDD",
            ".......ROYYYOOGGGGDOYYYORDDD",
            ".......ROYYORR.....TYYYOR",
            "......ROOYYOR......TKKKOG",
            ".....GCDCOOG.......DOWKWOG",
            "......GGGRG.........GWDCDCG",
            ".....................GGGGG",
        ],
        [
            ".",
            ".",
            "..........OODDD",
            "........OOKKKKKTT",
            ".......OEKKKKKKKKR",
            "......OEEEKKKKKKKR",
            "......OEEEKKKKKKKWG",
            ".....OKKEKKKKKYKKKR",
            ".....OKKKKKKKYKKWKOG",
            ".....MOKKKKKKOWSSOOR",
            ".....LOKKKKKKWMSSTOR",
            "......KKKKKKKWCRLTOR",
            ".....GKKKKKKKWCSLDOR.............O",
            "....DSKKKKKKKKTLLOOR.............YE",
            "....TEEEKKKKKKKOOYOR.............YE",
            "....DEEKKYKKKKYYTYOG............YKE",
            ".....DWKKKKKKODTYOR......TD.....YKKK",
            ".....GRWKKKTTRCOYOR..DTTTOG.....YKKKY",
            "..DD...RRRRYYTOOYYTDDKKKKOG.....YKYKK",
            "..ROTTTROOTTTOOROYKKKKKKYOOR...YYYYKKO",
            "..ROKKKORGWWORROYYYKKYYYORG....YYKYYKKO",
            ".GOOYKKYOORRROOYYYYYYYOOR......YKKYKKKY",
            "..GGOOYYYYOOOOOYYYYYYOGG.......YKKKKKKY",
            "....RROOYYTOWWWOYYYTTG.........YKKKKKKY",
            "......RROYTWWWWWOYKKR...........YKYKKYO",
            "........GTOBBBBBWKKKR............YYTYO",
            ".........DWBBBBBBKKKOG............TDY",
            ".........DBBBBBBBKKKKG............TER",
            ".........DBBBBBBBKKKKWR...........TWR",
            "........DWBBBBBBBWKKKKR..........DKKR",
            "........TBBBBBBBBBKKKKG........DDKKOG",
            ".......DTBBBBBBBBBYKKKWR....TTTKKKOR",
            "......TKYWBBBBBBBWYKKKKORTTTKKKKKOWG",
            "......TKKOWBBBBWWOKKKKKKROYYYKKYWWR",
            ".....GKKKDWWWWWWWYKKKKKKORYYYYOWWG",
            ".....GKKKKRWWWWWWOKKKKKYOROYYWWWR",
            ".....GWKKKORWWWWWTYKKKYYORWWWWRG",
            "......RWKROYYORRWTYYYYYYOGWWDD",
            ".......RROOYYORGGGDOTYYYORDD",
            ".......GCDCOOG......TKKKOG",
            "........GGGRG.......DOWKWOG",
            ".....................GWDCDCG",
            "......................GGGGG",
            ".",
        ],
        [
            ".",
            ".",
            "..........OODDD",
            "........OOKKKKKTT",
            ".......OEKKKKKKKKR",
            "......OEEEKKKKKKKR",
            "......OEEEKKKKKKKWG",
            ".....OKKEKKKKKYKKKR",
            ".....OKKKKKKKYKKWKOG",
            ".....MOKKKKKKOWSSOOR",
            ".....LOKKKKKKWMSSTOR",
            "......KKKKKKKWCRLTOR",
            ".....GKKKKKKKWCSLDOR.............O",
            "....DSKKKKKKKKTLLOOR.............YE",
            "....TEEEKKKKKKKOOYOR.............YE",
            "....DEEKKYKKKKYYTYOG............YKE",
            ".....DWKKKKKKODTYOR......TD.....YKKK",
            ".....GRWKKKTTRCOYOR..DTTTOG.....YKKKY",
            "..DD...RRRRYYTOOYYTDDKKKKOG.....YKYKK",
            "..ROTTTROOTTTOOROYKKKKKKYOOR...YYYYKKO",
            "..ROKKKORGWWORROYYYKKYYYORG....YYKYYKKO",
            ".GOOYKKYOORRROOYYYYYYYOOR......YKKYKKKY",
            "..GGOOYYYYOOOOOYYYYYYOGG.......YKKKKKKY",
            "....RROOYYTOWWWOYYYTTG.........YKKKKKKY",
            "......RROYTWWWWWOYKKR...........YKYKKYO",
            "........GTOBBBBBWKKKR............YYTYO",
            ".........DWBBBBBBKKKOG............TDY",
            ".........DBBBBBBBKKKKG............TER",
            ".........DBBBBBBBKKKKWR...........TWR",
            "........DWBBBBBBBWKKKKR..........DKKR",
            "........TBBBBBBBBBKKKKG........DDKKOG",
            ".......DTBBBBBBBBBYKKKWR....TTTKKKOR",
            "......TKYWBBBBBBBWYKKKKORTTTKKKKKOWG",
            "......TKKOWBBBBWWOKKKKKKROYYYKKYWWR",
            ".....GKKKDWWWWWWWYKKKKKKORYYYYOWWG",
            ".....GKKKKRWWWWWWOKKKKKYOROYYWWWR",
            ".....GWKKKORWWWWWTYKKKYYORWWWWRG",
            "......RWKYYORRWWWTYYYYYYOGWWDD",
            ".......ROYYYOOGGGGDOYYYORDDD",
            ".......ROYYORR.....TYYYOR",
            "......ROOYYOR......TKKKOG",
            ".....GCDCOOG.......DOWKWOG",
            "......GGGRG.........GWDCDCG",
            ".....................GGGGG",
        ],
        [
            ".",
            ".",
            "..........OODDD",
            "........OOKKKKKTT",
            ".......OEKKKKKKKKR",
            "......OEEEKKKKKKKR",
            "......OEEEKKKKKKKWG",
            ".....OKKEKKKKKYKKKR",
            ".....OKKKKKKKYKKWKOG",
            ".....MOKKKKKKOWSSOOR",
            ".....LOKKKKKKWMSSTOR",
            "......KKKKKKKWCRLTOR",
            ".....GKKKKKKKWCSLDOR.............O",
            "....DSKKKKKKKKTLLOOR.............YE",
            "....TEEEKKKKKKKOOYOR.............YE",
            "....DEEKKYKKKKYYTYOG............YKE",
            ".....DWKKKKKKODTYOR......TD.....YKKK",
            ".....GRWKKKTTRCOYOR..DTTTOG.....YKKKY",
            "..DD...RRRRYYTOOYYTDDKKKKOG.....YKYKK",
            "..ROTTTROOTTTOOROYKKKKKKYOOR...YYYYKKO",
            "..ROKKKORGWWORROYYYKKYYYORG....YYKYYKKO",
            ".GOOYKKYOORRROOYYYYYYYOOR......YKKYKKKY",
            "..GGOOYYYYOOOOOYYYYYYOGG.......YKKKKKKY",
            "....RROOYYTOWWWOYYYTTG.........YKKKKKKY",
            "......RROYTWWWWWOYKKR...........YKYKKYO",
            "........GTOBBBBBWKKKR............YYTYO",
            ".........DWBBBBBBKKKOG............TDY",
            ".........DBBBBBBBKKKKG............TER",
            ".........DBBBBBBBKKKKWR...........TWR",
            "........DWBBBBBBBWKKKKR..........DKKR",
            "........TBBBBBBBBBKKKKG........DDKKOG",
            ".......DTBBBBBBBBBYKKKWR....TTTKKKOR",
            "......TKYWBBBBBBBWYKKKKORTTTKKKKKOWG",
            "......TKKOWBBBBWWOKKKKKKROYYYKKYWWR",
            ".....GKKKDWWWWWWWYKKKKKKORYYYYOWWG",
            ".....GKKKKRWWWWWWOKKKKKYOROYYWWWR",
            ".....GWKKKORWWWWWTYKKKYYORWWWWRG",
            "......RWKYYORRWWWTYYYTYYYORWDD",
            ".......RROYYORRGGGDOYTKKKOGD",
            ".......ROOYYOR.......DOWKWOG",
            "......GCDCOOG.........GWDCDCG",
            ".......GGGRG...........GGGGG",
            ".",
            ".",
        ],
    ],
    pose_rows={
        "blink": [
            ".",
            ".",
            "..........OODDD",
            "........OOKKKKKTT",
            ".......OEKKKKKKKKR",
            "......OEEEKKKKKKKR",
            "......OEEEKKKKKKKWG",
            ".....OKKEKKKKKYKKKR",
            ".....OKKKKKKKYKKWKOG",
            ".....MOKKKKKKKKKKKKR",
            ".....LOKKKKKKKKKKKKR",
            "......KKKKKKKRRRRRRR",
            ".....GKKKKKKKKKKKKKR.............O",
            "....DSKKKKKKKKKKKKKR.............YE",
            "....TEEEKKKKKKKOOYOR.............YE",
            "....DEEKKYKKKKYYTYOG............YKE",
            ".....DWKKKKKKODTYOR......TD.....YKKK",
            ".....GRWKKKTTRCOYOR..DTTTOG.....YKKKY",
            "..DD...RRRRYYTOOYYTDDKKKKOG.....YKYKK",
            "..ROTTTROOTTTOOROYKKKKKKYOOR...YYYYKKO",
            "..ROKKKORGWWORROYYYKKYYYORG....YYKYYKKO",
            ".GOOYKKYOORRROOYYYYYYYOOR......YKKYKKKY",
            "..GGOOYYYYOOOOOYYYYYYOGG.......YKKKKKKY",
            "....RROOYYTOWWWOYYYTTG.........YKKKKKKY",
            "......RROYTWWWWWOYKKR...........YKYKKYO",
            "........GTOBBBBBWKKKR............YYTYO",
            ".........DWBBBBBBKKKOG............TDY",
            ".........DBBBBBBBKKKKG............TER",
            ".........DBBBBBBBKKKKWR...........TWR",
            "........DWBBBBBBBWKKKKR..........DKKR",
            "........TBBBBBBBBBKKKKG........DDKKOG",
            ".......DTBBBBBBBBBYKKKWR....TTTKKKOR",
            "......TKYWBBBBBBBWYKKKKORTTTKKKKKOWG",
            "......TKKOWBBBBWWOKKKKKKROYYYKKYWWR",
            ".....GKKKDWWWWWWWYKKKKKKORYYYYOWWG",
            ".....GKKKKRWWWWWWOKKKKKYOROYYWWWR",
            ".....GWKKKORWWWWWTYKKKYYORWWWWRG",
            "......RWKYYORRWWWTYYYYYYOGWWDD",
            ".......ROYYYOOGGGGDOYYYORDDD",
            ".......ROYYORR.....TYYYOR",
            "......ROOYYOR......TKKKOG",
            ".....GCDCOOG.......DOWKWOG",
            "......GGGRG.........GWDCDCG",
            ".....................GGGGG",
        ],
        "squash": [
            ".",
            ".",
            ".",
            ".",
            "..........OODDD",
            "........OOKKKKKTT",
            ".......OEKKKKKKKKR",
            "......OEEEKKKKKKKR",
            "......OEEEKKKKKKKWG",
            ".....OKKEKKKKKYKKKR",
            ".....OKKKKKKKYKKWKOG",
            ".....MOKKKKKKOWSSOOR",
            ".....LOKKKKKKWMSSTOR",
            "......KKKKKKKWCRLTOR",
            ".....GKKKKKKKWCSLDOR..............O",
            "....DSKKKKKKKKTLLOOR..............YE",
            "....TEEEKKKKKKKOOYOR..............YE",
            "....DEEKKYKKKKYYTYOG.............YKE",
            ".....DWKKKKKKODTYOR.......TD.....YKKK",
            ".....GRWKKKTTRCOYOR...DTTTOG.....YKKKY",
            "..DD...RRRRYYTOOYYTDDDKKKKOG.....YKYKK",
            "..ROTTTROOTTTOOROYKKKKKKKYOOR...YYYYKKO",
            "..ROKKKORGWWORROYYYKKKYYYORG....YYKYYKKO",
            "GGOOYKKYOORRROOYYYYYYYYOOR......YKKYKKKY",
            "....RROOYYTOWWWOYYYTTTG.........YKKKKKKY",
            "......RROYTWWWWWOYKKRR...........YKYKKYO",
            "........GTOBBBBBWKKKRR............YYTYO",
            ".........DWBBBBBBKKKOOG............TDY",
            ".........DBBBBBBBKKKKKG............TER",
            ".........DBBBBBBBKKKKKWR...........TWR",
            "........DWBBBBBBBWKKKKKR..........DKKR",
            "........TBBBBBBBBBKKKKKG........DDKKOG",
            ".......DTBBBBBBBBBYKKKKWR....TTTKKKOR",
            "......TKYWBBBBBBBWYKKKKKORTTTKKKKKOWG",
            "......TKKOWBBBBWWOKKKKKKKROYYYKKYWWR",
            ".....GKKKDWWWWWWWYKKKKKKKORYYYYOWWG",
            ".....GKKKKRWWWWWWOKKKKKKYOROYYWWWR",
            ".....GWKKKORWWWWWTYKKKKYYORWWWWRG",
            "......RWKYYORRWWWTYYYYYYYOGWWDD",
            ".......ROYYYOOGGGGDOYYYYORDDD",
            ".......ROYYORR.....TYYYYOR",
            "......ROOYYOR......TKKKKOG",
            ".....GCDCOOG.......DOOWKWOG",
            "......GGGRG.........GGWDCDCG",
        ],
        "stretch": [
            "...........OODDD",
            "...........OODDD",
            ".........OOKKKKKTT",
            "........OEKKKKKKKKR",
            ".......OEEEKKKKKKKR",
            ".......OEEEKKKKKKKWG",
            "......OKKEKKKKKYKKKR",
            "......OKKKKKKKYKKWKO",
            "......MOKKKKKKOWSSOO",
            "......LOKKKKKKWMSSTO",
            ".......KKKKKKKWCRLTO",
            "......GKKKKKKKWCSLDO.............O",
            ".....DSKKKKKKKKTLLOO.............YE",
            ".....TEEEKKKKKKKOOYO.............YE",
            ".....DEEKKYKKKKYYTYO............YKE",
            "......DWKKKKKKODTYOR.....TD.....YKKK",
            "......GRWKKKTTRCOYOR.DTTTOG.....YKKKY",
            "...DD...RRRRYYTOOYYTDKKKKOG.....YKYKK",
            "...ROTTTROOTTTOOROYKKKKKYOOR...YYYYKKO",
            "...ROKKKORGWWORROYYYKYYYORG....YYKYYKK",
            "..GOOYKKYOORRROOYYYYYYOOR......YKKYKKK",
            "...GGOOYYYYOOOOOYYYYYOGG.......YKKKKKK",
            ".....RROOYYTOWWWOYYYTG.........YKKKKKK",
            ".....RROOYYTOWWWOYYYTG.........YKKKKKK",
            ".......RROYTWWWWWOYKR...........YKYKKY",
            ".........GTOBBBBBWKKR............YYTYO",
            "..........DWBBBBBBKKOG............TDY",
            "..........DBBBBBBBKKKG............TER",
            "..........DBBBBBBBKKKWR...........TWR",
            ".........DWBBBBBBBWKKKR..........DKKR",
            ".........TBBBBBBBBBKKKG........DDKKOG",
            "........DTBBBBBBBBBYKKWR....TTTKKKOR",
            ".......TKYWBBBBBBBWYKKKORTTTKKKKKOWG",
            ".......TKKOWBBBBWWOKKKKKROYYYKKYWWR",
            "......GKKKDWWWWWWWYKKKKKORYYYYOWWG",
            "......GKKKKRWWWWWWOKKKKYOROYYWWWR",
            "......GWKKKORWWWWWTYKKYYORWWWWRG",
            ".......RWKYYORRWWWTYYYYYOGWWDD",
            "........ROYYYOOGGGGDYYYORDDD",
            "........ROYYORR.....YYYOR",
            ".......ROOYYOR......KKKOG",
            "......GCDCOOG.......OWKWOG",
            ".......GGGRG........GWDCDCG",
            ".....................GGGGG",
        ],
    },
)
# --- 자동 생성 끝: charmander ---


# --- 자동 생성 시작: bulbasaur ---
BULBASAUR = Pokemon(
    key="bulbasaur",
    name_ko="이상해씨",
    scale_factor=1 / 3,
    facing="left",
    palette={
        "K": "#589bb4",
        "Y": "#a3d7df",
        "O": "#07090a",
        "W": "#beedea",
        "R": "#849b48",
        "B": "#2f606b",
        "G": "#437e90",
        "T": "#eaf9a8",
        "D": "#c3d476",
        "E": "#a5322c",
        "C": "#57623b",
        "S": "#ffffff",
        "L": "#29535a",
        "M": "#dd9291",
    },
    frame_rows=[
        [
            ".",
            ".",
            "............................C",
            "..........................CCDOO",
            "..................RRRRCCCCDRRCRO",
            "................RRTTTTTTDDDRDCRO",
            "...............RTTTTTTTTTRRDDRCO",
            "....LL........RTTTTTLORRRTDDDRCO",
            "...KWWBL.BBBBBBBBLLLWYOTTTTDDDCRO",
            "...KWWWBBYWWWWYYYLWWWYOTTTTDDDCRRO",
            "...KYKWWWWWGGGWYYWWWYYOTTTTDDDRCRO",
            "...KGWWWWWGGGGWWYYYYYYKOTTTDDDRCRRO",
            "...GWWWWWGGGGWWWYYYYYYKOTTDDDDRRCRO",
            "...GWWWWWGGGWWWWYKKYYYKOTDDDDRRRCRRO",
            "..GBYYWWWWWWWWYWGWWBYKKKODDDRRRRCRRO",
            "..BEKWYWWWGGWYWGEESWBKKKOLDRRRRRCRRO",
            "..BEKWYWWGGGWYWGEESSBKKKOBRRRRRCRRRO",
            ".GWESKWWWGGWWWKESEESWKKKBKBRRRRCRRRO",
            ".GSESKYWWWWWWYKESMMSWKKKGKKBRRCRRRO",
            ".GYEEKYYYYYYYYKEEMMWKKKKKKKKBBRRRRO",
            ".BOYYYYYYYYYYYYYYYYKKBKKKKKKKKBRRO",
            ".BGOLYYGYGYYYYYYYGBOOKKGKKKBBKKBO",
            "..BGSEEYYYYYGLOOOSGKKKKBKKKBBBKKB",
            "...BGGGEEEEEEEEEEGKKKKBKKKKKBBKKKB",
            "....OOGGGEEMMMMGKKKKOOKKKKKGKKKKKB",
            "......OOGKKKKKKKKOOOKKKGKKLKKKBKKKO",
            "......BKOOOOOOOOOKKKKKKBKKOKKBBBKKO",
            "......KYYYKBKKKKKKBYYKKKBOKKKBBBKKO",
            ".......GKYYKBOKKKBKKYYKKBOKKKBBBKKO",
            ".......GKYYKKKOOOBKKKYKKBOKKKKBKKO",
            ".......KYYYYKKO..KYKKYKKB.OGKGKGKO",
            "........BYGYKKO..KYYYYKO..GSLSLSB",
            ".......BSLSBSO...GYKYKKO...OOOOO",
            "........OOOOO...BSBSBKO",
            ".................OOOOO",
        ],
        [
            ".",
            ".",
            "............................C",
            "..........................CCDOO",
            "..................RRRRCCCCDRRCRO",
            "................RRTTTTTTDDDRDCRO",
            "...............RTTTTTTTTTRRDDRCO",
            "....LL........RTTTTTLORRRTDDDRCO",
            "...KWWBL.BBBBBBBBLLLWYOTTTTDDDCRO",
            "...KWWWBBYWWWWYYYLWWWYOTTTTDDDCRRO",
            "...KYKWWWWWGGGWYYWWWYYOTTTTDDDRCRO",
            "...KGWWWWWGGGGWWYYYYYYKOTTTDDDRCRRO",
            "...GWWWWWGGGGWWWYYYYYYKOTTDDDDRRCRO",
            "...GWWWWWGGGWWWWYKKYYYKOTDDDDRRRCRRO",
            "..GBYYWWWWWWWWYWGWWBYKKKODDDRRRRCRRO",
            "..BEKWYWWWGGWYWGEESWBKKKOLDRRRRRCRRO",
            "..BEKWYWWGGGWYWGEESSBKKKOBRRRRRCRRRO",
            ".GWESKWWWGGWWWKESEESWKKKBKBRRRRCRRRO",
            ".GSESKYWWWWWWYKESMMSWKKKGKKBRRCRRRO",
            ".GYEEKYYYYYYYYKEEMMWKKKKKKKKBBRRRRO",
            ".BOYYYYYYYYYYYYYYYYKKBKKKKKKKKBRRO",
            ".BGOLYYGYGYYYYYYYGBOOKKGKKKBBKKBO",
            "..BGSEEYYYYYGLOOOSGKKKKBKKKBBBKKB",
            "...BGGGEEEEEEEEEEGKKKKBKKKKKBBKKKB",
            "....OOGGGEEMMMMGKKKKOOKKKKKGKKKKKB",
            "......OOGKKKKKKKKOOOKKKGKKLKKKBKKKO",
            "......BKOOOOOOOOOKKKKKKBKKOKKBBBKKO",
            "......KYYYKBKKKKKKBYYKKKBOKKKBBBKKO",
            ".......GKYYYYKKOKBKKYYKKBOKKKBBBKKO",
            ".......GKBYGYKKOOBKYKKYKKBOGKGKGKO",
            "........BSLSBSO...KYYYYKO.GSLSLSB",
            ".........OOOOO....GYKYKKO..OOOOO",
            ".................BSBSBKO",
            "..................OOOOO",
            ".",
        ],
        [
            ".",
            ".",
            "............................C",
            "..........................CCDOO",
            "..................RRRRCCCCDRRCRO",
            "................RRTTTTTTDDDRDCRO",
            "...............RTTTTTTTTTRRDDRCO",
            "....LL........RTTTTTLORRRTDDDRCO",
            "...KWWBL.BBBBBBBBLLLWYOTTTTDDDCRO",
            "...KWWWBBYWWWWYYYLWWWYOTTTTDDDCRRO",
            "...KYKWWWWWGGGWYYWWWYYOTTTTDDDRCRO",
            "...KGWWWWWGGGGWWYYYYYYKOTTTDDDRCRRO",
            "...GWWWWWGGGGWWWYYYYYYKOTTDDDDRRCRO",
            "...GWWWWWGGGWWWWYKKYYYKOTDDDDRRRCRRO",
            "..GBYYWWWWWWWWYWGWWBYKKKODDDRRRRCRRO",
            "..BEKWYWWWGGWYWGEESWBKKKOLDRRRRRCRRO",
            "..BEKWYWWGGGWYWGEESSBKKKOBRRRRRCRRRO",
            ".GWESKWWWGGWWWKESEESWKKKBKBRRRRCRRRO",
            ".GSESKYWWWWWWYKESMMSWKKKGKKBRRCRRRO",
            ".GYEEKYYYYYYYYKEEMMWKKKKKKKKBBRRRRO",
            ".BOYYYYYYYYYYYYYYYYKKBKKKKKKKKBRRO",
            ".BGOLYYGYGYYYYYYYGBOOKKGKKKBBKKBO",
            "..BGSEEYYYYYGLOOOSGKKKKBKKKBBBKKB",
            "...BGGGEEEEEEEEEEGKKKKBKKKKKBBKKKB",
            "....OOGGGEEMMMMGKKKKOOKKKKKGKKKKKB",
            "......OOGKKKKKKKKOOOKKKGKKLKKKBKKKO",
            "......BKOOOOOOOOOKKKKKKBKKOKKBBBKKO",
            "......KYYYKBKKKKKKBYYKKKBOKKKBBBKKO",
            ".......GKYYKBOKKKBKKYYKKBOKKKBBBKKO",
            ".......GKYYKKKOOOBKKKYKKBOKKKKBKKO",
            ".......KYYYYKKO..KYKKYKKB.OGKGKGKO",
            "........BYGYKKO..KYYYYKO..GSLSLSB",
            ".......BSLSBSO...GYKYKKO...OOOOO",
            "........OOOOO...BSBSBKO",
            ".................OOOOO",
        ],
        [
            ".",
            ".",
            "............................C",
            "..........................CCDOO",
            "..................RRRRCCCCDRRCRO",
            "................RRTTTTTTDDDRDCRO",
            "...............RTTTTTTTTTRRDDRCO",
            "....LL........RTTTTTLORRRTDDDRCO",
            "...KWWBL.BBBBBBBBLLLWYOTTTTDDDCRO",
            "...KWWWBBYWWWWYYYLWWWYOTTTTDDDCRRO",
            "...KYKWWWWWGGGWYYWWWYYOTTTTDDDRCRO",
            "...KGWWWWWGGGGWWYYYYYYKOTTTDDDRCRRO",
            "...GWWWWWGGGGWWWYYYYYYKOTTDDDDRRCRO",
            "...GWWWWWGGGWWWWYKKYYYKOTDDDDRRRCRRO",
            "..GBYYWWWWWWWWYWGWWBYKKKODDDRRRRCRRO",
            "..BEKWYWWWGGWYWGEESWBKKKOLDRRRRRCRRO",
            "..BEKWYWWGGGWYWGEESSBKKKOBRRRRRCRRRO",
            ".GWESKWWWGGWWWKESEESWKKKBKBRRRRCRRRO",
            ".GSESKYWWWWWWYKESMMSWKKKGKKBRRCRRRO",
            ".GYEEKYYYYYYYYKEEMMWKKKKKKKKBBRRRRO",
            ".BOYYYYYYYYYYYYYYYYKKBKKKKKKKKBRRO",
            ".BGOLYYGYGYYYYYYYGBOOKKGKKKBBKKBO",
            "..BGSEEYYYYYGLOOOSGKKKKBKKKBBBKKB",
            "...BGGGEEEEEEEEEEGKKKKBKKKKKBBKKKB",
            "....OOGGGEEMMMMGKKKKOOKKKKKGKKKKKB",
            "......OOGKKKKKKKKOOOKKKGKKLKKKBKKKO",
            "......BKOOOOOOOOOKKKKKKBKKOKKBBBKKO",
            "......KYYYKBKKKKKKBYYKKKBOKKKBBBKKO",
            ".......GKYYKBOKKKBKYKKYKKBKOGKGKGKO",
            ".......GKYYYYKKOOBKYYYYKOOKGSLSLSB",
            ".........BYGYKKO..GYKYKKO...OOOOO",
            "........BSLSBSO..BSBSBKO",
            ".........OOOOO....OOOOO",
            ".",
            ".",
        ],
    ],
    pose_rows={
        "blink": [
            ".",
            ".",
            "............................C",
            "..........................CCDOO",
            "..................RRRRCCCCDRRCRO",
            "................RRTTTTTTDDDRDCRO",
            "...............RTTTTTTTTTRRDDRCO",
            "....LL........RTTTTTLORRRTDDDRCO",
            "...KWWBL.BBBBBBBBLLLWYOTTTTDDDCRO",
            "...KWWWBBYWWWWYYYLWWWYOTTTTDDDCRRO",
            "...KYKWWWWWGGGWYYWWWYYOTTTTDDDRCRO",
            "...KGWWWWWGGGGWWYYYYYYKOTTTDDDRCRRO",
            "...GWWWWWGGGGWWWYYYYYYKOTTDDDDRRCRO",
            "...GWWWWWGGGWWWWYKKYYYKOTDDDDRRRCRRO",
            "..GBYYWWWWWWWWYWGWWBYKKKODDDRRRRCRRO",
            "..BEYYYYYWGGWWWWWWWWBKKKOLDRRRRRCRRO",
            "..BEYYYYYGGGWWWWWWWSBKKKOBRRRRRCRRRO",
            ".GWEEEEEEGGWWEEEEEESWKKKBKBRRRRCRRRO",
            ".GSEYYYYYWWWWWWWWWWSWKKKGKKBRRCRRRO",
            ".GYEYYYYYYYYYWWWWWWWKKKKKKKKBBRRRRO",
            ".BOYYYYYYYYYYYYYYYYKKBKKKKKKKKBRRO",
            ".BGOLYYGYGYYYYYYYGBOOKKGKKKBBKKBO",
            "..BGSEEYYYYYGLOOOSGKKKKBKKKBBBKKB",
            "...BGGGEEEEEEEEEEGKKKKBKKKKKBBKKKB",
            "....OOGGGEEMMMMGKKKKOOKKKKKGKKKKKB",
            "......OOGKKKKKKKKOOOKKKGKKLKKKBKKKO",
            "......BKOOOOOOOOOKKKKKKBKKOKKBBBKKO",
            "......KYYYKBKKKKKKBYYKKKBOKKKBBBKKO",
            ".......GKYYKBOKKKBKKYYKKBOKKKBBBKKO",
            ".......GKYYKKKOOOBKKKYKKBOKKKKBKKO",
            ".......KYYYYKKO..KYKKYKKB.OGKGKGKO",
            "........BYGYKKO..KYYYYKO..GSLSLSB",
            ".......BSLSBSO...GYKYKKO...OOOOO",
            "........OOOOO...BSBSBKO",
            ".................OOOOO",
        ],
        "squash": [
            ".",
            ".",
            ".",
            ".",
            ".............................C",
            "...........................CCDOO",
            "..................RRRRRCCCCDRRCRO",
            "................RRTTTTTTTDDDRDCRO",
            "...............RTTTTTTTTTTRRDDRCO",
            "....LL........RTTTTTTLORRRTDDDRCO",
            "...KWWBL.BBBBBBBBLLLLWYOTTTTDDDCRO",
            "...KWWWBBYWWWWYYYLWWWWYOTTTTDDDCRRO",
            "...KYKWWWWWGGGWYYWWWWYYOTTTTDDDRCRO",
            "...KGWWWWWGGGGWWYYYYYYYKOTTTDDDRCRRO",
            "...GWWWWWGGGGWWWYYYYYYYKOTTDDDDRRCRO",
            "...GWWWWWGGGWWWWYKKKYYYKOTDDDDRRRCRRO",
            "..GBYYWWWWWWWWYWGWWWBYKKKODDDRRRRCRRO",
            "..BEKWYWWWGGWYWGEESSWBKKKOLDRRRRRCRRO",
            "..BEKWYWWGGGWYWGEESSSBKKKOBRRRRRCRRRO",
            "GGWESKWWWGGWWWKESEEESWKKKBKBRRRRCRRRO",
            "GGYEEKYYYYYYYYKEEMMMWKKKKKKKKBBRRRRO",
            "BBOYYYYYYYYYYYYYYYYYKKBKKKKKKKKBRRO",
            "BBGOLYYGYGYYYYYYYGBBOOKKGKKKBBKKBO",
            "..BGSEEYYYYYGLOOOSGGKKKKBKKKBBBKKB",
            "...BGGGEEEEEEEEEEGKKKKKBKKKKKBBKKKB",
            "....OOGGGEEMMMMGKKKKKOOKKKKKGKKKKKB",
            "......OOGKKKKKKKKOOOOKKKGKKLKKKBKKKO",
            "......BKOOOOOOOOOKKKKKKKBKKOKKBBBKKO",
            "......KYYYKBKKKKKKBBYYKKKBOKKKBBBKKO",
            ".......GKYYKBOKKKBKKKYYKKBOKKKBBBKKO",
            ".......GKYYKKKOOOBKKKKYKKBOKKKKBKKO",
            ".......KYYYYKKO..KYYKKYKKB.OGKGKGKO",
            "........BYGYKKO..KYYYYYKO..GSLSLSB",
            ".......BSLSBSO...GYYKYKKO...OOOOO",
            "........OOOOO...BSBBSBKO",
        ],
        "stretch": [
            "............................C",
            "............................C",
            "..........................CCDOO",
            "...................RRRCCCCDRRCRO",
            ".................RRTTTTTDDDRDCRO",
            "................RTTTTTTTTRRDDRCO",
            ".....LL........RTTTTLORRRTDDDRCO",
            "....KWWBL.BBBBBBBBLLWYOTTTTDDDCRO",
            "....KWWWBBYWWWWYYYLWWYOTTTTDDDCRRO",
            "....KYKWWWWWGGGWYYWWYYOTTTTDDDRCRO",
            "....KGWWWWWGGGGWWYYYYYKOTTTDDDRCRRO",
            "....GWWWWWGGGGWWWYYYYYKOTTDDDDRRCRO",
            "....GWWWWWGGGWWWWYKYYYKOTDDDDRRRCRR",
            "...GBYYWWWWWWWWYWGWBYKKKODDDRRRRCRR",
            "...BEKWYWWWGGWYWGEEWBKKKOLDRRRRRCRR",
            "...BEKWYWWGGGWYWGEESBKKKOBRRRRRCRRR",
            "..GWESKWWWGGWWWKESESWKKKBKBRRRRCRRR",
            "..GSESKYWWWWWWYKESMSWKKKGKKBRRCRRRO",
            "..GSESKYWWWWWWYKESMSWKKKGKKBRRCRRRO",
            "..GYEEKYYYYYYYYKEEMWKKKKKKKKBBRRRRO",
            "..BOYYYYYYYYYYYYYYYKKBKKKKKKKKBRRO",
            "..BGOLYYGYGYYYYYYYGOOKKGKKKBBKKBO",
            "...BGSEEYYYYYGLOOOSKKKKBKKKBBBKKB",
            "....BGGGEEEEEEEEEEGKKKBKKKKKBBKKKB",
            ".....OOGGGEEMMMMGKKKOOKKKKKGKKKKKB",
            ".......OOGKKKKKKKKOOKKKGKKLKKKBKKKO",
            ".......BKOOOOOOOOOKKKKKBKKOKKBBBKKO",
            ".......KYYYKBKKKKKKYYKKKBOKKKBBBKKO",
            "........GKYYKBOKKKBKYYKKBOKKKBBBKKO",
            "........GKYYKKKOOOBKKYKKBOKKKKBKKO",
            "........KYYYYKKO..KKKYKKB.OGKGKGKO",
            ".........BYGYKKO..KYYYKO..GSLSLSB",
            "........BSLSBSO...GKYKKO...OOOOO",
            ".........OOOOO...BSSBKO",
            "..................OOOO",
        ],
    },
)
# --- 자동 생성 끝: bulbasaur ---


# --- 자동 생성 시작: squirtle ---
SQUIRTLE = Pokemon(
    key="squirtle",
    name_ko="꼬부기",
    scale_factor=1 / 3,
    facing="left",
    palette={
        "K": "#60aa9b",
        "Y": "#92d3ca",
        "O": "#141c19",
        "W": "#467364",
        "R": "#fcdc88",
        "B": "#c67f31",
        "G": "#e3ab5b",
        "T": "#579283",
        "D": "#682e0c",
        "E": "#b4f2ea",
        "C": "#cbc2b8",
        "S": "#b4690f",
        "L": "#803d17",
        "M": "#fdfcf9",
    },
    frame_rows=[
        [
            ".",
            ".",
            "............KKKKWW",
            "..........KKEEEEYYWW",
            ".........KEEEEYYYYYYW",
            "........TEEEEYYYYYYYYWK",
            ".......WYEEEYYYYYYYYYYW",
            ".......WYYYYYYYKYYYYYYT",
            "......WKYYYYYYKYKKKYYYKW",
            "......WLYYYYYYYTOCCKYKKO",
            "......WMKYYYYYYOOOCWKKKO",
            "......WDKYYYYYYOODMWKKKO",
            "......WOYYYYYYYMODMWKKKO",
            ".....WEEYYYYYYYDODMKKKKO",
            ".....OEYKYKYYYYYYKKKKKKO",
            "......OWYYYYYYYYKKWKKKO..KWWW",
            "..K.K..OOYYKWWWWWDDKKKW.KYYKKO",
            "..WYKWOOTOODBBBBDDKKKOTYYYWKO",
            ".KYYYYKKOKKDDDDDKKKWOWYYYWWKO",
            ".WYYYYYYYOWKKKKKKOOGCKYYYKKO",
            "..WKYYYYYKKWOOOOOGGGWYYYKKKO",
            "...WKKKKKKBGGGGGBBBWKYYKKKO",
            "....WWKKKBGBGBBGRRGWKKKKKOD.....WWWW",
            "......OOOBRGBGRRRRRBWKKKOSSL..WWYYYKT",
            "........BRRRGRRRRRRBGOOOCSSD.WKYYYYYKW",
            "........BRRRGRRRRRGGGGDCCSSDWKYYYYYYYW",
            "........BRRRGRRRRRBRGGDCCSSOTKKYYWWYYKO",
            "........BBRRBRRRRBGRGGSCCSDDTKKKTYYTYKO",
            "........BRGBBBGGBBRRRGBSCGSDTKKWKYYYKKO",
            "........BRRRBRRRGGBRRGBDCCBOTKKOTKKKKO",
            ".......KBRRRGRRRRRGBGKKWWCBOTKKOTKKKKO",
            "......KYCBRRGRRRRRGBKYYYKWCOTKKTOTKKO",
            ".....KYYYBBBBBGGGGGKYYYYYKWKKKKKKOOO",
            "....EKYYYYBGGGGBBBBWYYYYYKOKKKKOOO",
            ".....WYYYYKLGGGGGBBWYYYYYKWOOOO",
            ".....OKYYKKTLLBBBBBOKYYYKKKO",
            "......OKKKKKTTLLOOOOWKKKKKKO",
            "......WKKKKKKO.C....OKKKKKKO",
            ".....WYKTYKOO........OTKKKKTO",
            "......OO.OO..........OKKOYTOO",
            "......................OO.OO",
        ],
        [
            ".",
            ".",
            "............KKKKWW",
            "..........KKEEEEYYWW",
            ".........KEEEEYYYYYYW",
            "........TEEEEYYYYYYYYWK",
            ".......WYEEEYYYYYYYYYYW",
            ".......WYYYYYYYKYYYYYYT",
            "......WKYYYYYYKYKKKYYYKW",
            "......WLYYYYYYYTOCCKYKKO",
            "......WMKYYYYYYOOOCWKKKO",
            "......WDKYYYYYYOODMWKKKO",
            "......WOYYYYYYYMODMWKKKO",
            ".....WEEYYYYYYYDODMKKKKO",
            ".....OEYKYKYYYYYYKKKKKKO",
            "......OWYYYYYYYYKKWKKKO..KWWW",
            "..K.K..OOYYKWWWWWDDKKKW.KYYKKO",
            "..WYKWOOTOODBBBBDDKKKOTYYYWKO",
            ".KYYYYKKOKKDDDDDKKKWOWYYYWWKO",
            ".WYYYYYYYOWKKKKKKOOGCKYYYKKO",
            "..WKYYYYYKKWOOOOOGGGWYYYKKKO",
            "...WKKKKKKBGGGGGBBBWKYYKKKO",
            "....WWKKKBGBGBBGRRGWKKKKKOD.....WWWW",
            "......OOOBRGBGRRRRRBWKKKOSSL..WWYYYKT",
            "........BRRRGRRRRRRBGOOOCSSD.WKYYYYYKW",
            "........BRRRGRRRRRGGGGDCCSSDWKYYYYYYYW",
            "........BRRRGRRRRRBRGGDCCSSOTKKYYWWYYKO",
            "........BBRRBRRRRBGRGGSCCSDDTKKKTYYTYKO",
            "........BRGBBBGGBBRRRGBSCGSDTKKWKYYYKKO",
            "........BRRRBRRRGGBRRGBDCCBOTKKOTKKKKO",
            ".......KBRRRGRRRRRGBGKKWWCBOTKKOTKKKKO",
            "......KYCBRRGRRRRRGBKYYYKWCOTKKTOTKKO",
            ".....KYYYBBBBBGGGGGKYYYYYKWKKKKKKOOO",
            "....EKYYYYBGGGGBBBBWYYYYYKOKKKKOOO",
            ".....WYYOKKKKKTTGBBWYYYYYKWOOOO",
            ".....OKYWKKKKKKOBBBOKYYYKKKO",
            ".......WYKTYKOOLOOOOWOKKKKKKO",
            "........OO.OO..C......OTKKKKTO",
            "......................OKKOYTOO",
            ".......................OO.OO",
            ".",
        ],
        [
            ".",
            ".",
            "............KKKKWW",
            "..........KKEEEEYYWW",
            ".........KEEEEYYYYYYW",
            "........TEEEEYYYYYYYYWK",
            ".......WYEEEYYYYYYYYYYW",
            ".......WYYYYYYYKYYYYYYT",
            "......WKYYYYYYKYKKKYYYKW",
            "......WLYYYYYYYTOCCKYKKO",
            "......WMKYYYYYYOOOCWKKKO",
            "......WDKYYYYYYOODMWKKKO",
            "......WOYYYYYYYMODMWKKKO",
            ".....WEEYYYYYYYDODMKKKKO",
            ".....OEYKYKYYYYYYKKKKKKO",
            "......OWYYYYYYYYKKWKKKO..KWWW",
            "..K.K..OOYYKWWWWWDDKKKW.KYYKKO",
            "..WYKWOOTOODBBBBDDKKKOTYYYWKO",
            ".KYYYYKKOKKDDDDDKKKWOWYYYWWKO",
            ".WYYYYYYYOWKKKKKKOOGCKYYYKKO",
            "..WKYYYYYKKWOOOOOGGGWYYYKKKO",
            "...WKKKKKKBGGGGGBBBWKYYKKKO",
            "....WWKKKBGBGBBGRRGWKKKKKOD.....WWWW",
            "......OOOBRGBGRRRRRBWKKKOSSL..WWYYYKT",
            "........BRRRGRRRRRRBGOOOCSSD.WKYYYYYKW",
            "........BRRRGRRRRRGGGGDCCSSDWKYYYYYYYW",
            "........BRRRGRRRRRBRGGDCCSSOTKKYYWWYYKO",
            "........BBRRBRRRRBGRGGSCCSDDTKKKTYYTYKO",
            "........BRGBBBGGBBRRRGBSCGSDTKKWKYYYKKO",
            "........BRRRBRRRGGBRRGBDCCBOTKKOTKKKKO",
            ".......KBRRRGRRRRRGBGKKWWCBOTKKOTKKKKO",
            "......KYCBRRGRRRRRGBKYYYKWCOTKKTOTKKO",
            ".....KYYYBBBBBGGGGGKYYYYYKWKKKKKKOOO",
            "....EKYYYYBGGGGBBBBWYYYYYKOKKKKOOO",
            ".....WYYYYKLGGGGGBBWYYYYYKWOOOO",
            ".....OKYYKKTLLBBBBBOKYYYKKKO",
            "......OKKKKKTTLLOOOOWKKKKKKO",
            "......WKKKKKKO.C....OKKKKKKO",
            ".....WYKTYKOO........OTKKKKTO",
            "......OO.OO..........OKKOYTOO",
            "......................OO.OO",
        ],
        [
            ".",
            ".",
            "............KKKKWW",
            "..........KKEEEEYYWW",
            ".........KEEEEYYYYYYW",
            "........TEEEEYYYYYYYYWK",
            ".......WYEEEYYYYYYYYYYW",
            ".......WYYYYYYYKYYYYYYT",
            "......WKYYYYYYKYKKKYYYKW",
            "......WLYYYYYYYTOCCKYKKO",
            "......WMKYYYYYYOOOCWKKKO",
            "......WDKYYYYYYOODMWKKKO",
            "......WOYYYYYYYMODMWKKKO",
            ".....WEEYYYYYYYDODMKKKKO",
            ".....OEYKYKYYYYYYKKKKKKO",
            "......OWYYYYYYYYKKWKKKO..KWWW",
            "..K.K..OOYYKWWWWWDDKKKW.KYYKKO",
            "..WYKWOOTOODBBBBDDKKKOTYYYWKO",
            ".KYYYYKKOKKDDDDDKKKWOWYYYWWKO",
            ".WYYYYYYYOWKKKKKKOOGCKYYYKKO",
            "..WKYYYYYKKWOOOOOGGGWYYYKKKO",
            "...WKKKKKKBGGGGGBBBWKYYKKKO",
            "....WWKKKBGBGBBGRRGWKKKKKOD.....WWWW",
            "......OOOBRGBGRRRRRBWKKKOSSL..WWYYYKT",
            "........BRRRGRRRRRRBGOOOCSSD.WKYYYYYKW",
            "........BRRRGRRRRRGGGGDCCSSDWKYYYYYYYW",
            "........BRRRGRRRRRBRGGDCCSSOTKKYYWWYYKO",
            "........BBRRBRRRRBGRGGSCCSDDTKKKTYYTYKO",
            "........BRGBBBGGBBRRRGBSCGSDTKKWKYYYKKO",
            "........BRRRBRRRGGBRRGBDCCBOTKKOTKKKKO",
            ".......KBRRRGRRRRRGBGKKWWCBOTKKOTKKKKO",
            "......KYCBRRGRRRRRGBKYYYKWCOTKKTOTKKO",
            ".....KYYYBBBBBGGGGGKYYYYYKWKKKKKKOOO",
            "....EKYYYYBGGGGBBBBWYYYYYKOKKKKOOO",
            ".....WYYYYKLGGGGGBBWYYYYYKWOOOO",
            ".....OKOKKKKKTTBBBBOKYOKKKKKKO",
            ".......WKKKKKKOLOOOOWKKOTKKKKTO",
            "......WYKTYKOO.C.......OKKOYTOO",
            ".......OO.OO............OO.OO",
            ".",
            ".",
        ],
    ],
    pose_rows={
        "blink": [
            ".",
            ".",
            "............KKKKWW",
            "..........KKEEEEYYWW",
            ".........KEEEEYYYYYYW",
            "........TEEEEYYYYYYYYWK",
            ".......WYEEEYYYYYYYYYYW",
            ".......WYYYYYYYKYYYYYYT",
            "......WKYYYYYYKYKKKYYYKW",
            "......YYYYYYYYYYYYYKYKKO",
            "......YYYYYYYYYYYYYWKKKO",
            "......OOOYYYYYOOOOOWKKKO",
            "......YYYYYYYYYYYYYWKKKO",
            ".....WYYYYYYYYYYYYYKKKKO",
            ".....OEYKYKYYYYYYKKKKKKO",
            "......OWYYYYYYYYKKWKKKO..KWWW",
            "..K.K..OOYYKWWWWWDDKKKW.KYYKKO",
            "..WYKWOOTOODBBBBDDKKKOTYYYWKO",
            ".KYYYYKKOKKDDDDDKKKWOWYYYWWKO",
            ".WYYYYYYYOWKKKKKKOOGCKYYYKKO",
            "..WKYYYYYKKWOOOOOGGGWYYYKKKO",
            "...WKKKKKKBGGGGGBBBWKYYKKKO",
            "....WWKKKBGBGBBGRRGWKKKKKOD.....WWWW",
            "......OOOBRGBGRRRRRBWKKKOSSL..WWYYYKT",
            "........BRRRGRRRRRRBGOOOCSSD.WKYYYYYKW",
            "........BRRRGRRRRRGGGGDCCSSDWKYYYYYYYW",
            "........BRRRGRRRRRBRGGDCCSSOTKKYYWWYYKO",
            "........BBRRBRRRRBGRGGSCCSDDTKKKTYYTYKO",
            "........BRGBBBGGBBRRRGBSCGSDTKKWKYYYKKO",
            "........BRRRBRRRGGBRRGBDCCBOTKKOTKKKKO",
            ".......KBRRRGRRRRRGBGKKWWCBOTKKOTKKKKO",
            "......KYCBRRGRRRRRGBKYYYKWCOTKKTOTKKO",
            ".....KYYYBBBBBGGGGGKYYYYYKWKKKKKKOOO",
            "....EKYYYYBGGGGBBBBWYYYYYKOKKKKOOO",
            ".....WYYYYKLGGGGGBBWYYYYYKWOOOO",
            ".....OKYYKKTLLBBBBBOKYYYKKKO",
            "......OKKKKKTTLLOOOOWKKKKKKO",
            "......WKKKKKKO.C....OKKKKKKO",
            ".....WYKTYKOO........OTKKKKTO",
            "......OO.OO..........OKKOYTOO",
            "......................OO.OO",
        ],
        "squash": [
            ".",
            ".",
            ".",
            ".",
            "............KKKKWW",
            "..........KKEEEEYYWW",
            ".........KEEEEYYYYYYWW",
            "........TEEEEYYYYYYYYYWK",
            ".......WYEEEYYYYYYYYYYYW",
            ".......WYYYYYYYKYYYYYYYT",
            "......WKYYYYYYKYKKKYYYYKW",
            "......WLYYYYYYYTOCCKYYKKO",
            "......WMKYYYYYYOOOCWKKKKO",
            "......WDKYYYYYYOODMWKKKKO",
            "......WOYYYYYYYMODMWKKKKO",
            ".....WEEYYYYYYYDODMKKKKKO",
            ".....OEYKYKYYYYYYKKKKKKKO",
            "......OWYYYYYYYYKKWKKKKO..KWWW",
            "..K.K..OOYYKWWWWWDDKKKKW.KYYKKO",
            "..WYKWOOTOODBBBBDDKKKKOTYYYWKO",
            "KKYYYYKKOKKDDDDDKKKWOOWYYYWWKO",
            "WWYYYYYYYOWKKKKKKOOGCCKYYYKKO",
            "..WKYYYYYKKWOOOOOGGGWWYYYKKKO",
            "....WWKKKBGBGBBGRRGWKKKKKKOD.....WWWW",
            "......OOOBRGBGRRRRRBWWKKKOSSL..WWYYYKT",
            "........BRRRGRRRRRRBGGOOOCSSD.WKYYYYYKW",
            "........BRRRGRRRRRGGGGGDCCSSDWKYYYYYYYW",
            "........BRRRGRRRRRBRGGGDCCSSOTKKYYWWYYKO",
            "........BBRRBRRRRBGRGGGSCCSDDTKKKTYYTYKO",
            "........BRGBBBGGBBRRRRGBSCGSDTKKWKYYYKKO",
            "........BRRRBRRRGGBRRRGBDCCBOTKKOTKKKKO",
            ".......KBRRRGRRRRRGBGGKKWWCBOTKKOTKKKKO",
            "......KYCBRRGRRRRRGBKKYYYKWCOTKKTOTKKO",
            ".....KYYYBBBBBGGGGGKYYYYYYKWKKKKKKOOO",
            "....EKYYYYBGGGGBBBBWYYYYYYKOKKKKOOO",
            ".....WYYYYKLGGGGGBBWYYYYYYKWOOOO",
            ".....OKYYKKTLLBBBBBOKKYYYKKKO",
            "......OKKKKKTTLLOOOOWWKKKKKKO",
            "......WKKKKKKO.C....OOKKKKKKO",
            ".....WYKTYKOO.........OTKKKKTO",
            "......OO.OO...........OKKOYTOO",
        ],
        "stretch": [
            ".............KKKKWW",
            ".............KKKKWW",
            "...........KKEEEEYYW",
            "..........KEEEEYYYYYW",
            ".........TEEEEYYYYYYYWK",
            "........WYEEEYYYYYYYYYW",
            "........WYYYYYYYKYYYYYT",
            ".......WKYYYYYYKYKKKYYKW",
            ".......WLYYYYYYYTOCCYKKO",
            ".......WMKYYYYYYOOOCKKKO",
            ".......WDKYYYYYYOODMKKKO",
            ".......WOYYYYYYYMODMKKKO",
            "......WEEYYYYYYYDODMKKKO",
            "......OEYKYKYYYYYYKKKKKO",
            ".......OWYYYYYYYYKKWKKO..KWWW",
            "...K.K..OOYYKWWWWWDDKKW.KYYKKO",
            "...WYKWOOTOODBBBBDDKKOTYYYWKO",
            "..KYYYYKKOKKDDDDDKKKOWYYYWWKO",
            "..WYYYYYYYOWKKKKKKOOCKYYYKKO",
            "...WKYYYYYKKWOOOOOGGWYYYKKKO",
            "....WKKKKKKBGGGGGBBBKYYKKKO",
            "....WKKKKKKBGGGGGBBBKYYKKKO",
            ".....WWKKKBGBGBBGRRGKKKKKOD.....WWWW",
            ".......OOOBRGBGRRRRRWKKKOSSL..WWYYYKT",
            ".........BRRRGRRRRRRGOOOCSSD.WKYYYYYKW",
            ".........BRRRGRRRRRGGGDCCSSDWKYYYYYYYW",
            ".........BRRRGRRRRRBGGDCCSSOTKKYYWWYYK",
            ".........BBRRBRRRRBGGGSCCSDDTKKKTYYTYK",
            ".........BRGBBBGGBBRRGBSCGSDTKKWKYYYKK",
            ".........BRRRBRRRGGBRGBDCCBOTKKOTKKKKO",
            "........KBRRRGRRRRRGGKKWWCBOTKKOTKKKKO",
            ".......KYCBRRGRRRRRGKYYYKWCOTKKTOTKKO",
            "......KYYYBBBBBGGGGGYYYYYKWKKKKKKOOO",
            ".....EKYYYYBGGGGBBBBYYYYYKOKKKKOOO",
            "......WYYYYKLGGGGGBBYYYYYKWOOOO",
            "......OKYYKKTLLBBBBBKYYYKKKO",
            ".......OKKKKKTTLLOOOWKKKKKKO",
            ".......WKKKKKKO.C...OKKKKKKO",
            "......WYKTYKOO.......OTKKKKTO",
            ".......OO.OO.........OKKOYTOO",
            "......................OO.OO",
        ],
    },
)
# --- 자동 생성 끝: squirtle ---


# --- 자동 생성 시작: ditto ---
DITTO = Pokemon(
    key="ditto",
    name_ko="메타몽",
    scale_factor=1 / 3,
    bounce=False,
    facing="left",
    move="hop",
    palette={
        "K": "#c37ae4",
        "Y": "#9a59b3",
        "O": "#060209",
        "W": "#854f9a",
        "R": "#ac69c9",
        "B": "#66328c",
        "G": "#592085",
        "T": "#e5acef",
        "D": "#1b0f24",
        "E": "#cd8fe2",
        "C": "#fac7fa",
        "S": "#341942",
    },
    frame_rows=[
        [
            ".",
            ".",
            ".",
            "..............YBOO",
            ".............YTTRYO..GOOO",
            "...........GGECTKYWBBTTEYO",
            "......YYBGGGRKEKKYYRECCTKWO",
            ".....RTCEKKKKKKKRRKKKTTKKYO",
            "....YECCTKKKKKKKKKKKKKKKKYWB",
            "....BRTTKKKKKKKKKKKKKKKKKYYYG",
            "....DYKKKKKKKSKKKKKKKKKKKKRKKGG",
            ".....ORKKKKKKKKKKKKKOKKKKKKKKKKB",
            ".....ORKKKKKRKKKKKKKRKKKKKKKKKKRO",
            "......OYKKKKKBOWKKKKKKKKKKKKKKKRO",
            "......OYKKKKKKRYBSDDBYKKKKKKKKKRO",
            "......OYKKKKKKKKKKKKKKKKKKKKKKKYB",
            "......GRKKKKKKKKKKKKKKKKKKKKKKKD",
            ".....GRKKKKKKKKKKKKKKKKKKKKKKRYYB",
            ".....BRKKKKKKKKKKKKKKKKKKKKKKYYYB",
            "....OYKKKKKKKKKKKKKKKKKKKKKKKRYYWO",
            "...ORKKKKKKKKKKKKKKKKKKKKKKKKKYYYB",
            "..BWKKKKKKKKKKKKKKKKKKKKKKKKKRYYYYG",
            "..BYYRKKKKKKKKKKKKKKKKKKKKKKKYYYYYWD",
            ".BYYYYRKKKKKKKKKKKKKKKKKKKKKYYYYYYYWO",
            ".OWYYYYYYYYYRKKKKKKKKKKYKRKYYYYYYYYWO",
            ".OWYYYYYYYYYYKKKKKKKRKYKYKYYYYYYYYYWO",
            "..OWYYYYYYYYYYRKKKKRYYKYKYYYYYYYYYYWO",
            "..OBWYYYWWYYYYYYYYYYYYYYYYYWWYYYYWWB",
            "...OOBWWDOGGYYYYYYYYYYYYYYGOOGWWWOO",
            ".....OOO...GYWYYYYYYYYYWWG...GOOB",
            "............BDWWWWWWWWWOO",
            "..............OOOOOOOOO",
        ],
        [
            ".",
            ".",
            ".",
            ".",
            ".",
            ".",
            "...............YBOO",
            ".............YYTTRYO..GOOO",
            "...........GGEECTKYWBBTTEYOO",
            "......YYBGGGRKKEKKYYRECCTKWWO",
            ".....RTCEKKKKKKKKRRKKKTTKKYYO",
            "....YECCTKKKKKKKKKKKKKKKKKYYWB",
            "....BRTTKKKKKKKKKKKKKKKKKKYYYYG",
            "....DYKKKKKKKSSKKKKKKKKKKKKKRKKGG",
            ".....ORKKKKKKKKKKKKKKOKKKKKKKKKKKB",
            "......OYKKKKKBBOWKKKKKKKKKKKKKKKKRO",
            "......OYKKKKKKKRYBSDDBYKKKKKKKKKKRO",
            "......OYKKKKKKKKKKKKKKKKKKKKKKKKKYB",
            "......GRKKKKKKKKKKKKKKKKKKKKKKKKKD",
            ".....GRKKKKKKKKKKKKKKKKKKKKKKKKRYYB",
            ".....BRKKKKKKKKKKKKKKKKKKKKKKKKYYYB",
            "....OYKKKKKKKKKKKKKKKKKKKKKKKKKRYYWO",
            "...ORKKKKKKKKKKKKKKKKKKKKKKKKKKKYYYB",
            "..BWKKKKKKKKKKKKKKKKKKKKKKKKKKKRYYYYG",
            "BBYYYYRKKKKKKKKKKKKKKKKKKKKKKKYYYYYYYWO",
            "OOWYYYYYYYYYRKKKKKKKKKKKYKRRKYYYYYYYYWO",
            "OOWYYYYYYYYYYKKKKKKKKRKYKYKKYYYYYYYYYWO",
            "..OWYYYYYYYYYYYRKKKKRYYKYKYYYYYYYYYYYWO",
            "..OBWYYYWWYYYYYYYYYYYYYYYYYYYWWYYYYWWB",
            "...OOBWWDOGGYYYYYYYYYYYYYYYYGOOGWWWOO",
            ".....OOO...GYWWYYYYYYYYYWWGG...GOOB",
            "............BDDWWWWWWWWWOO",
        ],
        [
            "...............YBOO",
            "...............YBOO",
            "..............YTTRYO..GOO",
            ".............GECTKYWBBTTEO",
            "........YYBGGGKEKKYYRECCTWO",
            ".......RTCEKKKKKKRRKKKTTKYO",
            "......YECCTKKKKKKKKKKKKKKYWB",
            "......BRTTKKKKKKKKKKKKKKKYYYG",
            "......DYKKKKKKSKKKKKKKKKKKRKKGG",
            ".......ORKKKKKKKKKKKKOKKKKKKKKKB",
            ".......ORKKKKKKKKKKKKRKKKKKKKKKRO",
            ".......ORKKKKKKKKKKKKRKKKKKKKKKRO",
            "........OYKKKKBOWKKKKKKKKKKKKKKRO",
            "........OYKKKKKRYBSDDBYKKKKKKKKRO",
            "........OYKKKKKKKKKKKKKKKKKKKKKYB",
            "........GRKKKKKKKKKKKKKKKKKKKKKD",
            ".......GRKKKKKKKKKKKKKKKKKKKKRYYB",
            ".......BRKKKKKKKKKKKKKKKKKKKKYYYB",
            "......OYKKKKKKKKKKKKKKKKKKKKKRYYWO",
            ".....ORKKKKKKKKKKKKKKKKKKKKKKKYYYB",
            "....BWKKKKKKKKKKKKKKKKKKKKKKKRYYYYG",
            "....BYYRKKKKKKKKKKKKKKKKKKKKKYYYYYWD",
            "....BYYRKKKKKKKKKKKKKKKKKKKKKYYYYYWD",
            "...BYYYYRKKKKKKKKKKKKKKKKKKKYYYYYYYW",
            "...OWYYYYYYYYYKKKKKKKKKKYRKYYYYYYYYW",
            "...OWYYYYYYYYYKKKKKKKRKYKKYYYYYYYYYW",
            "....OWYYYYYYYYYRKKKKRYYKYYYYYYYYYYYW",
            "....OBWYYYWWYYYYYYYYYYYYYYYWWYYYYWWB",
            ".....OOBWWDOGGYYYYYYYYYYYYGOOGWWWOO",
            ".......OOO...GWYYYYYYYYYWG...GOOB",
            "..............DWWWWWWWWWO",
            "...............OOOOOOOOO",
        ],
    ],
    pose_rows={
        "blink": [
            ".",
            ".",
            ".",
            "..............YBOO",
            ".............YTTRYO..GOOO",
            "...........GGECTKYWBBTTEYO",
            "......YYBGGGRKEKKYYRECCTKWO",
            ".....RTCEKKKKKKKRRKKKTTKKYO",
            "....YECCTKKKKKKKKKKKKKKKKYWB",
            "....BRTTKKKKKKKKKKKKKKKKKYYYG",
            "....DYKKKKKKKSKKKKKKKKKKKKRKKGG",
            ".....ORKKKKKKKKKKKKKOKKKKKKKKKKB",
            ".....ORKKKKKRKKKKKKKRKKKKKKKKKKRO",
            "......OYKKKKKOOOKKKKKKKKKKKKKKKRO",
            "......OYKKKKKKKKBSDDBBBKKKKKKKKRO",
            "......OYKKKKKKKKKKKKKKKKKKKKKKKYB",
            "......GRKKKKKKKKKKKKKKKKKKKKKKKD",
            ".....GRKKKKKKKKKKKKKKKKKKKKKKRYYB",
            ".....BRKKKKKKKKKKKKKKKKKKKKKKYYYB",
            "....OYKKKKKKKKKKKKKKKKKKKKKKKRYYWO",
            "...ORKKKKKKKKKKKKKKKKKKKKKKKKKYYYB",
            "..BWKKKKKKKKKKKKKKKKKKKKKKKKKRYYYYG",
            "..BYYRKKKKKKKKKKKKKKKKKKKKKKKYYYYYWD",
            ".BYYYYRKKKKKKKKKKKKKKKKKKKKKYYYYYYYWO",
            ".OWYYYYYYYYYRKKKKKKKKKKYKRKYYYYYYYYWO",
            ".OWYYYYYYYYYYKKKKKKKRKYKYKYYYYYYYYYWO",
            "..OWYYYYYYYYYYRKKKKRYYKYKYYYYYYYYYYWO",
            "..OBWYYYWWYYYYYYYYYYYYYYYYYWWYYYYWWB",
            "...OOBWWDOGGYYYYYYYYYYYYYYGOOGWWWOO",
            ".....OOO...GYWYYYYYYYYYWWG...GOOB",
            "............BDWWWWWWWWWOO",
            "..............OOOOOOOOO",
        ],
    },
)
# --- 자동 생성 끝: ditto ---

# --- 자동 생성 시작: mew ---
MEW = Pokemon(
    key="mew",
    name_ko="뮤",
    scale_factor=1 / 3,
    bounce=False,
    facing="left",
    move="float",
    palette={
        "K": "#fab2d4",
        "Y": "#754e6b",
        "O": "#e784b2",
        "W": "#ae6690",
        "R": "#90587b",
        "B": "#c778a1",
        "G": "#673a5b",
        "T": "#ec9bc2",
        "D": "#53314b",
        "E": "#261c23",
        "C": "#0c0509",
        "S": "#3b2d36",
        "L": "#f4cee9",
        "M": "#ad96b8",
        "N": "#2c5fda",
        "P": "#ffffff",
    },
    frame_rows=[
        [
            ".",
            ".",
            ".........................................BWRDDDDM",
            ".......................................BWTKKKOOWECE",
            "......................................WKKKYCCEGGDRDS",
            ".....................................BTKGSY.....GGYGE",
            "....................................YTKGYD......RRRYGD",
            "...................................RBKYD...........YYGS",
            "..................................YYTWE............YYRE",
            "...RY..........M..................RRBS.............RRYDS",
            "...YGW........BWB................YROBE..............YGRC",
            "..WKTBWWRDD.DRTKBG...............YRWE...............YGRC",
            "..WKBTKKKKKGTKKTRE...............YRBG...............YGRC",
            "..GOKKKKKKKTKKTORE...............YRBY................RGRC",
            "..DKLLLLKKKKKKKKBD................RRWS................GWC",
            "..DLLLLKKKKKKKKKTWR...............YYBS................GBC",
            ".YWLLLKKKTOOKKKKTBY................RRRE...............GOC",
            ".DKLLKTTOWMBTKKKKBD.................GOC...............GOC",
            ".DKKLTKTWYMPTKKKKBE.................GOC...............GOC",
            ".DKKKTKMYLNLPKKKKBE.................GOC..............YYOC",
            ".COKKKLMYLNMLKKKBG.....YR...........GOC.............YGWOC",
            ".COOKKKBGNNOOKKWSE...GDMWD..........GOC.............YYBC",
            "..GOKKKKKKKKKKTOOBWEGTKTGE........YYBG..............YYBC",
            "..DTKKKKTBKKTBOOOOOMTKTOORE.......YYBC.............RRBBC",
            "..RRTKKBYSDRWBOOOOKKKTGDGR.......RRBBC.............YRBDD",
            "...YWYYYGEEWBOOOTTKOWREES........DGBGC............YRWRE",
            "....YEESRRROTTTTTKKOWWYG........RYYRE.........YYYYRBWGE",
            "......YYWOOOTKKKKKKKKKKRGS....RYRRRGS......WYRRRRRBBYS",
            ".....RWBOOWWWOKKKKKKKKKKRSS...YGRRGS......BWYROOOOBYS",
            "....GBTOOOCCSBTKKKKKKKKKKTWCDDWWWGE....BWWOKKKOOOOGE",
            ".....SRRCE...GBKKKKKKKKKKKTBDWWWDD....WKLLLLKKKOODS",
            "......SS.....DBKKKKKKTKKKKTBDEEES....WKLLLLLLKOWYY",
            ".............DBKKKKKBTKKKKTOBDD......GTLLLLLKOYEY",
            "............YWWBKKKKWKKKKKKOOE.......RRRYYYGYRYE",
            "............GBRWTTTKYTTKKKTOOC........YYSEEESY",
            "............GBBWBOOTRRBTTTOOOC",
            "............YBTBRWOOODRBOOOOOES",
            ".............DBKWSWBBBEGWBOOWGES",
            ".............GWOOBDCCCCCCDWWWWWSS",
            "..............YEDOOOWGCS.ECESOTKKWG",
            "................DCEWWWGY...YWRTKKTWY",
            ".................SCGWWGGR....YWTKKTWY",
            "..................DDWWRDD.....GBKTTOY",
            "...................DWWWSS.....GBKOBBD",
            "...................YGWWDG.....YRBOWYE",
            "....................EYYYR......YRBWSS",
            ".....................SED........YECE",
            ".",
            ".",
        ],
        [
            ".",
            ".",
            ".........................................BWRDDDDM",
            ".......................................BWTKKKOOWECE",
            "......................................WKKKYCCEGGDRDS",
            ".....................................BTKGSY.....GGYGE",
            "....................................YTKGYD......RRRYGD",
            "...................................RBKYD...........YYGS",
            "..................................YYTWE............YYRE",
            "...RY..........M..................RRBS.............RRYDS",
            "...YGW........BWB................YROBE..............YGRC",
            "..WKTBWWRDD.DRTKBG...............YRWE...............YGRC",
            "..WKBTKKKKKGTKKTRE...............YRBG...............YGRC",
            "..GOKKKKKKKTKKTORE...............YRBY................RGRC",
            "..DKLLLLKKKKKKKKBD................RRWS................GWC",
            "..DLLLLKKKKKKKKKTWR...............YYBS................GBC",
            ".YWLLLKKKTOOKKKKTBY................RRRE...............GOC",
            ".DKLLKTTOWMBTKKKKBD.................GOC...............GOC",
            ".DKKLTKTWYMPTKKKKBE.................GOC...............GOC",
            ".DKKKTKMYLNLPKKKKBE.................GOC..............YYOC",
            ".COKKKLMYLNMLKKKBG.....YR...........GOC.............YGWOC",
            ".COOKKKBGNNOOKKWSE...GDMWD..........GOC.............YYBC",
            "..GOKKKKKKKKKKTOOBWEGTKTGE........YYBG..............YYBC",
            "..DTKKKKTBKKTBOOOOOMTKTOORE.......YYBC.............RRBBC",
            "..RRTKKBYSDRWBOOOOKKKTGDGR.......RRBBC.............YRBDD",
            "...YWYYYGEEWBOOOTTKOWREES........DGBGC............YRWRE",
            "....YEESRRROTTTTTKKOWWYG........RYYRE.........YYYYRBWGE",
            "......YYWOOOTKKKKKKKKKKRGS....RYRRRGS.....BWYROOOOBYSS",
            ".....RWBOOWWWOKKKKKKKKKKRSS...YGRRGS...BWWOKKKOOOOGE",
            "....GBTOOOCCSBTKKKKKKKKKKTWCDDWWWGE....KLLLLKKKOODS",
            ".....SRRCE...GBKKKKKKKKKKKTBDWWWDD....WLLLLLLKOWYY",
            "......SS.....DBKKKKKKTKKKKTBDEEES....WKLLLLLKOYEY",
            ".............DBKKKKKBTKKKKTOBDD......GTRYYYGYRYE",
            "............YWWBKKKKWKKKKKKOOE.......RRYSEEESY",
            "............GBRWTTTKYTTKKKTOOC........Y",
            "............GBBWBOOTRRBTTTOOOC",
            "............YBTBRWOOODRBOOOOOES",
            ".............DBKWSWBBBEGWBOOWGES",
            ".............GWOOBDCCCCCCDWWWWWSS",
            "..............YEDOOOWGCS.ECEWWWGDY",
            "................DSCGWWGGR..YSOTKKWG",
            "..................DDWWRDD...WRTKKTWY",
            "...................DWWWSS....YWTKKTWY",
            "...................YGWWDG.....GBKTTOY",
            "....................EYYYR.....GBKOBBD",
            ".....................SED......YRBOWYE",
            "...............................YRBWSS",
            "................................YECE",
            ".",
        ],
        [
            ".",
            ".",
            ".........................................BWRDDDDM",
            ".......................................BWTKKKOOWECE",
            "......................................WKKKYCCEGGDRDS",
            ".....................................BTKGSY.....GGYGE",
            "....................................YTKGYD......RRRYGD",
            "...................................RBKYD...........YYGS",
            "..................................YYTWE............YYRE",
            "...RY..........M..................RRBS.............RRYDS",
            "...YGW........BWB................YROBE..............YGRC",
            "..WKTBWWRDD.DRTKBG...............YRWE...............YGRC",
            "..WKBTKKKKKGTKKTRE...............YRBG...............YGRC",
            "..GOKKKKKKKTKKTORE...............YRBY................RGRC",
            "..DKLLLLKKKKKKKKBD................RRWS................GWC",
            "..DLLLLKKKKKKKKKTWR...............YYBS................GBC",
            ".YWLLLKKKTOOKKKKTBY................RRRE...............GOC",
            ".DKLLKTTOWMBTKKKKBD.................GOC...............GOC",
            ".DKKLTKTWYMPTKKKKBE.................GOC...............GOC",
            ".DKKKTKMYLNLPKKKKBE.................GOC..............YYOC",
            ".COKKKLMYLNMLKKKBG.....YR...........GOC.............YGWOC",
            ".COOKKKBGNNOOKKWSE...GDMWD..........GOC.............YYBC",
            "..GOKKKKKKKKKKTOOBWEGTKTGE........YYBG..............YYBC",
            "..DTKKKKTBKKTBOOOOOMTKTOORE.......YYBC.............RRBBC",
            "..RRTKKBYSDRWBOOOOKKKTGDGR.......RRBBC.............YRBDD",
            "...YWYYYGEEWBOOOTTKOWREES........DGBGC............YRWRE",
            "....YEESRRROTTTTTKKOWWYG........RYYRE.....BWYROOOOBYSGE",
            "......YYWOOOTKKKKKKKKKKRGS....RYRRRGS..BWWOKKKOOOOGEYS",
            ".....RWBOOWWWOKKKKKKKKKKRSS...YGRRGS...KLLLLKKKOODS",
            "....GBTOOOCCSBTKKKKKKKKKKTWCDDWWWGE....LLLLLLKOWYY",
            ".....SRRCE...GBKKKKKKKKKKKTBDWWWDD....WLLLLLKOYEY",
            "......SS.....DBKKKKKKTKKKKTBDEEES....WKRYYYGYRYE",
            ".............DBKKKKKBTKKKKTOBDD......GTYSEEESY",
            "............YWWBKKKKWKKKKKKOOE.......RR",
            "............GBRWTTTKYTTKKKTOOC........Y",
            "............GBBWBOOTRRBTTTOOOC",
            "............YBTBRWOOODRBOOOOOES",
            ".............DBKWSWBBBEGWBOOWGES",
            ".............GWOOBDCCCCCCDWWWWWSS",
            "..............YEDSCGWWGGRECEWWWGDY",
            "................DCDDWWRDD..YCWWBOWY",
            "...................DWWWSS...SOTKKWG",
            "...................YGWWDG...WRTKKTWY",
            "....................EYYYR....YWTKKTWY",
            ".....................SED......GBKTTOY",
            "..............................GBKOBBD",
            "..............................YRBOWYE",
            "...............................YRBWSS",
            "................................YECE",
        ],
        [
            ".",
            ".",
            ".........................................BWRDDDDM",
            ".......................................BWTKKKOOWECE",
            "......................................WKKKYCCEGGDRDS",
            ".....................................BTKGSY.....GGYGE",
            "....................................YTKGYD......RRRYGD",
            "...................................RBKYD...........YYGS",
            "..................................YYTWE............YYRE",
            "...RY..........M..................RRBS.............RRYDS",
            "...YGW........BWB................YROBE..............YGRC",
            "..WKTBWWRDD.DRTKBG...............YRWE...............YGRC",
            "..WKBTKKKKKGTKKTRE...............YRBG...............YGRC",
            "..GOKKKKKKKTKKTORE...............YRBY................RGRC",
            "..DKLLLLKKKKKKKKBD................RRWS................GWC",
            "..DLLLLKKKKKKKKKTWR...............YYBS................GBC",
            ".YWLLLKKKTOOKKKKTBY................RRRE...............GOC",
            ".DKLLKTTOWMBTKKKKBD.................GOC...............GOC",
            ".DKKLTKTWYMPTKKKKBE.................GOC...............GOC",
            ".DKKKTKMYLNLPKKKKBE.................GOC..............YYOC",
            ".COKKKLMYLNMLKKKBG.....YR...........GOC.............YGWOC",
            ".COOKKKBGNNOOKKWSE...GDMWD..........GOC.............YYBC",
            "..GOKKKKKKKKKKTOOBWEGTKTGE........YYBG..............YYBC",
            "..DTKKKKTBKKTBOOOOOMTKTOORE.......YYBC.............RRBBC",
            "..RRTKKBYSDRWBOOOOKKKTGDGR.......RRBBC.............YRBDD",
            "...YWYYYGEEWBOOOTTKOWREES........DGBGC............YRWRE",
            "....YEESRRROTTTTTKKOWWYG........RYYRE.........YYYYRBWGE",
            "......YYWOOOTKKKKKKKKKKRGS....RYRRRGS.....BWYROOOOBYSS",
            ".....RWBOOWWWOKKKKKKKKKKRSS...YGRRGS...BWWOKKKOOOOGE",
            "....GBTOOOCCSBTKKKKKKKKKKTWCDDWWWGE....KLLLLKKKOODS",
            ".....SRRCE...GBKKKKKKKKKKKTBDWWWDD....WLLLLLLKOWYY",
            "......SS.....DBKKKKKKTKKKKTBDEEES....WKLLLLLKOYEY",
            ".............DBKKKKKBTKKKKTOBDD......GTRYYYGYRYE",
            "............YWWBKKKKWKKKKKKOOE.......RRYSEEESY",
            "............GBRWTTTKYTTKKKTOOC........Y",
            "............GBBWBOOTRRBTTTOOOC",
            "............YBTBRWOOODRBOOOOOES",
            ".............DBKWSWBBBEGWBOOWGES",
            ".............GWOOBDCCCCCCDWWWWWSS",
            "..............YEDOOOWGCS.ECEWWWGDY",
            "................DSCGWWGGR..YSOTKKWG",
            "..................DDWWRDD...WRTKKTWY",
            "...................DWWWSS....YWTKKTWY",
            "...................YGWWDG.....GBKTTOY",
            "....................EYYYR.....GBKOBBD",
            ".....................SED......YRBOWYE",
            "...............................YRBWSS",
            "................................YECE",
            ".",
        ],
    ],
    pose_rows={
        "blink": [
            ".",
            ".",
            ".........................................BWRDDDDM",
            ".......................................BWTKKKOOWECE",
            "......................................WKKKYCCEGGDRDS",
            ".....................................BTKGSY.....GGYGE",
            "....................................YTKGYD......RRRYGD",
            "...................................RBKYD...........YYGS",
            "..................................YYTWE............YYRE",
            "...RY..........M..................RRBS.............RRYDS",
            "...YGW........BWB................YROBE..............YGRC",
            "..WKTBWWRDD.DRTKBG...............YRWE...............YGRC",
            "..WKBTKKKKKGTKKTRE...............YRBG...............YGRC",
            "..GOKKKKKKKTKKTORE...............YRBY................RGRC",
            "..DKLLLLKKKKKKKKBD................RRWS................GWC",
            "..DLLLLKKKKKKKKKTWR...............YYBS................GBC",
            ".YWLLLKKKTOOKKKKTBY................RRRE...............GOC",
            ".DKLLKTTOWMBTKKKKBD.................GOC...............GOC",
            ".DKKLTKTWYMKKKKKKKE.................GOC...............GOC",
            ".DKKKTKMYLNKKKKKKKE.................GOC..............YYOC",
            ".COKKKLMYLNKKKKKKK.....YR...........GOC.............YGWOC",
            ".COOKKKBGNNEEEEEEE...GDMWD..........GOC.............YYBC",
            "..GOKKKKKKKKKKKKKKWEGTKTGE........YYBG..............YYBC",
            "..DTKKKKTBKKKKKKKKOMTKTOORE.......YYBC.............RRBBC",
            "..RRTKKBYSDKKKKKKKKKKTGDGR.......RRBBC.............YRBDD",
            "...YWYYYGEEWBOOOTTKOWREES........DGBGC............YRWRE",
            "....YEESRRROTTTTTKKOWWYG........RYYRE.........YYYYRBWGE",
            "......YYWOOOTKKKKKKKKKKRGS....RYRRRGS......WYRRRRRBBYS",
            ".....RWBOOWWWOKKKKKKKKKKRSS...YGRRGS......BWYROOOOBYS",
            "....GBTOOOCCSBTKKKKKKKKKKTWCDDWWWGE....BWWOKKKOOOOGE",
            ".....SRRCE...GBKKKKKKKKKKKTBDWWWDD....WKLLLLKKKOODS",
            "......SS.....DBKKKKKKTKKKKTBDEEES....WKLLLLLLKOWYY",
            ".............DBKKKKKBTKKKKTOBDD......GTLLLLLKOYEY",
            "............YWWBKKKKWKKKKKKOOE.......RRRYYYGYRYE",
            "............GBRWTTTKYTTKKKTOOC........YYSEEESY",
            "............GBBWBOOTRRBTTTOOOC",
            "............YBTBRWOOODRBOOOOOES",
            ".............DBKWSWBBBEGWBOOWGES",
            ".............GWOOBDCCCCCCDWWWWWSS",
            "..............YEDOOOWGCS.ECEWWWGDY",
            "................DCEWWWGY...YCWWBOWY",
            ".................SCGWWGGR...SOTKKWG",
            "..................DDWWRDD...WRTKKTWY",
            "...................DWWWSS....YWTKKTWY",
            "...................YGWWDG.....GBKTTOY",
            "....................EYYYR.....GBKOBBD",
            ".....................SED......YRBOWYE",
            "...............................YRBWSS",
            "................................YECE",
        ],
        "squash": [
            ".",
            ".",
            ".",
            ".",
            "..........................................BWRDDDDM",
            "........................................BWTKKKOOWECE",
            ".......................................WKKKYCCEGGDRDS",
            "......................................BTKGSY.....GGYGE",
            ".....................................YTKGYD......RRRYGD",
            "....................................RBKYD...........YYGS",
            "...................................YYTWE............YYRE",
            "...RY..........M...................RRBS.............RRYDS",
            "...YGW........BWB.................YROBE..............YGRC",
            "..WKTBWWRDD.DRTKBG................YRWE...............YGRC",
            "..WKBTKKKKKGTKKTRE................YRBG...............YGRC",
            "..GOKKKKKKKTKKTORE................YRBY................RGRC",
            "..DKLLLLKKKKKKKKBD.................RRWS................GWC",
            "..DLLLLKKKKKKKKKTWR................YYBS................GBC",
            "YYWLLLKKKTOOKKKKTBY.................RRRE...............GOC",
            "DDKLLKTTOWMBTKKKKBD..................GOC...............GOC",
            "DDKKLTKTWYMPTKKKKBE..................GOC...............GOC",
            "DDKKKTKMYLNLPKKKKBE..................GOC..............YYOC",
            "CCOKKKLMYLNMLKKKBG.....YR............GOC.............YGWOC",
            "CCOOKKKBGNNOOKKWSE...GDMWD...........GOC.............YYBC",
            "..GOKKKKKKKKKKTOOBWEGTKTGE.........YYBG..............YYBC",
            "..DTKKKKTBKKTBOOOOOMTKTOORE........YYBC.............RRBBC",
            "..RRTKKBYSDRWBOOOOKKKTGDGR........RRBBC.............YRBDD",
            "....YEESRRROTTTTTKKOWWYG.........RYYRE.........YYYYRBWGE",
            "......YYWOOOTKKKKKKKKKKRGS.....RYRRRGS......WYRRRRRBBYS",
            ".....RWBOOWWWOKKKKKKKKKKRSS....YGRRGS......BWYROOOOBYS",
            "....GBTOOOCCSBTKKKKKKKKKKTWCDDDWWWGE....BWWOKKKOOOOGE",
            ".....SRRCE...GBKKKKKKKKKKKTBDWWWWDD....WKLLLLKKKOODS",
            "......SS.....DBKKKKKKTKKKKTBDEEEES....WKLLLLLLKOWYY",
            ".............DBKKKKKBTKKKKTOBDDD......GTLLLLLKOYEY",
            "............YWWBKKKKWKKKKKKOOEE.......RRRYYYGYRYE",
            "............GBRWTTTKYTTKKKTOOCC........YYSEEESY",
            "............GBBWBOOTRRBTTTOOOCC",
            "............YBTBRWOOODRBOOOOOEES",
            ".............DBKWSWBBBEGWBOOWGGES",
            ".............GWOOBDCCCCCCDWWWWWWSS",
            "..............YEDOOOWGCS.ECEWWWWGDY",
            "................DCEWWWGY...YCWWWBOWY",
            ".................SCGWWGGR...SOOTKKWG",
            "..................DDWWRDD...WRRTKKTWY",
            "...................DWWWSS....YYWTKKTWY",
            "...................YGWWDG......GBKTTOY",
            "....................EYYYR......GBKOBBD",
            ".....................SED.......YRBOWYE",
            "................................YRBWSS",
        ],
        "stretch": [
            ".........................................BWRDDDDM",
            ".........................................BWRDDDDM",
            ".......................................BWTKKKOOWECE",
            "......................................WKKKYCCEGGDRDS",
            ".....................................BTKGSY.....GGYGE",
            "....................................YTKGYD......RRRYGD",
            "...................................RBKYD...........YYGS",
            "..................................YYTWE............YYRE",
            "....RY..........M.................RRBS.............RRYDS",
            "....YGW........BWB...............YROBE..............YGRC",
            "...WKTBWWRDD.DRTKBG..............YRWE...............YGRC",
            "...WKBTKKKKKGTKKTRE..............YRBG...............YGRC",
            "...GOKKKKKKKTKKTORE..............YRBY................RGR",
            "...DKLLLLKKKKKKKKBD...............RRWS................GW",
            "...DLLLLKKKKKKKKKTWR..............YYBS................GB",
            "..YWLLLKKKTOOKKKKTBY...............RRRE...............GO",
            "..DKLLKTTOWMBTKKKKBD................GOC...............GO",
            "..DKKLTKTWYMPTKKKKBE................GOC...............GO",
            "..DKKKTKMYLNLPKKKKBE................GOC..............YYO",
            "..COKKKLMYLNMLKKKBG.....YR..........GOC.............YGWO",
            "..COOKKKBGNNOOKKWSE...GDMWD.........GOC.............YYBC",
            "...GOKKKKKKKKKKTOOBWEGTKTGE.......YYBG..............YYBC",
            "...DTKKKKTBKKTBOOOOOMTKTOORE......YYBC.............RRBBC",
            "...RRTKKBYSDRWBOOOOKKKTGDGR......RRBBC.............YRBDD",
            "....YWYYYGEEWBOOOTTKOWREES.......DGBGC............YRWRE",
            "....YWYYYGEEWBOOOTTKOWREES.......DGBGC............YRWRE",
            ".....YEESRRROTTTTTKKOWWYG.......RYYRE.........YYYYRBWGE",
            ".......YYWOOOTKKKKKKKKKKRGS...RYRRRGS......WYRRRRRBBYS",
            "......RWBOOWWWOKKKKKKKKKKRSS..YGRRGS......BWYROOOOBYS",
            ".....GBTOOOCCSBTKKKKKKKKKKTWCDWWWGE....BWWOKKKOOOOGE",
            "......SRRCE...GBKKKKKKKKKKKTBWWWDD....WKLLLLKKKOODS",
            ".......SS.....DBKKKKKKTKKKKTBEEES....WKLLLLLLKOWYY",
            "..............DBKKKKKBTKKKKTODD......GTLLLLLKOYEY",
            ".............YWWBKKKKWKKKKKKOE.......RRRYYYGYRYE",
            ".............GBRWTTTKYTTKKKTOC........YYSEEESY",
            ".............GBBWBOOTRRBTTTOOC",
            ".............YBTBRWOOODRBOOOOES",
            "..............DBKWSWBBBEGWBOOGES",
            "..............GWOOBDCCCCCCDWWWWSS",
            "...............YEDOOOWGCS.ECEWWGDY",
            ".................DCEWWWGY...YWWBOWY",
            "..................SCGWWGGR...OTKKWG",
            "...................DDWWRDD...RTKKTWY",
            "....................DWWWSS...YWTKKTWY",
            "....................YGWWDG....GBKTTOY",
            ".....................EYYYR....GBKOBBD",
            "......................SED.....YRBOWYE",
            "...............................YRBWSS",
            "................................YECE",
        ],
    },
)
# --- 자동 생성 끝: mew ---

POKEMON = {p.key: p for p in (PIKACHU, CHARMANDER, BULBASAUR, SQUIRTLE, DITTO, MEW)}


def validate_all():
    """모든 스프라이트 데이터가 정상인지 확인한다."""
    for pokemon in POKEMON.values():
        pokemon.validate()
        frames = pokemon.frames()
        widths = {len(row) for frame in frames for row in frame}
        heights = {len(frame) for frame in frames}
        if len(widths) != 1 or len(heights) != 1:
            raise ValueError("%s: 프레임 크기가 서로 다릅니다" % pokemon.key)
        if len(frames) < 2:
            raise ValueError("%s: 프레임이 2장 이상이어야 합니다" % pokemon.key)
        if pokemon.move == "hop" and len(frames) < 3:
            raise ValueError(
                "%s: 뛰어다니는 포켓몬은 [평소, 웅크림, 늘어남] 3장이 필요합니다" % pokemon.key
            )
    return True


if __name__ == "__main__":
    validate_all()
    for pokemon in POKEMON.values():
        frame = pokemon.frames()[0]
        print("%s (%s) %dx%d, %d프레임, x%.2f" % (
            pokemon.name_ko, pokemon.key, len(frame[0]), len(frame),
            len(pokemon.frames()), pokemon.scale_factor,
        ))
