# -*- coding: utf-8 -*-
"""도트(픽셀) 스프라이트 데이터.

외부 이미지 파일이나 네트워크 없이, 문자 그리드로 포켓몬 도트를 정의한다.
각 문자는 팔레트의 색(#RRGGBB)에 대응하고 '.' 은 투명 픽셀이다.

이 모듈은 tkinter에 의존하지 않으므로 GUI 없이도 검증/테스트가 가능하다.
"""

from __future__ import annotations


class Pokemon:
    """한 마리의 도트 그림과 걷기 애니메이션 정보.

    두 가지 방식으로 정의할 수 있다.

    * rows + step_rows : 손으로 그린 스프라이트. 기본 자세와, 두 번째 프레임에서
      바꿔 끼울 줄만 적는다.
    * frame_rows       : 프레임마다 전체 줄을 적는다. tools/import_sprite.py 가
      이미지에서 만들어 내는 형식이다.
    """

    def __init__(self, key, name_ko, palette, rows=None, step_rows=None,
                 frame_rows=None, scale_factor=1.0, bounce=True, facing="right"):
        self.key = key
        self.name_ko = name_ko
        self.palette = palette
        # --scale 에 곱해질 배율. 도트가 촘촘한 그림일수록 작게 잡는다.
        self.scale_factor = scale_factor
        # 프로그램이 홀수 프레임마다 살짝 띄워 주는 흔들림을 쓸지 여부.
        # 프레임 안에 이미 몸통 움직임이 그려져 있으면 끈다.
        self.bounce = bounce
        # 원본 그림이 어느 쪽을 보고 있는지. 이동 방향과 다르면 좌우로 뒤집는다.
        if facing not in ("left", "right"):
            raise ValueError("%s: facing 은 'left' 또는 'right' 여야 합니다" % key)
        self.facing = facing

        if frame_rows:
            self.frame_rows = [list(frame) for frame in frame_rows]
            self.rows = self.frame_rows[0]
            self.step_rows = {}
        else:
            if not rows:
                raise ValueError("%s: rows 또는 frame_rows 가 필요합니다" % key)
            self.rows = list(rows)
            self.step_rows = step_rows or {}
            stepped = list(self.rows)
            for index, replacement in self.step_rows.items():
                stepped[index] = replacement
            self.frame_rows = [self.rows, stepped]

    # --- 그리드 만들기 -------------------------------------------------
    def width(self):
        return max(len(row) for frame in self.frame_rows for row in frame)

    def _grid(self, rows, width):
        grid = []
        for row in rows:
            row = row.ljust(width, ".")
            grid.append([None if ch == "." else self.palette[ch] for ch in row])
        return grid

    def frames(self):
        """걷기 프레임(색상 그리드) 목록을 돌려준다."""
        width = self.width()
        return [self._grid(frame, width) for frame in self.frame_rows]

    # --- 검증 -----------------------------------------------------------
    def validate(self):
        heights = {len(frame) for frame in self.frame_rows}
        if len(heights) != 1:
            raise ValueError("%s: 프레임마다 줄 수가 다릅니다" % self.key)
        for number, frame in enumerate(self.frame_rows):
            for index, row in enumerate(frame):
                for ch in row:
                    if ch != "." and ch not in self.palette:
                        raise ValueError(
                            "%s: %d번 프레임 %d행에 팔레트에 없는 문자 %r 이 있습니다"
                            % (self.key, number, index, ch)
                        )
        if self.scale_factor <= 0:
            raise ValueError("%s: scale_factor 는 0보다 커야 합니다" % self.key)


# --- 자동 생성 시작: pikachu ---
PIKACHU = Pokemon(
    key="pikachu",
    name_ko="피카츄",
    scale_factor=1 / 3,
    facing="left",
    palette={
        "K": "#feba11",
        "Y": "#feed43",
        "O": "#000000",
        "W": "#542100",
        "R": "#984300",
        "B": "#dd9800",
        "G": "#fefeaa",
        "T": "#101010",
        "D": "#444355",
        "E": "#fdee42",
        "C": "#cb2110",
        "S": "#ed5443",
        "L": "#552000",
        "M": "#fdfefd",
    },
    frame_rows=[
        [
            ".....OO",
            "....OTO",
            "....TTO",
            "...OTTO",
            "...OTTO",
            "...WKBW",
            "...WKKW..............OOOOOO",
            "..WBKKW..........WWOOTDDDTO",
            "..WKKKW........WWKYBTTDTTO",
            "..WKKRRRRRRWWWOKYYYYBTTTO",
            "..WREGGGGYYKBYYYYYYYKBOO",
            "..RYGGGGGGYYYYYYYYYKWO..........RRRR",
            "..KEGGGGGYYYYYYYKWOO.........RRRKYYW",
            ".RYYGGGYYYYYYYYYWO........RRRKYYYYYW",
            ".ODKYYYYYKDOKYYYW......RRRKYYYYYYYEW",
            "ROMRYYYYYRMORYYKW.....RRYYYYYYYYYYYKW",
            "RODREYYYYRDORYYKKW....RBKKKKYYYYYYYYW",
            "RDOEYYYYYKODKYYKKW....RKKKKKKKKKYYYYW",
            "RCYYRKYYYYYYYSSKKW....RKKKKKKKKKKKKKW",
            "WCYBBYYYBYYYSSSCKW....WKKKKKKKKBOOOOO",
            "WCKBKRRBYYYYSSCCKWO...WBKKKBWWWO",
            ".WRKKKKKKKKKKCCKKWO....LKBWW",
            "..WRBBKKKKKKKKKKKKO....WBKO",
            "...LKKKKKKKKKKKKKKO.....OKKWW",
            "...RKKKKKKKKKKKKYYRO.....OKKW",
            "..WKBKKKKKKBKKWEYEWO....LBKO",
            "..OKRKKKKKKRKKOEYYWO...WBBBOO",
            "..OYYRYYYERYYOYYYYKRO...OBBBO",
            "..OKYYRYYRYYKWYYYYYWOOOORRWO",
            "..WLYYWYYWEYWYYYYYYWOWLLWOO",
            ".RKYWWYYYYWWYYYYYYKWROWOO",
            ".RKKYYYYYYYYYYYKKKKRBOO",
            ".WKKKKYYYYYYKKKKKKKKKO",
            ".WBKKKKKKKKKKKKKKKKKKO",
            "..WBKKKKKKKKKKKKKKKKBO",
            "..ORBBRWWWWWBBKKKKKBO",
            ".OKKBOO.....WWWWRBRL",
            ".OOOOO.........OKRKBO",
            "................OOOOO",
        ],
        [
            ".....OO",
            "....OTO",
            "....TTO",
            "...OTTO",
            "...OTTO",
            "...WKBW",
            "...WKKW..............OOOOOO",
            "..WBKKW..........WWOOTDDDTO",
            "..WKKKW........WWKYBTTDTTO",
            "..WKKRRRRRRWWWOKYYYYBTTTO",
            "..WREGGGGYYKBYYYYYYYKBOO",
            "..RYGGGGGGYYYYYYYYYKWO..........RRRR",
            "..KEGGGGGYYYYYYYKWOO.........RRRKYYW",
            ".RYYGGGYYYYYYYYYWO........RRRKYYYYYW",
            ".ODKYYYYYKDOKYYYW......RRRKYYYYYYYEW",
            "ROMRYYYYYRMORYYKW.....RRYYYYYYYYYYYKW",
            "RODREYYYYRDORYYKKW....RBKKKKYYYYYYYYW",
            "RDOEYYYYYKODKYYKKW....RKKKKKKKKKYYYYW",
            "RCYYRKYYYYYYYSSKKW....RKKKKKKKKKKKKKW",
            "WCYBBYYYBYYYSSSCKW....WKKKKKKKKBOOOOO",
            "WCKBKRRBYYYYSSCCKWO...WBKKKBWWWO",
            ".WRKKKKKKKKKKCCKKWO....LKBWW",
            "..WRBBKKKKKKKKKKKKO....WBKO",
            "...LKKKKKKKKKKKKKKO.....OKKWW",
            "...RKKKKKKKKKKKKYYRO.....OKKW",
            "..WKBKKKKKKBKKWEYEWO....LBKO",
            "..OKRKKKKKKRKKOEYYWO...WBBBOO",
            "..OYYRYYYERYYOYYYYKRO...OBBBO",
            "..OKYYRYYRYYKWYYYYYWOOOORRWO",
            "..WLYYWYYWEYWYYYYYYWOWLLWOO",
            ".RKYWWYYYYWWYYYYYYKWROWOO",
            ".RKKYYYYYYYYYYYKKKKRBOO",
            ".WKKKKYYYYYYKKKKKKKKKO",
            ".WBKORBBRKKKKKKKKKKKKO",
            "..WOKKBOOKKKKKKKKKKKBO",
            "...OOOOOWWWWBBKWWRBRL",
            "............WW..OKRKBO",
            ".................OOOOO",
            ".",
        ],
        [
            ".....OO",
            "....OTO",
            "....TTO",
            "...OTTO",
            "...OTTO",
            "...WKBW",
            "...WKKW..............OOOOOO",
            "..WBKKW..........WWOOTDDDTO",
            "..WKKKW........WWKYBTTDTTO",
            "..WKKRRRRRRWWWOKYYYYBTTTO",
            "..WREGGGGYYKBYYYYYYYKBOO",
            "..RYGGGGGGYYYYYYYYYKWO..........RRRR",
            "..KEGGGGGYYYYYYYKWOO.........RRRKYYW",
            ".RYYGGGYYYYYYYYYWO........RRRKYYYYYW",
            ".ODKYYYYYKDOKYYYW......RRRKYYYYYYYEW",
            "ROMRYYYYYRMORYYKW.....RRYYYYYYYYYYYKW",
            "RODREYYYYRDORYYKKW....RBKKKKYYYYYYYYW",
            "RDOEYYYYYKODKYYKKW....RKKKKKKKKKYYYYW",
            "RCYYRKYYYYYYYSSKKW....RKKKKKKKKKKKKKW",
            "WCYBBYYYBYYYSSSCKW....WKKKKKKKKBOOOOO",
            "WCKBKRRBYYYYSSCCKWO...WBKKKBWWWO",
            ".WRKKKKKKKKKKCCKKWO....LKBWW",
            "..WRBBKKKKKKKKKKKKO....WBKO",
            "...LKKKKKKKKKKKKKKO.....OKKWW",
            "...RKKKKKKKKKKKKYYRO.....OKKW",
            "..WKBKKKKKKBKKWEYEWO....LBKO",
            "..OKRKKKKKKRKKOEYYWO...WBBBOO",
            "..OYYRYYYERYYOYYYYKRO...OBBBO",
            "..OKYYRYYRYYKWYYYYYWOOOORRWO",
            "..WLYYWYYWEYWYYYYYYWOWLLWOO",
            ".RKYWWYYYYWWYYYYYYKWROWOO",
            ".RKKYYYYYYYYYYYKKKKRBOO",
            ".WKKKKYYYYYYKKKKKKKKKO",
            ".WBKKKKKKKKKKKKKKKKKKO",
            "..WBKKKKKKKKKKKKKKKKBO",
            "..ORBBRWWWWWBBKKKKKBO",
            ".OKKBOO.....WWWWRBRL",
            ".OOOOO.........OKRKBO",
            "................OOOOO",
        ],
        [
            ".....OO",
            "....OTO",
            "....TTO",
            "...OTTO",
            "...OTTO",
            "...WKBW",
            "...WKKW..............OOOOOO",
            "..WBKKW..........WWOOTDDDTO",
            "..WKKKW........WWKYBTTDTTO",
            "..WKKRRRRRRWWWOKYYYYBTTTO",
            "..WREGGGGYYKBYYYYYYYKBOO",
            "..RYGGGGGGYYYYYYYYYKWO..........RRRR",
            "..KEGGGGGYYYYYYYKWOO.........RRRKYYW",
            ".RYYGGGYYYYYYYYYWO........RRRKYYYYYW",
            ".ODKYYYYYKDOKYYYW......RRRKYYYYYYYEW",
            "ROMRYYYYYRMORYYKW.....RRYYYYYYYYYYYKW",
            "RODREYYYYRDORYYKKW....RBKKKKYYYYYYYYW",
            "RDOEYYYYYKODKYYKKW....RKKKKKKKKKYYYYW",
            "RCYYRKYYYYYYYSSKKW....RKKKKKKKKKKKKKW",
            "WCYBBYYYBYYYSSSCKW....WKKKKKKKKBOOOOO",
            "WCKBKRRBYYYYSSCCKWO...WBKKKBWWWO",
            ".WRKKKKKKKKKKCCKKWO....LKBWW",
            "..WRBBKKKKKKKKKKKKO....WBKO",
            "...LKKKKKKKKKKKKKKO.....OKKWW",
            "...RKKKKKKKKKKKKYYRO.....OKKW",
            "..WKBKKKKKKBKKWEYEWO....LBKO",
            "..OKRKKKKKKRKKOEYYWO...WBBBOO",
            "..OYYRYYYERYYOYYYYKRO...OBBBO",
            "..OKYYRYYRYYKWYYYYYWOOOORRWO",
            "..WLYYWYYWEYWYYYYYYWOWLLWOO",
            ".RKYWWYYYYWWYYYYYYKWROWOO",
            ".RKKYYYYYYYYYYYKKKKRBOO",
            ".WKKKKYYYYYYKKKKKKKKKO",
            ".WBKKKKKKKKKKKKKKKKKKO",
            "..WORBBRKKKKKKKKWWRBRL",
            "..OKKBOOWWWWBBKKKOKRKBO",
            "..OOOOO.....WW....OOOOO",
            ".",
            ".",
        ],
    ],
)
# --- 자동 생성 끝: pikachu ---

# --- 자동 생성 시작: charmander ---
CHARMANDER = Pokemon(
    key="charmander",
    name_ko="파이리",
    scale_factor=1 / 3,
    facing="left",
    palette={
        "K": "#fc9443",
        "Y": "#d95339",
        "O": "#170c0c",
        "W": "#862b09",
        "R": "#fdd47a",
        "B": "#e7aa5b",
        "G": "#db3f0b",
        "T": "#fccf10",
        "D": "#fbc364",
        "E": "#f4a10c",
        "C": "#11387f",
        "S": "#fafcfb",
        "L": "#2885a8",
        "M": "#36aae9",
    },
    frame_rows=[
        [
            ".........YYWWW",
            ".......YYKKKKKWW",
            "......YDKKKKKKKKO",
            ".....YDDDKKKKKKKO",
            ".....YDDDKKKKKKKKO",
            "....YKKDKKKKKYKKKO",
            "....YKKKKKKKYKKKKYO",
            "....CYKKKKKKYKCCYYO",
            "....LYKKKKKKKCCCWYO",
            ".....KKKKKKKKSOLWYO",
            "....OKKKKKKKKSCMWYO.............Y",
            "...WCKKKKKKKKWLMYYO.............YT",
            "...WDDDKKKKKKKYYYYO.............YT",
            "...WDDKKYKKKKYYWYYO............GET",
            "....WKKKKKKKYWWYYO......WW.....GTTE",
            "....OOKKKKWWOSYYYO..WWWWYO.....GETTG",
            ".WW...OOOOGGWYYYYWWWKKKKYO.....GTGTE",
            ".OYWWWOYYWWWYYOYYKKKKKKYYYO...GGGGTTG",
            ".OYKKKYOOKKYOOYYYYKKYYYYOO....GGEGGTEG",
            "OYYYKKYYYOOOYYYYYYYYYYYO......GTTGTTTG",
            ".OOYYYYYYYYYYYYYYYYYYOO.......GETTTTTG",
            "...OOYYYYWYBBBYYYYWWO.........GEEETTEG",
            ".....OOYYWBBBBBYYKKO...........GEGEEGG",
            ".......OWYRRRRRBKKKO............YGWGG",
            "........WBRRRRRRKKKYO............WWG",
            "........WRRRRRRRKKKKO............WDO",
            "........WRRRRRRRKKKKKO...........WKO",
            ".......WBRRRRRRRBKKKKO..........WKKO",
            ".......WRRRRRRRRRKKKKO........WWKKYO",
            "......WWRRRRRRRRRYKKKKO....WWWKKKYO",
            ".....WKYBRRRRRRRBYKKKKYOWWWKKKKKYBO",
            ".....WKKYBRRRRBBYKKKKKKOYYYYKKYBBO",
            "....OKKKWBBBBBBBYKKKKKKYOYYYYYBBO",
            "....OKKKKOBBBBBBYKKKKKYYOYYYBBBO",
            "....OKKKKYOBBBBBWYKKKYYYOBBBBOO",
            ".....OKKYYYOOBBBWYYYYYYYOBBWW",
            "......OYYYYYYOOOOWYYYYYOWWW",
            "......OYYYYOO.....WYYYYO",
            ".....OYYYYYO......WKKKYO",
            "....OSWSYYO.......WYKKKYO",
            ".....OOOOO.........OSWSWSO",
            "....................OOOOO",
        ],
        [
            ".........YYWWW",
            ".......YYKKKKKWW",
            "......YDKKKKKKKKO",
            ".....YDDDKKKKKKKO",
            ".....YDDDKKKKKKKKO",
            "....YKKDKKKKKYKKKO",
            "....YKKKKKKKYKKKKYO",
            "....CYKKKKKKYKCCYYO",
            "....LYKKKKKKKCCCWYO",
            ".....KKKKKKKKSOLWYO",
            "....OKKKKKKKKSCMWYO.............Y",
            "...WCKKKKKKKKWLMYYO.............YT",
            "...WDDDKKKKKKKYYYYO.............YT",
            "...WDDKKYKKKKYYWYYO............GET",
            "....WKKKKKKKYWWYYO......WW.....GTTE",
            "....OOKKKKWWOSYYYO..WWWWYO.....GETTG",
            ".WW...OOOOGGWYYYYWWWKKKKYO.....GTGTE",
            ".OYWWWOYYWWWYYOYYKKKKKKYYYO...GGGGTTG",
            ".OYKKKYOOKKYOOYYYYKKYYYYOO....GGEGGTEG",
            "OYYYKKYYYOOOYYYYYYYYYYYO......GTTGTTTG",
            ".OOYYYYYYYYYYYYYYYYYYOO.......GETTTTTG",
            "...OOYYYYWYBBBYYYYWWO.........GEEETTEG",
            ".....OOYYWBBBBBYYKKO...........GEGEEGG",
            ".......OWYRRRRRBKKKO............YGWGG",
            "........WBRRRRRRKKKYO............WWG",
            "........WRRRRRRRKKKKO............WDO",
            "........WRRRRRRRKKKKKO...........WKO",
            ".......WBRRRRRRRBKKKKO..........WKKO",
            ".......WRRRRRRRRRKKKKO........WWKKYO",
            "......WWRRRRRRRRRYKKKKO....WWWKKKYO",
            ".....WKYBRRRRRRRBYKKKKYOWWWKKKKKYBO",
            ".....WKKYBRRRRBBYKKKKKKOYYYYKKYBBO",
            "....OKKKWBBBBBBBYKKKKKKYOYYYYYBBO",
            "....OKKKKOBBBBBBYKKKKKYYOYYYBBBO",
            "....OKKKKYOBBBBBWYKKKYYYOBBBBOO",
            ".....OKKOYYYYOOBWYYYYYYYOBBWW",
            "......OOYYYYYOOOOWYWYYYYOWW",
            "......OSWSYYO......WKKKYO",
            ".......OOOOO.......WYKKKYO",
            "....................OSWSWSO",
            ".....................OOOOO",
            ".",
        ],
        [
            ".........YYWWW",
            ".......YYKKKKKWW",
            "......YDKKKKKKKKO",
            ".....YDDDKKKKKKKO",
            ".....YDDDKKKKKKKKO",
            "....YKKDKKKKKYKKKO",
            "....YKKKKKKKYKKKKYO",
            "....CYKKKKKKYKCCYYO",
            "....LYKKKKKKKCCCWYO",
            ".....KKKKKKKKSOLWYO",
            "....OKKKKKKKKSCMWYO.............Y",
            "...WCKKKKKKKKWLMYYO.............YT",
            "...WDDDKKKKKKKYYYYO.............YT",
            "...WDDKKYKKKKYYWYYO............GET",
            "....WKKKKKKKYWWYYO......WW.....GTTE",
            "....OOKKKKWWOSYYYO..WWWWYO.....GETTG",
            ".WW...OOOOGGWYYYYWWWKKKKYO.....GTGTE",
            ".OYWWWOYYWWWYYOYYKKKKKKYYYO...GGGGTTG",
            ".OYKKKYOOKKYOOYYYYKKYYYYOO....GGEGGTEG",
            "OYYYKKYYYOOOYYYYYYYYYYYO......GTTGTTTG",
            ".OOYYYYYYYYYYYYYYYYYYOO.......GETTTTTG",
            "...OOYYYYWYBBBYYYYWWO.........GEEETTEG",
            ".....OOYYWBBBBBYYKKO...........GEGEEGG",
            ".......OWYRRRRRBKKKO............YGWGG",
            "........WBRRRRRRKKKYO............WWG",
            "........WRRRRRRRKKKKO............WDO",
            "........WRRRRRRRKKKKKO...........WKO",
            ".......WBRRRRRRRBKKKKO..........WKKO",
            ".......WRRRRRRRRRKKKKO........WWKKYO",
            "......WWRRRRRRRRRYKKKKO....WWWKKKYO",
            ".....WKYBRRRRRRRBYKKKKYOWWWKKKKKYBO",
            ".....WKKYBRRRRBBYKKKKKKOYYYYKKYBBO",
            "....OKKKWBBBBBBBYKKKKKKYOYYYYYBBO",
            "....OKKKKOBBBBBBYKKKKKYYOYYYBBBO",
            "....OKKKKYOBBBBBWYKKKYYYOBBBBOO",
            ".....OKKYYYOOBBBWYYYYYYYOBBWW",
            "......OYYYYYYOOOOWYYYYYOWWW",
            "......OYYYYOO.....WYYYYO",
            ".....OYYYYYO......WKKKYO",
            "....OSWSYYO.......WYKKKYO",
            ".....OOOOO.........OSWSWSO",
            "....................OOOOO",
        ],
        [
            ".........YYWWW",
            ".......YYKKKKKWW",
            "......YDKKKKKKKKO",
            ".....YDDDKKKKKKKO",
            ".....YDDDKKKKKKKKO",
            "....YKKDKKKKKYKKKO",
            "....YKKKKKKKYKKKKYO",
            "....CYKKKKKKYKCCYYO",
            "....LYKKKKKKKCCCWYO",
            ".....KKKKKKKKSOLWYO",
            "....OKKKKKKKKSCMWYO.............Y",
            "...WCKKKKKKKKWLMYYO.............YT",
            "...WDDDKKKKKKKYYYYO.............YT",
            "...WDDKKYKKKKYYWYYO............GET",
            "....WKKKKKKKYWWYYO......WW.....GTTE",
            "....OOKKKKWWOSYYYO..WWWWYO.....GETTG",
            ".WW...OOOOGGWYYYYWWWKKKKYO.....GTGTE",
            ".OYWWWOYYWWWYYOYYKKKKKKYYYO...GGGGTTG",
            ".OYKKKYOOKKYOOYYYYKKYYYYOO....GGEGGTEG",
            "OYYYKKYYYOOOYYYYYYYYYYYO......GTTGTTTG",
            ".OOYYYYYYYYYYYYYYYYYYOO.......GETTTTTG",
            "...OOYYYYWYBBBYYYYWWO.........GEEETTEG",
            ".....OOYYWBBBBBYYKKO...........GEGEEGG",
            ".......OWYRRRRRBKKKO............YGWGG",
            "........WBRRRRRRKKKYO............WWG",
            "........WRRRRRRRKKKKO............WDO",
            "........WRRRRRRRKKKKKO...........WKO",
            ".......WBRRRRRRRBKKKKO..........WKKO",
            ".......WRRRRRRRRRKKKKO........WWKKYO",
            "......WWRRRRRRRRRYKKKKO....WWWKKKYO",
            ".....WKYBRRRRRRRBYKKKKYOWWWKKKKKYBO",
            ".....WKKYBRRRRBBYKKKKKKOYYYYKKYBBO",
            "....OKKKWBBBBBBBYKKKKKKYOYYYYYBBO",
            "....OKKKKOBBBBBBYKKKKKYYOYYYBBBO",
            "....OKKKKYOBBBBBWYKKKYYYOBBBBOO",
            ".....OKKYYYOOBBBWYYYWYYYYOBWW",
            "......OOYYYYOOOOOWYYWKKKYOW",
            "......OYYYYYO.......WYKKKYO",
            ".....OSWSYYO.........OSWSWSO",
            "......OOOOO...........OOOOO",
            ".",
            ".",
        ],
    ],
)
# --- 자동 생성 끝: charmander ---


# --- 자동 생성 시작: bulbasaur ---
BULBASAUR = Pokemon(
    key="bulbasaur",
    name_ko="이상해씨",
    scale_factor=1 / 3,
    facing="left",
    palette={
        "K": "#599cb4",
        "Y": "#c8ecea",
        "O": "#a3d7df",
        "W": "#849b48",
        "R": "#2f606b",
        "B": "#457e90",
        "G": "#050707",
        "T": "#eaf9a8",
        "D": "#161819",
        "E": "#c3d476",
        "C": "#a33029",
        "S": "#57623b",
        "L": "#29525a",
        "M": "#da8785",
    },
    frame_rows=[
        [
            "...........................S",
            ".........................SSEGG",
            ".................WWWWSSSSEWWSWG",
            "...............WWTTTTTTEEEWESWG",
            "..............WTTTTTTTTTWWEEWSG",
            "...RLY.......WTTTTTLGWWWTEEEWSG",
            "..KYYRLYBRRRRRRRLLLYOGTTTTEEESWGY",
            "..KYYYRROYYYYOOOLYYYOGTTTTEEESWWG",
            "..KOKYYYYYBBBYOOYYYOODTTTTEEEWSWG",
            "..KBYYYYYBBBBYYOOOOOOKGTTTEEEWSWWG",
            "..BYYYYYBBBBYYYOOOOOOKGTTEEEEWWSWG",
            "..BYYYYYBBBYYYYOKKOOOKDTEEEEWWWSWWG",
            ".BROOYYYYYYYYOYBYYROKKKGEEEWWWWSWWG",
            ".RCKYOYYYBBYOYBCCYYRKKKGLEWWWWWSWWG",
            ".RCKYOYYBBBYOYBMCYYRKKKGRWWWWWSWWWG",
            "BYMYKYYYBBYYYKCYCCYYKKKRKRWWWWSWWWD",
            "BYCYKOYYYYYYOKCYMMYYKKKBKKRWWSWWWG",
            "BOCCKOOOOOOOOKCCMMYKKKKKKKKRRWWWWD",
            "RGOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
            "BBDROOBOBOOOOOOOBRGGKKBKKKRRKKRG",
            ".RBYCCOOOOOBLGGGYBKKKKRKKKRRRKKR",
            "..BBBBCCCCCCCCCCBKKKKRKKKKKRRKKKR",
            "...DDBBBCCMMMMBKKKKDGKKKKKBKKKKKRY",
            ".....DGBKKKKKKKKDGGKKKBKKLKKKRKKKG",
            ".....RKDDGGGGGGGKKKKKKRKKDKKRRRKKG",
            ".....KOOOKRKKKKKKROOKKKRGKKKRRRKKG",
            "......BKOOKRDBKKRKKOOKKRGKKKRRRKKD",
            "......BKOOKKKGDDRKKKOKKRDKKKKRKKG",
            "......KOOOOKKG..KOKKOKKR.DBKBKBKD",
            "......YBOKOKKD..KOOOOKG..BYLYLYB",
            "......RYRYRYD...BOKOKKD...DDDDD",
            ".......DDDDD...RYRYRKD",
            "................DDDDD",
        ],
        [
            "...........................S",
            ".........................SSEGG",
            ".................WWWWSSSSEWWSWG",
            "...............WWTTTTTTEEEWESWG",
            "..............WTTTTTTTTTWWEEWSG",
            "...RLY.......WTTTTTLGWWWTEEEWSG",
            "..KYYRLYBRRRRRRRLLLYOGTTTTEEESWGY",
            "..KYYYRROYYYYOOOLYYYOGTTTTEEESWWG",
            "..KOKYYYYYBBBYOOYYYOODTTTTEEEWSWG",
            "..KBYYYYYBBBBYYOOOOOOKGTTTEEEWSWWG",
            "..BYYYYYBBBBYYYOOOOOOKGTTEEEEWWSWG",
            "..BYYYYYBBBYYYYOKKOOOKDTEEEEWWWSWWG",
            ".BROOYYYYYYYYOYBYYROKKKGEEEWWWWSWWG",
            ".RCKYOYYYBBYOYBCCYYRKKKGLEWWWWWSWWG",
            ".RCKYOYYBBBYOYBMCYYRKKKGRWWWWWSWWWG",
            "BYMYKYYYBBYYYKCYCCYYKKKRKRWWWWSWWWD",
            "BYCYKOYYYYYYOKCYMMYYKKKBKKRWWSWWWG",
            "BOCCKOOOOOOOOKCCMMYKKKKKKKKRRWWWWD",
            "RGOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
            "BBDROOBOBOOOOOOOBRGGKKBKKKRRKKRG",
            ".RBYCCOOOOOBLGGGYBKKKKRKKKRRRKKR",
            "..BBBBCCCCCCCCCCBKKKKRKKKKKRRKKKR",
            "...DDBBBCCMMMMBKKKKDGKKKKKBKKKKKRY",
            ".....DGBKKKKKKKKDGGKKKBKKLKKKRKKKG",
            ".....RKDDGGGGGGGKKKKKKRKKDKKRRRKKG",
            ".....KOOOKRKKKKKKROOKKKRGKKKRRRKKG",
            "......BKOOOOKKGKRKKOOKKRGKKKRRRKKD",
            "......BYBOKOKKDDRKOKKOKKRDBKBKBKD",
            ".......RYRYRYD...KOOOOKG.BYLYLYB",
            "........DDDDD....BOKOKKD..DDDDD",
            "................RYRYRKD",
            ".................DDDDD",
            ".",
        ],
        [
            "...........................S",
            ".........................SSEGG",
            ".................WWWWSSSSEWWSWG",
            "...............WWTTTTTTEEEWESWG",
            "..............WTTTTTTTTTWWEEWSG",
            "...RLY.......WTTTTTLGWWWTEEEWSG",
            "..KYYRLYBRRRRRRRLLLYOGTTTTEEESWGY",
            "..KYYYRROYYYYOOOLYYYOGTTTTEEESWWG",
            "..KOKYYYYYBBBYOOYYYOODTTTTEEEWSWG",
            "..KBYYYYYBBBBYYOOOOOOKGTTTEEEWSWWG",
            "..BYYYYYBBBBYYYOOOOOOKGTTEEEEWWSWG",
            "..BYYYYYBBBYYYYOKKOOOKDTEEEEWWWSWWG",
            ".BROOYYYYYYYYOYBYYROKKKGEEEWWWWSWWG",
            ".RCKYOYYYBBYOYBCCYYRKKKGLEWWWWWSWWG",
            ".RCKYOYYBBBYOYBMCYYRKKKGRWWWWWSWWWG",
            "BYMYKYYYBBYYYKCYCCYYKKKRKRWWWWSWWWD",
            "BYCYKOYYYYYYOKCYMMYYKKKBKKRWWSWWWG",
            "BOCCKOOOOOOOOKCCMMYKKKKKKKKRRWWWWD",
            "RGOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
            "BBDROOBOBOOOOOOOBRGGKKBKKKRRKKRG",
            ".RBYCCOOOOOBLGGGYBKKKKRKKKRRRKKR",
            "..BBBBCCCCCCCCCCBKKKKRKKKKKRRKKKR",
            "...DDBBBCCMMMMBKKKKDGKKKKKBKKKKKRY",
            ".....DGBKKKKKKKKDGGKKKBKKLKKKRKKKG",
            ".....RKDDGGGGGGGKKKKKKRKKDKKRRRKKG",
            ".....KOOOKRKKKKKKROOKKKRGKKKRRRKKG",
            "......BKOOKRDBKKRKKOOKKRGKKKRRRKKD",
            "......BKOOKKKGDDRKKKOKKRDKKKKRKKG",
            "......KOOOOKKG..KOKKOKKR.DBKBKBKD",
            "......YBOKOKKD..KOOOOKG..BYLYLYB",
            "......RYRYRYD...BOKOKKD...DDDDD",
            ".......DDDDD...RYRYRKD",
            "................DDDDD",
        ],
        [
            "...........................S",
            ".........................SSEGG",
            ".................WWWWSSSSEWWSWG",
            "...............WWTTTTTTEEEWESWG",
            "..............WTTTTTTTTTWWEEWSG",
            "...RLY.......WTTTTTLGWWWTEEEWSG",
            "..KYYRLYBRRRRRRRLLLYOGTTTTEEESWGY",
            "..KYYYRROYYYYOOOLYYYOGTTTTEEESWWG",
            "..KOKYYYYYBBBYOOYYYOODTTTTEEEWSWG",
            "..KBYYYYYBBBBYYOOOOOOKGTTTEEEWSWWG",
            "..BYYYYYBBBBYYYOOOOOOKGTTEEEEWWSWG",
            "..BYYYYYBBBYYYYOKKOOOKDTEEEEWWWSWWG",
            ".BROOYYYYYYYYOYBYYROKKKGEEEWWWWSWWG",
            ".RCKYOYYYBBYOYBCCYYRKKKGLEWWWWWSWWG",
            ".RCKYOYYBBBYOYBMCYYRKKKGRWWWWWSWWWG",
            "BYMYKYYYBBYYYKCYCCYYKKKRKRWWWWSWWWD",
            "BYCYKOYYYYYYOKCYMMYYKKKBKKRWWSWWWG",
            "BOCCKOOOOOOOOKCCMMYKKKKKKKKRRWWWWD",
            "RGOOOOOOOOOOOOOOOOKKRKKKKKKKKRWWG",
            "BBDROOBOBOOOOOOOBRGGKKBKKKRRKKRG",
            ".RBYCCOOOOOBLGGGYBKKKKRKKKRRRKKR",
            "..BBBBCCCCCCCCCCBKKKKRKKKKKRRKKKR",
            "...DDBBBCCMMMMBKKKKDGKKKKKBKKKKKRY",
            ".....DGBKKKKKKKKDGGKKKBKKLKKKRKKKG",
            ".....RKDDGGGGGGGKKKKKKRKKDKKRRRKKG",
            ".....KOOOKRKKKKKKROOKKKRGKKKRRRKKG",
            "......BKOOKRDBKKRKOKKOKKRKDBKBKBKD",
            "......BKOOOOKKGDRKOOOOKGDKBYLYLYB",
            ".......YBOKOKKD..BOKOKKD...DDDDD",
            ".......RYRYRYD..RYRYRKD",
            "........DDDDD....DDDDD",
            ".",
            ".",
        ],
    ],
)
# --- 자동 생성 끝: bulbasaur ---


# --- 자동 생성 시작: squirtle ---
SQUIRTLE = Pokemon(
    key="squirtle",
    name_ko="꼬부기",
    scale_factor=1 / 3,
    facing="left",
    palette={
        "K": "#5daa9b",
        "Y": "#94d4cc",
        "O": "#0e1010",
        "W": "#437162",
        "R": "#c77c2d",
        "B": "#e4ab5b",
        "G": "#fde49a",
        "T": "#fcd36b",
        "D": "#782c07",
        "E": "#b4f4ec",
        "C": "#d5ccca",
        "S": "#ba6908",
        "L": "#5f2804",
        "M": "#fcfafa",
    },
    frame_rows=[
        [
            "...........KKKKWW",
            ".........KKEEEEYYWW",
            "........KEEEEYYYYYYW",
            ".......WEEEEYYYYYYYYW",
            "......WYEEEYYYYYYYYYYW",
            "......WYYYYYYYKYYYYYYW",
            ".....WKYYYYYYKYKKKYYYKW",
            ".....WDYYYYYYYKOCCKYKKO",
            ".....WMKYYYYYYOOOCWKKKO",
            ".....WDKYYYYYYOODMWKKKO",
            ".....WOYYYYYYYMODMWKKKO",
            "....WEEYYYYYYYDODMKKKKO",
            "....OEYKYKYYYYYYKKKKKKO",
            ".....OWYYYYYYYYKKWKKKO..KWWW",
            ".K.K..OOYYKWWWWWDDKKKW.KYYKKO",
            ".WYKWOOKOODRRRRDDKKKOKYYYWKO",
            "KYYYYKKOKKDDDDDKKKWOWYYYWWKO",
            "WYYYYYYYOWKKKKKKOOBCKYYYKKO",
            ".WKYYYYYKKWOOOOOBBBWYYYKKKO",
            "..WKKKKKKRBBBBBRRRWKYYKKKO",
            "...WWKKKRBRBRRBTTBWKKKKKOL.....WWWW",
            ".....OOORGTRBGGTTTRWKKKOSSL..WWYYYKW",
            ".......RGGTBGGGGTTRBOOOCSSL.WKYYYYYKW",
            ".......RGGGBGGGGTBBBBLCCSSLWKYYYYYYYW",
            ".......RGGGBGGGGTRTBBLCCSSOKKKYYWWYYKO",
            ".......RRTGRGGGTRTTBBSCCSOLKKKKWYYWYKO",
            ".......RGBRRRBBRRTTTBRSCBSLKKKWKYYYKKO",
            ".......RGGGRGGGTBRTTBRLCCSOKKKOKKKKKO",
            "......KRTGGBGGGGTBRBKKWWCSOKKKOKKKKKO",
            ".....KYYRTTBTGGGTBRKYYYKWCOKKKKOKKKO",
            "....KYYYRRRRRBBBBBKYYYYYKWKKKKKKOOO",
            "....KYYYYRBBBBRRRRWYYYYYKOKKKKOOO",
            "....WYYYYKDBBBBBRRWYYYYYKWOOOO",
            "....OKYYKKKDDRRRRROKYYYKKKO",
            ".....OKKKKKKKDDOOOOWKKKKKKO",
            ".....WKKKKKKO......OKKKKKKO",
            "....WYKWYKOO........OKKKKKKO",
            ".....OO.OO..........OYKOYWOO",
            ".....................OO.OO",
        ],
        [
            "...........KKKKWW",
            ".........KKEEEEYYWW",
            "........KEEEEYYYYYYW",
            ".......WEEEEYYYYYYYYW",
            "......WYEEEYYYYYYYYYYW",
            "......WYYYYYYYKYYYYYYW",
            ".....WKYYYYYYKYKKKYYYKW",
            ".....WDYYYYYYYKOCCKYKKO",
            ".....WMKYYYYYYOOOCWKKKO",
            ".....WDKYYYYYYOODMWKKKO",
            ".....WOYYYYYYYMODMWKKKO",
            "....WEEYYYYYYYDODMKKKKO",
            "....OEYKYKYYYYYYKKKKKKO",
            ".....OWYYYYYYYYKKWKKKO..KWWW",
            ".K.K..OOYYKWWWWWDDKKKW.KYYKKO",
            ".WYKWOOKOODRRRRDDKKKOKYYYWKO",
            "KYYYYKKOKKDDDDDKKKWOWYYYWWKO",
            "WYYYYYYYOWKKKKKKOOBCKYYYKKO",
            ".WKYYYYYKKWOOOOOBBBWYYYKKKO",
            "..WKKKKKKRBBBBBRRRWKYYKKKO",
            "...WWKKKRBRBRRBTTBWKKKKKOL.....WWWW",
            ".....OOORGTRBGGTTTRWKKKOSSL..WWYYYKW",
            ".......RGGTBGGGGTTRBOOOCSSL.WKYYYYYKW",
            ".......RGGGBGGGGTBBBBLCCSSLWKYYYYYYYW",
            ".......RGGGBGGGGTRTBBLCCSSOKKKYYWWYYKO",
            ".......RRTGRGGGTRTTBBSCCSOLKKKKWYYWYKO",
            ".......RGBRRRBBRRTTTBRSCBSLKKKWKYYYKKO",
            ".......RGGGRGGGTBRTTBRLCCSOKKKOKKKKKO",
            "......KRTGGBGGGGTBRBKKWWCSOKKKOKKKKKO",
            ".....KYYRTTBTGGGTBRKYYYKWCOKKKKOKKKO",
            "....KYYYRRRRRBBBBBKYYYYYKWKKKKKKOOO",
            "....KYYYYRBBBBRRRRWYYYYYKOKKKKOOO",
            "....WYYOKKKKKKKBRRWYYYYYKWOOOO",
            "....OKYWKKKKKKORRROKYYYKKKO",
            "......WYKWYKOODOOOOWOKKKKKKO",
            ".......OO.OO.........OKKKKKKO",
            ".....................OYKOYWOO",
            "......................OO.OO",
            ".",
        ],
        [
            "...........KKKKWW",
            ".........KKEEEEYYWW",
            "........KEEEEYYYYYYW",
            ".......WEEEEYYYYYYYYW",
            "......WYEEEYYYYYYYYYYW",
            "......WYYYYYYYKYYYYYYW",
            ".....WKYYYYYYKYKKKYYYKW",
            ".....WDYYYYYYYKOCCKYKKO",
            ".....WMKYYYYYYOOOCWKKKO",
            ".....WDKYYYYYYOODMWKKKO",
            ".....WOYYYYYYYMODMWKKKO",
            "....WEEYYYYYYYDODMKKKKO",
            "....OEYKYKYYYYYYKKKKKKO",
            ".....OWYYYYYYYYKKWKKKO..KWWW",
            ".K.K..OOYYKWWWWWDDKKKW.KYYKKO",
            ".WYKWOOKOODRRRRDDKKKOKYYYWKO",
            "KYYYYKKOKKDDDDDKKKWOWYYYWWKO",
            "WYYYYYYYOWKKKKKKOOBCKYYYKKO",
            ".WKYYYYYKKWOOOOOBBBWYYYKKKO",
            "..WKKKKKKRBBBBBRRRWKYYKKKO",
            "...WWKKKRBRBRRBTTBWKKKKKOL.....WWWW",
            ".....OOORGTRBGGTTTRWKKKOSSL..WWYYYKW",
            ".......RGGTBGGGGTTRBOOOCSSL.WKYYYYYKW",
            ".......RGGGBGGGGTBBBBLCCSSLWKYYYYYYYW",
            ".......RGGGBGGGGTRTBBLCCSSOKKKYYWWYYKO",
            ".......RRTGRGGGTRTTBBSCCSOLKKKKWYYWYKO",
            ".......RGBRRRBBRRTTTBRSCBSLKKKWKYYYKKO",
            ".......RGGGRGGGTBRTTBRLCCSOKKKOKKKKKO",
            "......KRTGGBGGGGTBRBKKWWCSOKKKOKKKKKO",
            ".....KYYRTTBTGGGTBRKYYYKWCOKKKKOKKKO",
            "....KYYYRRRRRBBBBBKYYYYYKWKKKKKKOOO",
            "....KYYYYRBBBBRRRRWYYYYYKOKKKKOOO",
            "....WYYYYKDBBBBBRRWYYYYYKWOOOO",
            "....OKYYKKKDDRRRRROKYYYKKKO",
            ".....OKKKKKKKDDOOOOWKKKKKKO",
            ".....WKKKKKKO......OKKKKKKO",
            "....WYKWYKOO........OKKKKKKO",
            ".....OO.OO..........OYKOYWOO",
            ".....................OO.OO",
        ],
        [
            "...........KKKKWW",
            ".........KKEEEEYYWW",
            "........KEEEEYYYYYYW",
            ".......WEEEEYYYYYYYYW",
            "......WYEEEYYYYYYYYYYW",
            "......WYYYYYYYKYYYYYYW",
            ".....WKYYYYYYKYKKKYYYKW",
            ".....WDYYYYYYYKOCCKYKKO",
            ".....WMKYYYYYYOOOCWKKKO",
            ".....WDKYYYYYYOODMWKKKO",
            ".....WOYYYYYYYMODMWKKKO",
            "....WEEYYYYYYYDODMKKKKO",
            "....OEYKYKYYYYYYKKKKKKO",
            ".....OWYYYYYYYYKKWKKKO..KWWW",
            ".K.K..OOYYKWWWWWDDKKKW.KYYKKO",
            ".WYKWOOKOODRRRRDDKKKOKYYYWKO",
            "KYYYYKKOKKDDDDDKKKWOWYYYWWKO",
            "WYYYYYYYOWKKKKKKOOBCKYYYKKO",
            ".WKYYYYYKKWOOOOOBBBWYYYKKKO",
            "..WKKKKKKRBBBBBRRRWKYYKKKO",
            "...WWKKKRBRBRRBTTBWKKKKKOL.....WWWW",
            ".....OOORGTRBGGTTTRWKKKOSSL..WWYYYKW",
            ".......RGGTBGGGGTTRBOOOCSSL.WKYYYYYKW",
            ".......RGGGBGGGGTBBBBLCCSSLWKYYYYYYYW",
            ".......RGGGBGGGGTRTBBLCCSSOKKKYYWWYYKO",
            ".......RRTGRGGGTRTTBBSCCSOLKKKKWYYWYKO",
            ".......RGBRRRBBRRTTTBRSCBSLKKKWKYYYKKO",
            ".......RGGGRGGGTBRTTBRLCCSOKKKOKKKKKO",
            "......KRTGGBGGGGTBRBKKWWCSOKKKOKKKKKO",
            ".....KYYRTTBTGGGTBRKYYYKWCOKKKKOKKKO",
            "....KYYYRRRRRBBBBBKYYYYYKWKKKKKKOOO",
            "....KYYYYRBBBBRRRRWYYYYYKOKKKKOOO",
            "....WYYYYKDBBBBBRRWYYYYYKWOOOO",
            "....OKOKKKKKKKRRRROKYOKKKKKKO",
            "......WKKKKKKODOOOOWKKOKKKKKKO",
            ".....WYKWYKOO.........OYKOYWOO",
            "......OO.OO............OO.OO",
            ".",
            ".",
        ],
    ],
)
# --- 자동 생성 끝: squirtle ---


POKEMON = {p.key: p for p in (PIKACHU, CHARMANDER, BULBASAUR, SQUIRTLE)}


def validate_all():
    """모든 스프라이트 데이터가 정상인지 확인한다."""
    for pokemon in POKEMON.values():
        pokemon.validate()
        frames = pokemon.frames()
        widths = {len(row) for frame in frames for row in frame}
        heights = {len(frame) for frame in frames}
        if len(widths) != 1 or len(heights) != 1:
            raise ValueError("%s: 프레임 크기가 서로 다릅니다" % pokemon.key)
        if len(frames) < 2:
            raise ValueError("%s: 걷기 프레임이 2장 이상이어야 합니다" % pokemon.key)
    return True


if __name__ == "__main__":
    validate_all()
    for pokemon in POKEMON.values():
        frame = pokemon.frames()[0]
        print("%s (%s) %dx%d, %d프레임, x%.2f" % (
            pokemon.name_ko, pokemon.key, len(frame[0]), len(frame),
            len(pokemon.frames()), pokemon.scale_factor,
        ))
